/**
 * PuniCodex — The Sanctum · Admin Portal shell (portal.js v2)
 *
 * Auth guard, /me-driven role-based nav, API wrapper (x-admin-token +
 * trailing slashes), toasts, modal, sparklines, and formatting helpers.
 * Loaded by every portal page except the login screen.
 *
 * The shell renders a fixed obsidian sidebar (sectioned nav with labels,
 * gold active state, user footer) plus a slim top bar (breadcrumb, snapshot
 * time, refresh). On mobile the sidebar becomes a backdrop drawer driven by
 * the hamburger in the top bar.
 *
 * Canonical source: platform/public/admin-portal/portal.js
 * The copy at /admin-portal/portal.js is GENERATED by scripts/sync-admin-portal.js.
 */
(function () {
  'use strict';

  const TOKEN_KEY = 'punicodex_portal_token';

  // Pages set <body data-depth="1"> when they live one directory below the
  // portal root (applications/, patrons/, scholars/, users/, …).
  const depth = document.body && document.body.getAttribute('data-depth') === '1' ? 1 : 0;
  const PREFIX = depth === 1 ? '../' : './';
  const LOGIN_PATH = `${PREFIX}login/`;

  // Sectioned navigation. Each item: { id, label, href, permission } — the
  // permission is checked against the role's permission set from /me (see
  // can()). Items whose pages are still being built are listed anyway: the
  // shell renders every visible item whether or not the target exists yet.
  //
  // NOTE: Change Requests is gated on the 'ops' permission — the same
  // permission its endpoint enforces — so non-ops roles never see a link
  // that would 403 on arrival.
  const NAV_SECTIONS = [
    {
      id: 'command',
      label: 'Command',
      items: [
        { id: 'dashboard', label: 'Dashboard', href: PREFIX, permission: 'read' },
        { id: 'analytics', label: 'Analytics', href: `${PREFIX}analytics/`, permission: 'read' },
      ],
    },
    {
      id: 'work',
      label: 'Work',
      items: [
        {
          id: 'applications',
          label: 'Applications',
          href: `${PREFIX}applications/`,
          permission: 'read',
        },
        { id: 'requests', label: 'Change Requests', href: `${PREFIX}requests/`, permission: 'ops' },
      ],
    },
    {
      id: 'leasing',
      label: 'Leasing',
      items: [
        { id: 'leasing', label: 'Leasing', href: `${PREFIX}leasing/`, permission: 'read' },
        { id: 'patrons', label: 'Patrons', href: `${PREFIX}leasing/?tab=patrons`, permission: 'read' },
      ],
    },
    {
      id: 'content',
      label: 'Content',
      items: [
        {
          id: 'scholars',
          label: 'Scholars Review',
          href: `${PREFIX}scholars/`,
          permission: 'read',
        },
        { id: 'merch', label: 'Creator Merch', href: `${PREFIX}merch/`, permission: 'read' },
      ],
    },
    {
      id: 'people',
      label: 'People',
      items: [
        { id: 'newsletter', label: 'Newsletter', href: `${PREFIX}newsletter/`, permission: 'read' },
        { id: 'users', label: 'Users', href: `${PREFIX}users/`, permission: 'users' },
      ],
    },
    {
      id: 'system',
      label: 'System',
      items: [
        { id: 'system', label: 'System', href: `${PREFIX}system/`, permission: 'read' },
        { id: 'api-keys', label: 'API Keys', href: `${PREFIX}api-keys/`, permission: 'read' },
        { id: 'legacy', label: 'Legacy Tools', href: `${PREFIX}legacy/`, permission: 'read' },
      ],
    },
  ];

  // Flat view of the sectioned model (kept for consumers that iterate items).
  const NAV_ITEMS = NAV_SECTIONS.reduce((flat, section) => flat.concat(section.items), []);

  let shellContext = null;
  let mePromise = null;

  // ── Token ──────────────────────────────────────────────────

  function getToken() {
    try {
      return localStorage.getItem(TOKEN_KEY);
    } catch {
      return null;
    }
  }

  function setToken(token) {
    try {
      localStorage.setItem(TOKEN_KEY, token);
    } catch {
      /* storage unavailable — session lives for this page view only */
    }
  }

  function clearToken() {
    try {
      localStorage.removeItem(TOKEN_KEY);
    } catch {
      /* ignore */
    }
  }

  function redirectToLogin() {
    clearToken();
    const here = window.location.pathname + window.location.search;
    window.location.href = `${LOGIN_PATH}?redirect=${encodeURIComponent(here)}`;
  }

  // ── API wrapper ────────────────────────────────────────────

  // The Vercel router 308-redirects bare function paths; every portal call
  // must carry a trailing slash before any query string.
  function withTrailingSlash(path) {
    const q = path.indexOf('?');
    const base = q === -1 ? path : path.slice(0, q);
    const rest = q === -1 ? '' : path.slice(q);
    return (base.charAt(base.length - 1) === '/' ? base : `${base}/`) + rest;
  }

  function apiError(message, status, data) {
    const err = new Error(message);
    err.status = status;
    err.code = data?.code ? data.code : null;
    err.data = data || null;
    return err;
  }

  async function api(path, options) {
    const opts = options || {};
    const headers = { Accept: 'application/json' };
    if (opts.headers) {
      for (const k in opts.headers) headers[k] = opts.headers[k];
    }
    const token = getToken();
    if (token) headers['x-admin-token'] = token;

    const fetchOpts = { method: opts.method || 'GET', headers };
    if (opts.body !== undefined) {
      headers['Content-Type'] = 'application/json';
      fetchOpts.body = typeof opts.body === 'string' ? opts.body : JSON.stringify(opts.body);
    }

    const res = await fetch(withTrailingSlash(path), fetchOpts);
    let data = null;
    try {
      data = await res.json();
    } catch {
      data = null;
    }

    if (res.status === 401) {
      redirectToLogin();
      throw apiError(data?.error || 'Session expired. Please sign in again.', 401, data);
    }
    if (!res.ok) {
      throw apiError(data?.error || `Request failed (${res.status})`, res.status, data);
    }
    return data;
  }

  function me() {
    if (!mePromise) {
      mePromise = api('/api/admin/portal/me/');
    }
    return mePromise;
  }

  function can(permission) {
    if (!permission || permission === 'read') return true;
    if (!shellContext?.permissions) return false;
    return shellContext.permissions.indexOf(permission) !== -1;
  }

  // ── Shell rendering ────────────────────────────────────────

  function findNavContext(pageId) {
    for (const section of NAV_SECTIONS) {
      for (const item of section.items) {
        if (item.id === pageId) return { section, item };
      }
    }
    return { section: null, item: null };
  }

  function renderNavSections(pageId) {
    return NAV_SECTIONS.map((section) => {
      const items = section.items.filter((item) => can(item.permission));
      if (items.length === 0) return '';
      const links = items
        .map((item) => {
          const active = item.id === pageId ? ' active' : '';
          const current = item.id === pageId ? ' aria-current="page"' : '';
          return `<a class="pz-nav-item${active}" href="${item.href}"${current}>${escapeHtml(item.label)}</a>`;
        })
        .join('');
      return (
        `<div class="pz-nav-section"><span class="pz-nav-label">${escapeHtml(section.label)}</span>` +
        `${links}</div>`
      );
    }).join('');
  }

  function setDrawerOpen(open) {
    document.body.classList.toggle('pz-drawer-open', open);
    const toggle = document.getElementById('pz-drawer-toggle');
    if (toggle) toggle.setAttribute('aria-expanded', open ? 'true' : 'false');
  }

  function wireDrawer() {
    const toggle = document.getElementById('pz-drawer-toggle');
    const backdrop = document.getElementById('pz-backdrop');
    if (!toggle || !backdrop) return;

    toggle.addEventListener('click', () => {
      setDrawerOpen(!document.body.classList.contains('pz-drawer-open'));
    });
    backdrop.addEventListener('click', () => {
      setDrawerOpen(false);
      toggle.focus();
    });
    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape' && document.body.classList.contains('pz-drawer-open')) {
        setDrawerOpen(false);
        toggle.focus();
      }
    });
    // Navigating from the drawer always closes it.
    const nav = document.getElementById('pz-nav');
    if (nav) {
      nav.addEventListener('click', (e) => {
        if (e.target.closest?.('.pz-nav-item')) setDrawerOpen(false);
      });
    }
  }

  function renderShell(pageId, ctx) {
    const host = document.getElementById('portal-header');
    if (!host) return;

    const user = ctx.user || {};
    const { section, item } = findNavContext(pageId);
    const pageLabel = item ? item.label : pageId;
    const sectionLabel = section ? section.label : 'Portal';

    host.innerHTML =
      '<aside class="pz-sidebar" id="pz-sidebar" aria-label="Portal navigation">' +
      `<a class="pz-brand" href="${PREFIX}">` +
      '<img src="/assets/brand/01-logos/punicodex-wordmark-gold-solid.png" alt="PuniCodex" width="130" height="14">' +
      '<em>The Sanctum</em></a>' +
      `<nav class="pz-nav" id="pz-nav">${renderNavSections(pageId)}</nav>` +
      '<div class="pz-sidebar-foot">' +
      `<span class="pz-sidebar-user" title="${escapeHtml(user.email || '')}">${escapeHtml(user.displayName || user.email || '')}</span>` +
      `<span class="pz-sidebar-role">${escapeHtml(ctx.role || '')}</span>` +
      '<button type="button" class="btn btn-ghost btn-sm" id="pz-logout">Sign out</button>' +
      '</div>' +
      '</aside>' +
      '<div class="pz-topbar">' +
      '<button type="button" class="pz-drawer-toggle" id="pz-drawer-toggle" aria-label="Toggle navigation" aria-expanded="false" aria-controls="pz-sidebar">' +
      '<span></span><span></span><span></span></button>' +
      '<nav class="pz-breadcrumb" aria-label="Breadcrumb">' +
      '<span class="pz-breadcrumb-root">The Sanctum</span>' +
      '<span class="pz-breadcrumb-sep">/</span>' +
      `<span class="pz-breadcrumb-section">${escapeHtml(sectionLabel)}</span>` +
      '<span class="pz-breadcrumb-sep">/</span>' +
      `<span class="pz-breadcrumb-page">${escapeHtml(pageLabel)}</span>` +
      '</nav>' +
      '<div class="pz-topbar-right">' +
      '<span class="pz-topbar-time" id="pz-topbar-time"></span>' +
      '<button type="button" class="pz-topbar-refresh" id="pz-topbar-refresh">Refresh</button>' +
      '</div>' +
      '</div>' +
      '<div class="pz-backdrop" id="pz-backdrop"></div>';

    document.body.classList.add('pz-shell');
    wireDrawer();

    const refresh = document.getElementById('pz-topbar-refresh');
    if (refresh) {
      refresh.addEventListener('click', () => {
        window.location.reload();
      });
    }

    const logoutBtn = document.getElementById('pz-logout');
    if (logoutBtn) {
      logoutBtn.addEventListener('click', () => {
        logoutBtn.disabled = true;
        logout();
      });
    }
  }

  // Pages call this with their snapshot timestamp so the top bar can show the
  // data's age (e.g. the dashboard payload's generatedAt).
  function setSnapshotTime(value) {
    const el = document.getElementById('pz-topbar-time');
    if (!el) return;
    el.textContent = value ? `Snapshot ${fmtDateTime(value)}` : '';
  }

  // Auth guard: verifies the session, renders the shell, and resolves with
  // the /me context ({user, role, permissions}). Redirects to login on 401.
  async function initShell(pageId) {
    if (!getToken()) {
      redirectToLogin();
      return null;
    }
    let ctx;
    try {
      ctx = await me();
    } catch {
      return null;
    }
    shellContext = ctx;
    renderShell(pageId, ctx);
    return ctx;
  }

  async function logout() {
    try {
      await api('/api/admin/portal/logout/', { method: 'POST', body: {} });
    } catch {
      /* session may already be gone — sign out locally regardless */
    }
    clearToken();
    window.location.href = LOGIN_PATH;
  }

  // ── Toasts ─────────────────────────────────────────────────

  function toastRoot() {
    let root = document.getElementById('portal-toast-root');
    if (!root) {
      root = document.createElement('div');
      root.id = 'portal-toast-root';
      root.className = 'portal-toast-root';
      root.setAttribute('role', 'status');
      root.setAttribute('aria-live', 'polite');
      document.body.appendChild(root);
    }
    return root;
  }

  function toast(message, type) {
    const el = document.createElement('div');
    el.className = `portal-toast portal-toast--${type || 'info'}`;
    el.textContent = message;
    toastRoot().appendChild(el);
    setTimeout(() => {
      el.remove();
    }, 4500);
  }

  // ── Modal ──────────────────────────────────────────────────

  function closeModal() {
    const existing = document.querySelector('.portal-modal-overlay');
    if (existing) existing.remove();
  }

  function openModal(html, label) {
    closeModal();
    const overlay = document.createElement('div');
    overlay.className = 'portal-modal-overlay';
    overlay.innerHTML =
      `<div class="portal-modal" role="dialog" aria-modal="true" aria-label="${escapeHtml(label || 'Dialog')}">` +
      html +
      '</div>';
    overlay.addEventListener('click', (e) => {
      if (e.target === overlay) closeModal();
    });
    document.addEventListener('keydown', function onEsc(e) {
      if (e.key === 'Escape') {
        closeModal();
        document.removeEventListener('keydown', onEsc);
      }
    });
    document.body.appendChild(overlay);
    const focusable = overlay.querySelector('input, textarea, select, button');
    if (focusable) focusable.focus();
    return overlay;
  }

  // ── Sparklines ─────────────────────────────────────────────

  // Minimal line sparkline on a canvas element. Values are plain numbers;
  // fewer than two points renders nothing (honest empty state).
  function sparkline(canvas, values, options) {
    if (!canvas || typeof canvas.getContext !== 'function') return;
    const opts = options || {};
    const points = (Array.isArray(values) ? values : [])
      .map((value) => Number(value))
      .filter((value) => Number.isFinite(value));
    const ctx2d = canvas.getContext('2d');
    if (!ctx2d) return;
    const width = canvas.clientWidth || canvas.width || 120;
    const height = canvas.clientHeight || canvas.height || 36;
    const dpr = window.devicePixelRatio || 1;
    canvas.width = width * dpr;
    canvas.height = height * dpr;
    ctx2d.scale(dpr, dpr);
    ctx2d.clearRect(0, 0, width, height);
    if (points.length < 2) return;
    const max = Math.max(...points);
    const min = Math.min(...points);
    const span = max - min || 1;
    const stepX = width / (points.length - 1);
    ctx2d.strokeStyle = opts.stroke || '#d4af37';
    ctx2d.lineWidth = 1.5;
    ctx2d.beginPath();
    points.forEach((value, index) => {
      const x = index * stepX;
      const y = height - 2 - ((value - min) / span) * (height - 4);
      if (index === 0) {
        ctx2d.moveTo(x, y);
      } else {
        ctx2d.lineTo(x, y);
      }
    });
    ctx2d.stroke();
  }

  // ── Formatting helpers ─────────────────────────────────────

  function escapeHtml(value) {
    if (value === null || value === undefined) return '';
    return String(value)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  function fmtNumber(value) {
    const n = Number(value);
    if (!Number.isFinite(n)) return '0';
    return n.toLocaleString();
  }

  function fmtDateTime(value) {
    if (!value) return '—';
    const d = new Date(value);
    if (Number.isNaN(d.getTime())) return '—';
    return d.toLocaleString();
  }

  function fmtDate(value) {
    if (!value) return '—';
    const d = new Date(value);
    if (Number.isNaN(d.getTime())) return '—';
    return d.toLocaleDateString();
  }

  function fmtDollars(cents) {
    const n = Number(cents);
    if (!Number.isFinite(n)) return '$0.00';
    return `$${(n / 100).toFixed(2)}`;
  }

  function statusBadge(status) {
    const slug = String(status || 'unknown')
      .toLowerCase()
      .replace(/[^a-z0-9_]+/g, '_');
    return `<span class="badge badge--${slug}">${escapeHtml(String(status || 'unknown').replace(/_/g, ' '))}</span>`;
  }

  function copyToClipboard(text, label) {
    if (navigator.clipboard?.writeText) {
      navigator.clipboard.writeText(text).then(
        () => {
          toast(`${label || 'Value'} copied to clipboard`, 'success');
        },
        () => {
          toast('Copy failed — select and copy manually', 'error');
        }
      );
    } else {
      toast('Clipboard unavailable — select and copy manually', 'error');
    }
  }

  // ── Export ─────────────────────────────────────────────────

  window.Portal = {
    TOKEN_KEY,
    PREFIX,
    LOGIN_PATH,
    NAV_SECTIONS,
    NAV_ITEMS,
    getToken,
    setToken,
    clearToken,
    redirectToLogin,
    withTrailingSlash,
    api,
    me,
    can,
    initShell,
    logout,
    setSnapshotTime,
    toast,
    openModal,
    closeModal,
    sparkline,
    escapeHtml,
    fmtNumber,
    fmtDateTime,
    fmtDate,
    fmtDollars,
    statusBadge,
    badge: statusBadge,
    copyToClipboard,
  };
})();
