/**
 * PÚNYCODEX — Central Archetype Database
 * Handcrafted flagship temples only.
 * 74 handcrafted archetypes.
 */

const ARCHETYPES = [
    {
        id: "aigyptos",
        name: "Aígyptos",
        greek: "Αἴγυπτος",
        domain: "Personified Egypt, the Black Land",
        tagline: "From Egyptian Ḥwt-kꜣ-ptḥ (",
        tier: "tier-2",
        tierDetail: "tier-1",
        pantheon: "greek-location",
        folder: "aigyptos",
        domainUnicode: "aígyptos.com",
        domainPunycode: "xn--agyptos-7ya.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/aigyptos/assets/aigyptos_mascot.webp",
        mascotFallback: "/sites/aigyptos/assets/aigyptos_mascot.webp",
        logomarkPath: "/sites/aigyptos/assets/aigyptos_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "aphrodite",
        name: "Aphrodītē",
        greek: "Ἀφροδίτη",
        domain: "Goddess of Love & Beauty",
        tagline: "Born of Sea-Foam · The Irresistible",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "aphrodite",
        domainUnicode: "aphrodītē.com",
        domainPunycode: "xn--aphrodt-27a8s.com",
        domainAlt: ["aphrodítē.com"],
        colors: { primary: "#FF69B4", secondary: "#FFB6C1", glow: "rgba(255,105,180,0.3)" },
        mascotPath: "/sites/aphrodite/assets/aphrodite_mascot.webp",
        mascotFallback: "/sites/aphrodite/assets/aphrodite_mascot.webp",
        logomarkPath: "/sites/aphrodite/assets/aphrodite_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "ares",
        name: "Árēs",
        greek: "Ἄρης",
        domain: "God of War",
        tagline: "The Battle Fury · The Bloody Spear",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "ares",
        domainUnicode: "árēs.com",
        domainPunycode: "xn--rs-lia5r.com",
        colors: { primary: "#CD5C5C", secondary: "#8B0000", glow: "rgba(205,92,92,0.3)" },
        mascotPath: "/sites/ares/assets/ares_mascot.webp",
        mascotFallback: "/sites/ares/assets/ares_mascot.webp",
        logomarkPath: "/sites/ares/assets/ares_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "asia",
        name: "Asía",
        greek: "Ἀσία",
        domain: "Personified Continent of Asia",
        tagline: "The eastern continent",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "greek-location",
        folder: "asia",
        domainUnicode: "asía.com",
        domainPunycode: "xn--asa-sma.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/asia/assets/asia_mascot.webp",
        mascotFallback: "/sites/asia/assets/asia_mascot.webp",
        logomarkPath: "/sites/asia/assets/asia_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "athena",
        name: "Athēnā",
        greek: "Ἀθηνᾶ",
        domain: "Goddess of Wisdom + War",
        tagline: "The Grey-Eyed Strategist · Patron of Athens",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "athena",
        domainUnicode: "athénā.com",
        domainPunycode: "xn--athn-dpa9l.com",
        domainAlt: [],
        colors: { primary: "#4169E1", secondary: "#87CEEB", glow: "rgba(65,105,225,0.3)" },
        mascotPath: "/sites/athena/assets/athena_mascot.webp",
        mascotFallback: "/sites/athena/assets/athena_mascot.webp",
        logomarkPath: "/sites/athena/assets/athena_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "athenai",
        name: "Athēnai",
        greek: "Ἀθῆναι",
        domain: "City of Wisdom",
        tagline: "Of Athena",
        tier: "tier-2",
        tierDetail: "tier-1",
        pantheon: "greek-location",
        folder: "athenai",
        domainUnicode: "athēnai.com",
        domainPunycode: "xn--athnai-r3a.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        logomarkPath: "/sites/athenai/assets/athenai_logomark.webp",
        mascotPath: "/sites/athenai/assets/athenai_logomark.webp",
        mascotFallback: "/sites/athenai/assets/athenai_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "demeter",
        name: "Dēmētēr",
        greek: "Δημήτηρ",
        domain: "Goddess of the Harvest",
        tagline: "The Corn Mother · Bringer of Seasons",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "demeter",
        domainUnicode: "dēmētēr.com",
        domainPunycode: "xn--dmtr-bvabb.com",
        colors: { primary: "#228B22", secondary: "#DAA520", glow: "rgba(34,139,34,0.3)" },
        mascotPath: "/sites/demeter/assets/demeter_mascot.webp",
        mascotFallback: "/sites/demeter/assets/demeter_mascot.webp",
        logomarkPath: "/sites/demeter/assets/demeter_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "europe",
        name: "Eurṓpē",
        greek: "Εὐρώπη",
        domain: "Personified Continent of Europe",
        tagline: "Broad-faced (from εὐρύς + ὤψ)",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "greek-location",
        folder: "europe",
        domainUnicode: "eurṓpē.com",
        domainPunycode: "xn--eurp-eva0406b.com",
        domainAlt: ["eurōpē.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/europe/assets/europe_mascot.webp",
        mascotFallback: "/sites/europe/assets/europe_mascot.webp",
        logomarkPath: "/sites/europe/assets/europe_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "gaia",
        name: "Gaîa",
        greek: "Γαῖα",
        domain: "Earth, Mother of All",
        tagline: "Earth (from γαῖα)",
        tier: "tier-2",
        tierDetail: "tier-1",
        pantheon: "greek",
        folder: "gaia",
        domainUnicode: "gaîa.com",
        domainPunycode: "xn--gaa-wma.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        logomarkPath: "/sites/gaia/assets/gaia_logomark.webp",
        mascotPath: "/sites/gaia/assets/gaia_logomark.webp",
        mascotFallback: "/sites/gaia/assets/gaia_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "helios",
        name: "Hēlios",
        greek: "Ἥλιος",
        domain: "Sun, Sight, Oaths",
        tagline: "Sun (from ἕλος)",
        tier: "tier-2",
        tierDetail: "tier-1",
        pantheon: "greek",
        folder: "helios",
        domainUnicode: "hēlios.com",
        domainPunycode: "xn--hlios-iza.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/helios/assets/helios_mascot.webp",
        mascotFallback: "/sites/helios/assets/helios_mascot.webp",
        logomarkPath: "/sites/helios/assets/helios_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "hephaistos",
        name: "Hēphaistos",
        greek: "Ἥφαιστος",
        domain: "God of the Forge",
        tagline: "The Lame-Smith · Worker of Wonder",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "hephaistos",
        domainUnicode: "hēphaistos.com",
        domainPunycode: "xn--hphaistos-bhb.com",
        colors: { primary: "#FF4500", secondary: "#8B4513", glow: "rgba(255,69,0,0.3)" },
        mascotPath: "/sites/hephaistos/assets/hephaistos_mascot.webp",
        mascotFallback: "/sites/hephaistos/assets/hephaistos_mascot.webp",
        logomarkPath: "/sites/hephaistos/assets/hephaistos_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "hera",
        name: "Hēra",
        greek: "Ἥρα",
        domain: "Queen of the Gods",
        tagline: "The Golden-Throned · Guardian of Marriage",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "hera",
        domainUnicode: "hēra.com",
        domainPunycode: "xn--hra-3qa.com",
        colors: { primary: "#9B59B6", secondary: "#D4AF37", glow: "rgba(155,89,182,0.3)" },
        mascotPath: "/sites/hera/assets/hera_mascot.webp",
        mascotFallback: "/sites/hera/assets/hera_mascot.webp",
        logomarkPath: "/sites/hera/assets/hera_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "hermes",
        name: "Hermēs",
        greek: "Ἑρμῆς",
        domain: "Messenger of the Gods",
        tagline: "The Soul-Guide · Lord of Boundaries",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "hermes",
        domainUnicode: "hermēs.com",
        domainPunycode: "xn--herms-lza.com",
        domainAlt: ["hermês.com"],
        colors: { primary: "#32CD32", secondary: "#D4AF37", glow: "rgba(50,205,50,0.3)" },
        mascotPath: "/sites/hermes/assets/hermes_mascot.webp",
        mascotFallback: "/sites/hermes/assets/hermes_mascot.webp",
        logomarkPath: "/sites/hermes/assets/hermes_logomark.webp",
        built: true,
        darkPunchline: false,
        hasAdSite: true
    },
    {
        id: "hestia",
        name: "Hestía",
        greek: "Ἑστία",
        domain: "Goddess of the Hearth",
        tagline: "The Eternal Flame · Center of the Home",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "hestia",
        domainUnicode: "hestía.com",
        domainPunycode: "xn--hesta-2sa.com",
        colors: { primary: "#FF6B35", secondary: "#FFD700", glow: "rgba(255,107,53,0.3)" },
        mascotPath: "/sites/hestia/assets/hestia_mascot.webp",
        mascotFallback: "/sites/hestia/assets/hestia_mascot.webp",
        logomarkPath: "/sites/hestia/assets/hestia_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "kobe",
        name: "Kōbe",
        greek: "神戸",
        domain: "Port City, Hyōgo",
        tagline: "Door to the gods or support door",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "japanese",
        folder: "kobe",
        domainUnicode: "kōbe.com",
        domainPunycode: "xn--kbe-qxa.com",
        domainAlt: [],
        colors: { primary: "#FF6B6B", secondary: "#4ECDC4", glow: "rgba(255,107,107,0.3)" },
        logomarkPath: "/sites/kobe/assets/kobe_logomark.webp",
        mascotPath: "/sites/kobe/assets/kobe_logomark.webp",
        mascotFallback: "/sites/kobe/assets/kobe_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "kyoto",
        name: "Kyōto",
        greek: "京都",
        domain: "Imperial Capital, Kansai",
        tagline: "Capital city",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "japanese",
        folder: "kyoto",
        domainUnicode: "kyōto.com",
        domainPunycode: "xn--kyto-m3a.com",
        domainAlt: [],
        colors: { primary: "#FF6B6B", secondary: "#4ECDC4", glow: "rgba(255,107,107,0.3)" },
        logomarkPath: "/sites/kyoto/assets/kyoto_logomark.webp",
        mascotPath: "/sites/kyoto/assets/kyoto_logomark.webp",
        mascotFallback: "/sites/kyoto/assets/kyoto_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "libye",
        name: "Libyē",
        greek: "Λιβύη",
        domain: "Personified Continent of Africa",
        tagline: "The African continent (etymology uncertain)",
        tier: "tier-2",
        tierDetail: "tier-1",
        pantheon: "greek-location",
        folder: "libye",
        domainUnicode: "libyē.com",
        domainPunycode: "xn--liby-eva.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/libye/assets/libye_mascot.webp",
        mascotFallback: "/sites/libye/assets/libye_mascot.webp",
        logomarkPath: "/sites/libye/assets/libye_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "osaka",
        name: "Ōsaka",
        greek: "大阪",
        domain: "Merchant City, Kansai",
        tagline: "Large hill or slope",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "japanese",
        folder: "osaka",
        domainUnicode: "ōsaka.com",
        domainPunycode: "xn--saka-k3a.com",
        domainAlt: [],
        colors: { primary: "#FF6B6B", secondary: "#4ECDC4", glow: "rgba(255,107,107,0.3)" },
        logomarkPath: "/sites/osaka/assets/osaka_logomark.webp",
        mascotPath: "/sites/osaka/assets/osaka_logomark.webp",
        mascotFallback: "/sites/osaka/assets/osaka_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "persephone",
        name: "Persephonē",
        greek: "Περσεφόνη",
        domain: "Queen of the Underworld",
        tagline: "The Maiden · The Iron Queen",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "chthonic",
        folder: "persephone",
        domainUnicode: "persephonē.com",
        domainPunycode: "xn--persephon-jhb.com",
        colors: { primary: "#DC143C", secondary: "#8B008B", glow: "rgba(220,20,60,0.3)" },
        mascotPath: "/sites/persephone/assets/persephone_mascot.webp",
        mascotFallback: "/sites/persephone/assets/persephone_mascot.webp",
        logomarkPath: "/sites/persephone/assets/persephone_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: true
    },
    {
        id: "poseidon",
        name: "Poseidōn",
        greek: "Ποσειδῶν",
        domain: "Lord of the Sea",
        tagline: "The Earth-Shaker · Master of Waves",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "poseidon",
        domainUnicode: "poseidōn.com",
        domainPunycode: "xn--poseidn-bmb.com",
        domainAlt: ["poseidôn.com"],
        colors: { primary: "#1E90FF", secondary: "#00CED1", glow: "rgba(30,144,255,0.3)" },
        mascotPath: "/sites/poseidon/assets/poseidon_mascot.webp",
        mascotFallback: "/sites/poseidon/assets/poseidon_mascot.webp",
        logomarkPath: "/sites/poseidon/assets/poseidon_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "prometheus",
        name: "Promētheus",
        greek: "Προμηθεύς",
        domain: "The Fire-Bringer",
        tagline: "The Forethinker · Champion of Mortals",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "titan",
        folder: "prometheus",
        domainUnicode: "promētheus.com",
        domainPunycode: "xn--promtheus-ehb.com",
        colors: { primary: "#FF4500", secondary: "#4169E1", glow: "rgba(255,69,0,0.3)" },
        mascotPath: "/sites/prometheus/assets/prometheus_mascot.webp",
        mascotFallback: "/sites/prometheus/assets/prometheus_mascot.webp",
        logomarkPath: "/sites/prometheus/assets/prometheus_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "selene",
        name: "Selēnē",
        greek: "Σελήνη",
        domain: "Goddess of the Moon",
        tagline: "The Radiant · Driver of the Silver Chariot",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "selene",
        domainUnicode: "selēnē.com",
        domainPunycode: "xn--seln-dvab.com",
        colors: { primary: "#E6E6FA", secondary: "#C0C0C0", glow: "rgba(230,230,250,0.3)" },
        mascotPath: "/sites/selene/assets/selene_mascot.webp",
        mascotFallback: "/sites/selene/assets/selene_mascot.webp",
        logomarkPath: "/sites/selene/assets/selene_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "sparte",
        name: "Spártē",
        greek: "Σπάρτη",
        domain: "Warrior City",
        tagline: "Sown land (from σπείρω)",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "greek-location",
        folder: "sparte",
        domainUnicode: "spártē.com",
        domainPunycode: "xn--sprt-6na61a.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        logomarkPath: "/sites/sparte/assets/sparte_logomark.webp",
        mascotPath: "/sites/sparte/assets/sparte_logomark.webp",
        mascotFallback: "/sites/sparte/assets/sparte_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "zeus",
        name: "Zeús",
        greek: "Ζεύς",
        domain: "King of the Gods",
        tagline: "Lord of the Sky · Wielder of the Thunderbolt",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "zeus",
        domainUnicode: "zeús.com",
        domainPunycode: "xn--zes-9na.com",
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/zeus/assets/zeus_mascot.webp",
        mascotFallback: "/sites/zeus/assets/zeus_mascot.webp",
        logomarkPath: "/sites/zeus/assets/zeus_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "alfheimr",
        name: "Álfheimr",
        greek: "Álfheimr",
        domain: "Realm of the Light Elves",
        tagline: "Elf-home (from álfr + heimr)",
        tier: "tier-1",
        tierDetail: "tier-2",
        pantheon: "norse",
        folder: "alfheimr",
        domainUnicode: "álfheimr.com",
        domainPunycode: "xn--lfheimr-gwa.com",
        domainAlt: [],
        colors: { primary: "#4A90D9", secondary: "#8B0000", glow: "rgba(74,144,217,0.3)" },
        logomarkPath: "/sites/alfheimr/assets/alfheimr_logomark.webp",
        mascotPath: "/sites/alfheimr/assets/alfheimr_logomark.webp",
        mascotFallback: "/sites/alfheimr/assets/alfheimr_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "artemis",
        name: "Ártemis",
        greek: "Ἄρτεμις",
        domain: "Goddess of the Hunt",
        tagline: "The Virgin Huntress · Lady of Wild Beasts",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "artemis",
        domainUnicode: "ártemis.com",
        domainPunycode: "xn--rtemis-ota.com",
        colors: { primary: "#C0C0C0", secondary: "#228B22", glow: "rgba(192,192,192,0.3)" },
        mascotPath: "/sites/artemis/assets/artemis_mascot.webp",
        mascotFallback: "/sites/artemis/assets/artemis_mascot.webp",
        logomarkPath: "/sites/artemis/assets/artemis_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: true
    },
    {
        id: "atlas",
        name: "Átlas",
        greek: "Ἄτλας",
        domain: "The Titan of Endurance",
        tagline: "The World-Bearer · Guardian of the Western Edge",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "titan",
        folder: "atlas",
        domainUnicode: "átlas.com",
        domainPunycode: "xn--tlas-4na.com",
        colors: { primary: "#CD7F32", secondary: "#8B4513", glow: "rgba(205,127,50,0.3)" },
        mascotPath: "/sites/atlas/assets/atlas_mascot.webp",
        mascotFallback: "/sites/atlas/assets/atlas_mascot.webp",
        logomarkPath: "/sites/atlas/assets/atlas_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "chaos",
        name: "Cháos",
        greek: "Χάος",
        domain: "The First Void",
        tagline: "Gap, yawning void (from χάος)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "greek",
        folder: "chaos",
        domainUnicode: "cháos.com",
        domainPunycode: "xn--chos-6na.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/chaos/assets/chaos_mascot.png",
        mascotFallback: "/sites/chaos/assets/chaos_mascot.png",
        logomarkPath: "/sites/chaos/assets/chaos_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "delphoi",
        name: "Delphoí",
        greek: "Δελφοί",
        domain: "Oracle of Apollo",
        tagline: "Womb (from δελφύς)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "greek-location",
        folder: "delphoi",
        domainUnicode: "delphoí.com",
        domainPunycode: "xn--delpho-8va.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        logomarkPath: "/sites/delphoi/assets/delphoi_logomark.webp",
        mascotPath: "/sites/delphoi/assets/delphoi_logomark.webp",
        mascotFallback: "/sites/delphoi/assets/delphoi_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "dionysos",
        name: "Diónysos",
        greek: "Διόνυσος",
        domain: "God of Wine & Ecstasy",
        tagline: "The Liberator · Twice-Born",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "dionysos",
        domainUnicode: "diónysos.com",
        domainPunycode: "xn--dinysos-m0a.com",
        colors: { primary: "#800080", secondary: "#DAA520", glow: "rgba(128,0,128,0.3)" },
        mascotPath: "/sites/dionysos/assets/dionysos_mascot.png",
        mascotFallback: "/sites/dionysos/assets/dionysos_mascot.png",
        logomarkPath: "/sites/dionysos/assets/dionysos_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "helheimr",
        name: "Helheimr",
        greek: "Helheimr",
        domain: "Realm of the Dead",
        tier: "tier-1",
        tierDetail: "tier-2",
        pantheon: "norse",
        folder: "helheimr",
        domainUnicode: "helheimr.com",
        domainPunycode: "helheimr.com",
        domainAlt: [],
        colors: { primary: "#4A90D9", secondary: "#8B0000", glow: "rgba(74,144,217,0.3)" },
        logomarkPath: "/sites/helheimr/assets/helheimr_logomark.webp",
        mascotPath: "/sites/helheimr/assets/helheimr_logomark.webp",
        mascotFallback: "/sites/helheimr/assets/helheimr_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "jotunheimr",
        name: "Jötunheimr",
        greek: "Jötunheimr",
        domain: "Land of the Giants",
        tagline: "Giant-home (from jötunn + heimr)",
        tier: "tier-1",
        tierDetail: "tier-2",
        pantheon: "norse",
        folder: "jotunheimr",
        domainUnicode: "jötunheimr.com",
        domainPunycode: "xn--jtunheimr-07a.com",
        domainAlt: [],
        colors: { primary: "#4A90D9", secondary: "#8B0000", glow: "rgba(74,144,217,0.3)" },
        logomarkPath: "/sites/jotunheimr/assets/jotunheimr_logomark.webp",
        mascotPath: "/sites/jotunheimr/assets/jotunheimr_logomark.webp",
        mascotFallback: "/sites/jotunheimr/assets/jotunheimr_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "ker",
        name: "Kēr",
        greek: "Κήρ",
        domain: "Spirit of Violent Death",
        tagline: "The Dark Angel · Minister of Doom",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "chthonic",
        folder: "ker",
        domainUnicode: "kēr.com",
        domainPunycode: "xn--kr-wma.com",
        colors: { primary: "#4A4A4A", secondary: "#8B0000", glow: "rgba(74,74,74,0.3)" },
        mascotPath: "/sites/ker/assets/ker_mascot.webp",
        mascotFallback: "/sites/ker/assets/ker_mascot.webp",
        logomarkPath: "/sites/ker/assets/ker_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: true
    },
    {
        id: "medousa",
        name: "Médousa",
        greek: "Μέδουσα",
        domain: "The Gorgon",
        tagline: "The Petrifying · Guardian of the Threshold",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "other",
        folder: "medousa",
        domainUnicode: "médousa.com",
        domainPunycode: "xn--mdousa-bva.com",
        colors: { primary: "#2E8B57", secondary: "#556B2F", glow: "rgba(46,139,87,0.3)" },
        mascotPath: "/sites/medousa/assets/medusa_mascot.webp",
        mascotFallback: "/sites/medousa/assets/medusa_mascot.webp",
        logomarkPath: "/sites/medousa/assets/medusa_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "midgardr",
        name: "Miðgarðr",
        greek: "Miðgarðr",
        domain: "Middle Enclosure (Earth)",
        tagline: "Middle enclosure (from mið + garðr)",
        tier: "tier-1",
        tierDetail: "tier-2",
        pantheon: "norse",
        folder: "midgardr",
        domainUnicode: "miðgarðr.com",
        domainPunycode: "xn--migarr-qwad.com",
        domainAlt: [],
        colors: { primary: "#4A90D9", secondary: "#8B0000", glow: "rgba(74,144,217,0.3)" },
        logomarkPath: "/sites/midgardr/assets/midgardr_logomark.webp",
        mascotPath: "/sites/midgardr/assets/midgardr_logomark.webp",
        mascotFallback: "/sites/midgardr/assets/midgardr_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "muspellheimr",
        name: "Muspellheimr",
        greek: "Muspellheimr",
        domain: "World of Fire",
        tagline: "Muspel-home (world-ender)",
        tier: "tier-1",
        tierDetail: "tier-2",
        pantheon: "norse",
        folder: "muspellheimr",
        domainUnicode: "muspellheimr.com",
        domainPunycode: "muspellheimr.com",
        domainAlt: [],
        colors: { primary: "#4A90D9", secondary: "#8B0000", glow: "rgba(74,144,217,0.3)" },
        logomarkPath: "/sites/muspellheimr/assets/muspellheimr_logomark.webp",
        mascotPath: "/sites/muspellheimr/assets/muspellheimr_logomark.webp",
        mascotFallback: "/sites/muspellheimr/assets/muspellheimr_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
        {
        id: "maat",
        name: "Mꜣꜥt",
        greek: "—",
        domain: "Truth, Justice, Order",
        tagline: "Truth, straightness (Egyptian mꜣꜥt)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        folder: "maat",
        domainUnicode: "Mꜣꜥt.com",
        domainPunycode: "xn--mt-sq8hia.com",
        domainAlt: ["maat.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/maat/assets/maat_mascot.png",
        mascotFallback: "/sites/maat/assets/maat_mascot.png",
        logomarkPath: "/sites/maat/assets/maat_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "maa",
        name: "Mꜥ",
        greek: "Mꜥ",
        domain: "Vision, Perception, Understanding",
        tagline: "To see, to perceive, to understand. A core verb root, extremely common in texts",
        tier: "tier-1",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        folder: "maa",
        domainUnicode: "mꜥ.com",
        domainPunycode: "xn--m-2w3e.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/maa/assets/maa_mascot.webp",
        mascotFallback: "/sites/maa/assets/maa_mascot.webp",
        logomarkPath: "/sites/maa/assets/maa_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "odinn",
        name: "Óðinn",
        greek: "Óðinn",
        domain: "Allfather",
        tagline: "The Frenzied One · Lord of the Hanged",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "norse",
        folder: "odinn",
        domainUnicode: "óðinn.com",
        domainPunycode: "xn--inn-2mao.com",
        colors: { primary: "#5C5C5C", secondary: "#4169E1", glow: "rgba(92,92,92,0.3)" },
        mascotPath: "/sites/odinn/assets/odinn_mascot.webp",
        mascotFallback: "/sites/odinn/assets/odinn_mascot.webp",
        logomarkPath: "/sites/odinn/assets/odinn_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: true
    },
    {
        id: "olympos",
        name: "Ólympos",
        greek: "Ὄλυμπος",
        domain: "Mountain of the Gods",
        tagline: "Bright, shining mountain",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "greek-location",
        folder: "olympos",
        domainUnicode: "ólympos.com",
        domainPunycode: "xn--lympos-9wa.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        logomarkPath: "/sites/olympos/assets/olympos_logomark.webp",
        mascotPath: "/sites/olympos/assets/olympos_logomark.webp",
        mascotFallback: "/sites/olympos/assets/olympos_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "pontos",
        name: "Póntos",
        greek: "Πόντος",
        domain: "The Primordial Sea",
        tagline: "Sea (from πόντος)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "greek",
        folder: "pontos",
        domainUnicode: "póntos.com",
        domainPunycode: "xn--pntos-0ta.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        logomarkPath: "/sites/pontos/assets/pontos_logomark.webp",
        mascotPath: "/sites/pontos/assets/pontos_logomark.webp",
        mascotFallback: "/sites/pontos/assets/pontos_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "ragnarok",
        name: "Ragnarǫk",
        greek: "Ragnarǫk",
        domain: "Doom of the Gods",
        tagline: "Twilight of the gods (from ragna + rǫk)",
        tier: "tier-1",
        tierDetail: "tier-2",
        pantheon: "norse",
        folder: "ragnarok",
        domainUnicode: "ragnarǫk.com",
        domainPunycode: "xn--ragnark-fnc.com",
        domainAlt: [],
        colors: { primary: "#4A90D9", secondary: "#8B0000", glow: "rgba(74,144,217,0.3)" },
        logomarkPath: "/sites/ragnarok/assets/ragnarok_logomark.webp",
        mascotPath: "/sites/ragnarok/assets/ragnarok_logomark.webp",
        mascotFallback: "/sites/ragnarok/assets/ragnarok_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "ra",
        name: "Rꜥ",
        greek: "Rꜥ",
        domain: "Sun, Creation, Kingship",
        tagline: "Sun (from Egyptian rꜥ)",
        tier: "tier-1",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        hasAdSite: true,
        folder: "ra",
        domainUnicode: "rꜥ.com",
        domainPunycode: "xn--r-2w3e.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/ra/assets/ra_mascot.webp",
        mascotFallback: "/sites/ra/assets/ra_mascot.webp",
        logomarkPath: "/sites/ra/assets/ra_logomark.webp",
        built: true,
        darkPunchline: false
    },
    {
        id: "sia",
        name: "Sꜥ",
        greek: "Sꜥ",
        domain: "Divine Archetype",
        tier: "tier-1",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        folder: "sia",
        domainUnicode: "sꜥ.com",
        domainPunycode: "xn--s-2w3e.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/sia/assets/sia_mascot.webp",
        mascotFallback: "/sites/sia/assets/sia_mascot.webp",
        logomarkPath: "/sites/sia/assets/sia_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "shiva",
        name: "Śiva",
        greek: "शिव",
        domain: "Destruction, Transformation, Dance",
        tagline: "Auspicious, kind (from शिव)",
        tier: "tier-1",
        tierDetail: "tier-2",
        pantheon: "sanskrit",
        folder: "shiva",
        domainUnicode: "śiva.com",
        domainPunycode: "xn--iva-bza.com",
        domainAlt: [],
        colors: { primary: "#FF9933", secondary: "#138808", glow: "rgba(255,153,51,0.3)" },
        mascotPath: "/sites/shiva/assets/siva_mascot.webp",
        mascotFallback: "/sites/shiva/assets/siva_mascot.webp",
        logomarkPath: "/sites/shiva/assets/siva_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "shu",
        name: "Šw",
        greek: "Šw",
        domain: "Air, Wind, Lions",
        tagline: "Emptiness, he who rises up",
        tier: "tier-1",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        folder: "shu",
        domainUnicode: "šw.com",
        domainPunycode: "xn--w-4ma.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/shu/assets/shu_mascot.webp",
        mascotFallback: "/sites/shu/assets/shu_mascot.webp",
        logomarkPath: "/sites/shu/assets/shu_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "tartaros",
        name: "Tártaros",
        greek: "Τάρταρος",
        domain: "The Primordial Abyss",
        tagline: "Deep place (from τάρταρος)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "greek",
        folder: "tartaros",
        domainUnicode: "tártaros.com",
        domainPunycode: "xn--trtaros-hwa.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        logomarkPath: "/sites/tartaros/assets/tartaros_logomark.png",
        mascotPath: "/sites/tartaros/assets/tartaros_mascot.png",
        mascotFallback: "/sites/tartaros/assets/tartaros_mascot.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "thor",
        name: "Þórr",
        greek: "Þórr",
        domain: "Thunder, Storms, Oak",
        tagline: "Thunder (from *þunraz)",
        tier: "tier-1",
        tierDetail: "tier-2",
        pantheon: "norse",
        folder: "thor",
        domainUnicode: "þórr.com",
        domainPunycode: "xn--rr-4ja7b.com",
        domainAlt: [],
        colors: { primary: "#4A90D9", secondary: "#8B0000", glow: "rgba(74,144,217,0.3)" },
        mascotPath: "/sites/thor/assets/thor_mascot.webp",
        mascotFallback: "/sites/thor/assets/thor_mascot.webp",
        logomarkPath: "/sites/thor/assets/thor_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "ab",
        name: "ꜣb",
        greek: "ꜣb",
        domain: "Heart, Conscience, Emotion",
        tagline: "Heart. Central to the weighing of the heart ritual. Represents conscience, emotion, moral worth",
        tier: "tier-1",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        folder: "ab",
        domainUnicode: "ꜣb.com",
        domainPunycode: "xn--b-xw3e.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/ab/assets/ab_mascot.webp",
        mascotFallback: "/sites/ab/assets/ab_mascot.webp",
        logomarkPath: "/sites/ab/assets/ab_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "akh",
        name: "ꜣḫ",
        greek: "ꜣḫ",
        domain: "Soul, Afterlife, Transfiguration",
        tagline: "Akh, transfigured spirit; effective, luminous being. One of the highest forms of the soul",
        tier: "tier-1",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        folder: "akh",
        domainUnicode: "ꜣḫ.com",
        domainPunycode: "xn--9gg9559c.com",
        domainAlt: [],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/akh/assets/akh_mascot.webp",
        mascotFallback: "/sites/akh/assets/akh_mascot.webp",
        logomarkPath: "/sites/akh/assets/akh_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "apollon",
        name: "Apóllōn",
        greek: "Ἀπόλλων",
        domain: "Light, Music, Prophecy",
        tagline: "The Shining One · Lord of the Lyre",
        tier: "tier-1",
        tierDetail: "dual-tier",
        pantheon: "olympian",
        folder: "apollon",
        domainUnicode: "apóllōn.com",
        domainPunycode: "xn--aplln-1ta64d.com",
        domainAlt: ["apollōn.com"],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/apollon/assets/apollon_mascot.webp",
        mascotFallback: "/sites/apollon/assets/apollon_mascot.webp",
        logomarkPath: "/sites/apollon/assets/apollon_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "hades",
        name: "Hádēs",
        greek: "Ἅιδης",
        domain: "Underworld, Wealth",
        tagline: "The Unseen One · Lord of the Dead",
        tier: "tier-1",
        tierDetail: "dual-tier",
        pantheon: "olympian",
        folder: "hades",
        domainUnicode: "hádēs.com",
        domainPunycode: "xn--hds-ela5w.com",
        domainAlt: [],
        colors: { primary: "#8B0000", secondary: "#D4AF37", glow: "rgba(139,0,0,0.3)" },
        mascotPath: "/sites/hades/assets/hades_mascot.webp",
        mascotFallback: "/sites/hades/assets/hades_mascot.webp",
        logomarkPath: "/sites/hades/assets/hades_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: true
    },
    {
        id: "hekate",
        name: "Hekátē",
        greek: "Ἑκάτη",
        domain: "Goddess of Magic & Crossroads",
        tagline: "The Torch-Bearer · Queen of Ghosts",
        tier: "tier-1",
        tierDetail: "dual-tier",
        pantheon: "chthonic",
        folder: "hekate",
        domainUnicode: "hekátē.com",
        domainPunycode: "xn--hekt-7na51a.com",
        domainAlt: ["hekatē.com"],
        colors: { primary: "#FF6B35", secondary: "#8B00FF", glow: "rgba(255,107,53,0.3)" },
        mascotPath: "/sites/hekate/assets/hekate_mascot.webp",
        mascotFallback: "/sites/hekate/assets/hekate_mascot.webp",
        logomarkPath: "/sites/hekate/assets/hekate_logomark.webp",
        built: true,
        hasAdSite: true,
        darkPunchline: true
    },
    {
        id: "nike",
        name: "Níkē",
        greek: "Νίκη",
        domain: "Goddess of Victory",
        tagline: "The Winged Herald · Bringer of Triumph",
        tier: "tier-1",
        tierDetail: "dual-tier",
        pantheon: "olympian",
        folder: "nike",
        domainUnicode: "níkē.com",
        domainPunycode: "xn--nk-nja7m.com",
        domainAlt: ["nikē.com", "níkê.com"],
        colors: { primary: "#D4AF37", secondary: "#FFFFFF", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/nike/assets/nike_mascot.webp",
        mascotFallback: "/sites/nike/assets/nike_mascot.webp",
        logomarkPath: "/sites/nike/assets/nike_logomark.webp",
        built: true,
        darkPunchline: false,
        hasAdSite: true
    },
    {
        id: "el",
        name: "Ēl",
        greek: "Ἠλ",
        domain: "Supreme God, Father of Gods",
        tagline: "The Ancient High God · Father of the Divine Assembly",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "canaanite",
        folder: "el",
        domainUnicode: "ēl.com",
        domainPunycode: "xn--l-oia.com",
        domainAlt: [],
        colors: { primary: "#8B4513", secondary: "#D4AF37", glow: "rgba(139,69,19,0.3)" },
        mascotPath: "/sites/el/assets/el_mascot.png",
        mascotFallback: "/sites/el/assets/el_mascot.png",
        logomarkPath: "/sites/el/assets/el_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "baal",
        name: "Baꜥal",
        greek: "Βαάλ",
        domain: "Storm God, Lord of the Heavens",
        tagline: "Rider of the Clouds · Lord of the Storm",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "canaanite",
        folder: "baal",
        domainUnicode: "baꜥal.com",
        domainPunycode: "xn--baal-re8o.com",
        domainAlt: ["baʿal.com"],
        colors: { primary: "#8B4513", secondary: "#D4AF37", glow: "rgba(139,69,19,0.3)" },
        mascotPath: "/sites/baal/assets/baal_mascot.png",
        mascotFallback: "/sites/baal/assets/baal_mascot.png",
        logomarkPath: "/sites/baal/assets/baal_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "anat",
        name: "ꜥAnat",
        greek: "Ἀνάθ",
        domain: "Goddess of War and the Hunt",
        tagline: "The Virgin Warrior · Sister of the Storm",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "canaanite",
        folder: "anat",
        domainUnicode: "ꜥanat.com",
        domainPunycode: "xn--anat-pe8o.com",
        domainAlt: ["ʿanat.com"],
        colors: { primary: "#8B4513", secondary: "#D4AF37", glow: "rgba(139,69,19,0.3)" },
        mascotPath: "/sites/anat/assets/anat_mascot.png",
        mascotFallback: "/sites/anat/assets/anat_mascot.png",
        logomarkPath: "/sites/anat/assets/anat_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "asherah",
        name: "ꜥAsherah",
        greek: "Ἀσερά",
        domain: "Mother Goddess, Lady of the Sea",
        tagline: "She Who Treads the Sea · Mother of the Gods",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "canaanite",
        folder: "asherah",
        domainUnicode: "ꜥasherah.com",
        domainPunycode: "xn--asherah-dv2z.com",
        domainAlt: ["ʿasherah.com"],
        colors: { primary: "#8B4513", secondary: "#D4AF37", glow: "rgba(139,69,19,0.3)" },
        mascotPath: "/sites/asherah/assets/asherah_mascot.png",
        mascotFallback: "/sites/asherah/assets/asherah_mascot.png",
        logomarkPath: "/sites/asherah/assets/asherah_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "kronos",
        name: "Krónos",
        greek: "Κρόνος",
        domain: "Time, Harvest, Titans",
        tagline: "The Crooked-Sickle King · Devourer and Father of Gods",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "greek",
        folder: "kronos",
        domainUnicode: "krónos.com",
        domainPunycode: "xn--krnos-1ta.com",
        domainAlt: ["kronos.com"],
        colors: { primary: "#C0C0C0", secondary: "#4169E1", glow: "rgba(192,192,192,0.3)" },
        mascotPath: "/sites/kronos/assets/kronos_mascot.png",
        mascotFallback: "/sites/kronos/assets/kronos_mascot.png",
        logomarkPath: "/sites/kronos/assets/kronos_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: true
    },
    {
        id: "enlil",
        name: "Enlīl",
        greek: "—",
        domain: "Wind, Air, Storms, Kingship",
        tagline: "Lord of the Wind · King of Heaven and Earth",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "mesopotamian",
        folder: "enlil",
        domainUnicode: "enlīl.com",
        domainPunycode: "xn--enll-sya.com",
        domainAlt: ["enlil.com"],
        colors: { primary: "#CD7F32", secondary: "#C2B280", glow: "rgba(205,127,50,0.3)" },
        mascotPath: "/sites/enlil/assets/enlil_mascot.png",
        mascotFallback: "/sites/enlil/assets/enlil_mascot.png",
        logomarkPath: "/sites/enlil/assets/enlil_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: true
    },
    {
        id: "typhon",
        name: "Typhōn",
        greek: "Τυφῶν",
        domain: "Monster, Father of Monsters, Storms",
        tagline: "The Smoke-and-Fire Titan · Father of Monstrous Things",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "greek",
        folder: "typhon",
        domainUnicode: "typhōn.com",
        domainPunycode: "xn--typhn-j9a.com",
        domainAlt: ["typhon.com"],
        colors: { primary: "#8B0000", secondary: "#FF4500", glow: "rgba(139,0,0,0.3)" },
        mascotPath: "/sites/typhon/assets/typhon_mascot.png",
        mascotFallback: "/sites/typhon/assets/typhon_mascot.png",
        logomarkPath: "/sites/typhon/assets/typhon_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: true
    },
    {
        id: "ishtar",
        name: "Ištar",
        greek: "—",
        domain: "Love, War, Fertility, Venus",
        tagline: "Lady of Heaven · Morning Star and Warrior Queen",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "mesopotamian",
        folder: "ishtar",
        domainUnicode: "ištar.com",
        domainPunycode: "xn--itar-g6a.com",
        domainAlt: ["ishtar.com"],
        colors: { primary: "#CD7F32", secondary: "#D4AF37", glow: "rgba(205,127,50,0.3)" },
        mascotPath: "/sites/ishtar/assets/ishtar_mascot.png",
        mascotFallback: "/sites/ishtar/assets/ishtar_mascot.png",
        logomarkPath: "/sites/ishtar/assets/ishtar_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: true
    },
    {
        id: "aether",
        name: "Aithḗr",
        greek: "Αἰθήρ",
        domain: "Upper Air, Light",
        tagline: "Bright upper air",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "greek",
        folder: "aether",
        domainUnicode: "Aithḗr.com",
        domainPunycode: "xn--aithr-yd1b.com",
        domainAlt: ["aether.com"],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/aether/assets/aether_mascot.png",
        mascotFallback: "/sites/aether/assets/aether_mascot.png",
        logomarkPath: "/sites/aether/assets/aether_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "astart",
        name: "Aštart",
        greek: "—",
        domain: "Love, War, Fertility, Venus",
        tagline: "She of the womb. The planet Venus as deity. Queen of heaven.",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "phoenician",
        folder: "astart",
        domainUnicode: "Aštart.com",
        domainPunycode: "xn--atart-vdb.com",
        domainAlt: ["astart.com"],
        colors: { primary: "#E0115F", secondary: "#FFD700", glow: "rgba(224,17,95,0.3)" },
        mascotPath: "/sites/astart/assets/astart_mascot.png",
        mascotFallback: "/sites/astart/assets/astart_mascot.png",
        logomarkPath: "/sites/astart/assets/astart_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "ba",
        name: "Bꜣ",
        greek: "—",
        domain: "Soul, Personality, Manifestation",
        tagline: "The soul, personality, or manifestation of a person. One of the five components of the Egyptian soul.",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        folder: "ba",
        domainUnicode: "Bꜣ.com",
        domainPunycode: "xn--b-yw3e.com",
        domainAlt: ["ba.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/ba/assets/ba_mascot.png",
        mascotFallback: "/sites/ba/assets/ba_mascot.png",
        logomarkPath: "/sites/ba/assets/ba_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "enki",
        name: "Enki",
        greek: "—",
        domain: "Water, Wisdom, Crafts, Creation",
        tagline: "Lord of the Earth (Sumerian Enki)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "mesopotamian",
        folder: "enki",
        domainUnicode: "Enki.com",
        domainPunycode: "enki.com",
        domainAlt: ["enki.com"],
        colors: { primary: "#CD7F32", secondary: "#C2B280", glow: "rgba(205,127,50,0.3)" },
        mascotPath: "/sites/enki/assets/enki_mascot.png",
        mascotFallback: "/sites/enki/assets/enki_mascot.png",
        logomarkPath: "/sites/enki/assets/enki_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "eros",
        name: "Erōs",
        greek: "Ἔρως",
        domain: "Love, Desire, Attraction",
        tagline: "Love, desire (from ἔραμαι)",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "greek",
        folder: "eros",
        domainUnicode: "Erōs.com",
        domainPunycode: "xn--ers-rxa.com",
        domainAlt: ["eros.com"],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/eros/assets/eros_mascot.png",
        mascotFallback: "/sites/eros/assets/eros_mascot.png",
        logomarkPath: "/sites/eros/assets/eros_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "ganesha",
        name: "Gaṇeśa",
        greek: "—",
        domain: "Wisdom, Beginnings, Obstacle-Removal",
        tagline: "Lord of the gaṇas (from गणेश)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "sanskrit",
        folder: "ganesha",
        domainUnicode: "Gaṇeśa.com",
        domainPunycode: "xn--gaea-n5a6355b.com",
        domainAlt: ["ganesha.com"],
        colors: { primary: "#FF9933", secondary: "#8B0000", glow: "rgba(255,153,51,0.3)" },
        mascotPath: "/sites/ganesha/assets/ganesha_mascot.png",
        mascotFallback: "/sites/ganesha/assets/ganesha_mascot.png",
        logomarkPath: "/sites/ganesha/assets/ganesha_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "heka",
        name: "Ḥkꜣ",
        greek: "—",
        domain: "Magic, Medicine",
        tagline: "Magic, first work",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        folder: "heka",
        domainUnicode: "Ḥkꜣ.com",
        domainPunycode: "xn--k-xnm1886d.com",
        domainAlt: ["heka.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/heka/assets/heka_mascot.png",
        mascotFallback: "/sites/heka/assets/heka_mascot.png",
        logomarkPath: "/sites/heka/assets/heka_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "horus",
        name: "Ḥr",
        greek: "—",
        domain: "Sky, Kingship, Falcon",
        tagline: "The Distant One (Egyptian ḥr)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        folder: "horus",
        domainUnicode: "Ḥr.com",
        domainPunycode: "xn--r-xnm.com",
        domainAlt: ["horus.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/horus/assets/horus_mascot.png",
        mascotFallback: "/sites/horus/assets/horus_mascot.png",
        logomarkPath: "/sites/horus/assets/horus_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "kali",
        name: "Kālī",
        greek: "—",
        domain: "Time, Destruction, Empowerment",
        tagline: "The black one, time",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "sanskrit",
        folder: "kali",
        domainUnicode: "Kālī.com",
        domainPunycode: "xn--kl-dla3o.com",
        domainAlt: ["kali.com"],
        colors: { primary: "#FF9933", secondary: "#8B0000", glow: "rgba(255,153,51,0.3)" },
        mascotPath: "/sites/kali/assets/kali_mascot.png",
        mascotFallback: "/sites/kali/assets/kali_mascot.png",
        logomarkPath: "/sites/kali/assets/kali_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "prajapati",
        name: "Prajāpati",
        greek: "—",
        domain: "Lord of Creatures",
        tagline: "Lord of offspring",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "sanskrit",
        folder: "prajapati",
        domainUnicode: "Prajāpati.com",
        domainPunycode: "xn--prajpati-k7a.com",
        domainAlt: ["prajapati.com"],
        colors: { primary: "#FF9933", secondary: "#8B0000", glow: "rgba(255,153,51,0.3)" },
        mascotPath: "/sites/prajapati/assets/prajapati_mascot.png",
        mascotFallback: "/sites/prajapati/assets/prajapati_mascot.png",
        logomarkPath: "/sites/prajapati/assets/prajapati_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "rta",
        name: "Ṛta",
        greek: "—",
        domain: "Cosmic Order, Truth, Law",
        tagline: "Truth, cosmic order, natural law. The Vedic principle of righteousness and universal harmony.",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "sanskrit",
        folder: "rta",
        domainUnicode: "Ṛta.com",
        domainPunycode: "xn--ta-ezs.com",
        domainAlt: ["rta.com"],
        colors: { primary: "#FF9933", secondary: "#8B0000", glow: "rgba(255,153,51,0.3)" },
        mascotPath: "/sites/rta/assets/rta_mascot.png",
        mascotFallback: "/sites/rta/assets/rta_mascot.png",
        logomarkPath: "/sites/rta/assets/rta_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
    {
        id: "vishnu",
        name: "Viṣṇu",
        greek: "—",
        domain: "Preservation, Protection, Universe",
        tagline: "All-pervading (from विष्णु)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "sanskrit",
        folder: "vishnu",
        domainUnicode: "Viṣṇu.com",
        domainPunycode: "xn--viu-j5ytg.com",
        domainAlt: ["vishnu.com"],
        colors: { primary: "#FF9933", secondary: "#8B0000", glow: "rgba(255,153,51,0.3)" },
        mascotPath: "/sites/vishnu/assets/vishnu_mascot.png",
        mascotFallback: "/sites/vishnu/assets/vishnu_mascot.png",
        logomarkPath: "/sites/vishnu/assets/vishnu_logomark.png",
        built: true,
        hasAdSite: true,
        darkPunchline: false
    },
];
