/**
 * PÚNYCODEX — Central Archetype Database
 * Handcrafted flagship temples only.
 * 54 handcrafted archetypes.
 */

const ARCHETYPES = [
    {
        id: "aigyptos",
        name: "Aígyptos",
        greek: "Αἴγυπτος",
        domain: "Personified Egypt, the Black Land",
        tagline: "From Egyptian Ḥwt-kꜣ-ptḥ (",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "greek-location",
        folder: "aigyptos",
        domainUnicode: "Aígyptos.com",
        domainPunycode: "xn--Agyptos-7ya.com",
        domainAlt: ["aigyptos.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/aigyptos/assets/aigyptos_mascot.png",
        mascotFallback: "/sites/aigyptos/assets/aigyptos_mascot.png",
        logomarkPath: "/sites/aigyptos/assets/aigyptos_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "aphrodite",
        name: "Aphrodītē",
        greek: "Ἀφροδίτη",
        domain: "Goddess of Love & Beauty",
        tagline: "Born of Sea-Foam · The Irresistible",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "aphrodite",
        domainUnicode: "aphrodītē.com",
        domainPunycode: "xn--aphrodt-27a8s.com",
        colors: { primary: "#FF69B4", secondary: "#FFB6C1", glow: "rgba(255,105,180,0.3)" },
        mascotPath: "/sites/aphrodite/assets/aphrodite_mascot.png",
        mascotFallback: "/sites/aphrodite/assets/aphrodite_mascot.png",
        logomarkPath: "/sites/aphrodite/assets/aphrodite_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "ares",
        name: "Árēs",
        greek: "Ἄρης",
        domain: "God of War",
        tagline: "The Battle Fury · The Bloody Spear",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "ares",
        domainUnicode: "árēs.com",
        domainPunycode: "xn--rs-lia5r.com",
        colors: { primary: "#CD5C5C", secondary: "#8B0000", glow: "rgba(205,92,92,0.3)" },
        mascotPath: "/sites/ares/assets/ares_mascot.png",
        mascotFallback: "/sites/ares/assets/ares_mascot.png",
        logomarkPath: "/sites/ares/assets/ares_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "asia",
        name: "Asíā",
        greek: "Ἀσία",
        domain: "Personified Continent of Asia",
        tagline: "The eastern continent (possibly from Assuwa)",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "greek-location",
        folder: "asia",
        domainUnicode: "Asíā.com",
        domainPunycode: "xn--As-oja4f.com",
        domainAlt: ["asia.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/asia/assets/asia_mascot.png",
        mascotFallback: "/sites/asia/assets/asia_mascot.png",
        logomarkPath: "/sites/asia/assets/asia_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "athena",
        name: "Athēnā",
        greek: "Ἀθηνᾶ",
        domain: "Goddess of Wisdom & War",
        tagline: "The Grey-Eyed Strategist · Patron of Athens",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "athena",
        domainUnicode: "athēnā.com",
        domainPunycode: "xn--athn-tsa0i.com",
        colors: { primary: "#4169E1", secondary: "#87CEEB", glow: "rgba(65,105,225,0.3)" },
        mascotPath: "/sites/athena/assets/athena_mascot.png",
        mascotFallback: "/sites/athena/assets/athena_mascot.png",
        logomarkPath: "/sites/athena/assets/athena_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "athenai",
        name: "Athēnai",
        greek: "Ἀθῆναι",
        domain: "City of Wisdom",
        tagline: "Of Athena",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "greek-location",
        folder: "athenai",
        domainUnicode: "Athēnai.com",
        domainPunycode: "xn--Athnai-r3a.com",
        domainAlt: ["athenai.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        logomarkPath: "/sites/athenai/assets/athenai_logomark.png",
        mascotPath: "/sites/athenai/assets/athenai_logomark.png",
        mascotFallback: "/sites/athenai/assets/athenai_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "demeter",
        name: "Dēmētēr",
        greek: "Δημήτηρ",
        domain: "Goddess of the Harvest",
        tagline: "The Corn Mother · Bringer of Seasons",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "demeter",
        domainUnicode: "dēmētēr.com",
        domainPunycode: "xn--dmtr-bvabb.com",
        colors: { primary: "#228B22", secondary: "#DAA520", glow: "rgba(34,139,34,0.3)" },
        mascotPath: "/sites/demeter/assets/demeter_mascot.png",
        mascotFallback: "/sites/demeter/assets/demeter_mascot.png",
        logomarkPath: "/sites/demeter/assets/demeter_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "europe",
        name: "Eurṓpē",
        greek: "Εὐρώπη",
        domain: "Personified Continent of Europe",
        tagline: "Broad-faced (from εὐρύς + ὤψ)",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "greek-location",
        folder: "europe",
        domainUnicode: "Eurṓpē.com",
        domainPunycode: "xn--Eurp-eva0406b.com",
        domainAlt: ["europe.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/europe/assets/europe_mascot.png",
        mascotFallback: "/sites/europe/assets/europe_mascot.png",
        logomarkPath: "/sites/europe/assets/europe_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "gaia",
        name: "Gaîa",
        greek: "Γαῖα",
        domain: "Earth, Mother of All",
        tagline: "Earth (from γαῖα)",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "greek",
        folder: "gaia",
        domainUnicode: "Gaîa.com",
        domainPunycode: "xn--Gaa-wma.com",
        domainAlt: ["gaia.com"],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        logomarkPath: "/sites/gaia/assets/gaia_logomark.png",
        mascotPath: "/sites/gaia/assets/gaia_logomark.png",
        mascotFallback: "/sites/gaia/assets/gaia_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "helios",
        name: "Hēlios",
        greek: "Ἥλιος",
        domain: "Sun, Sight, Oaths",
        tagline: "Sun (from ἕλος)",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "greek",
        folder: "helios",
        domainUnicode: "Hēlios.com",
        domainPunycode: "xn--Hlios-iza.com",
        domainAlt: ["helios.com"],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/helios/assets/helios_mascot.png",
        mascotFallback: "/sites/helios/assets/helios_mascot.png",
        logomarkPath: "/sites/helios/assets/helios_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "hephaistos",
        name: "Hēphaistos",
        greek: "Ἥφαιστος",
        domain: "God of the Forge",
        tagline: "The Lame-Smith · Worker of Wonder",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "hephaistos",
        domainUnicode: "hēphaistos.com",
        domainPunycode: "xn--hphaistos-bhb.com",
        colors: { primary: "#FF4500", secondary: "#8B4513", glow: "rgba(255,69,0,0.3)" },
        mascotPath: "/sites/hephaistos/assets/hephaistos_mascot.png",
        mascotFallback: "/sites/hephaistos/assets/hephaistos_mascot.png",
        logomarkPath: "/sites/hephaistos/assets/hephaistos_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "hera",
        name: "Hēra",
        greek: "Ἥρα",
        domain: "Queen of the Gods",
        tagline: "The Golden-Throned · Guardian of Marriage",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "hera",
        domainUnicode: "hēra.com",
        domainPunycode: "xn--hra-3qa.com",
        colors: { primary: "#9B59B6", secondary: "#D4AF37", glow: "rgba(155,89,182,0.3)" },
        mascotPath: "/sites/hera/assets/hera_mascot.png",
        mascotFallback: "/sites/hera/assets/hera_mascot.png",
        logomarkPath: "/sites/hera/assets/hera_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "hermes",
        name: "Hermēs",
        greek: "Ἑρμῆς",
        domain: "Messenger of the Gods",
        tagline: "The Soul-Guide · Lord of Boundaries",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "hermes",
        domainUnicode: "hermēs.com",
        domainPunycode: "xn--herms-lza.com",
        colors: { primary: "#32CD32", secondary: "#D4AF37", glow: "rgba(50,205,50,0.3)" },
        mascotPath: "/sites/hermes/assets/hermes_mascot.png",
        mascotFallback: "/sites/hermes/assets/hermes_mascot.png",
        logomarkPath: "/sites/hermes/assets/hermes_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "hestia",
        name: "Hestiā",
        greek: "Ἑστία",
        domain: "Goddess of the Hearth",
        tagline: "The Eternal Flame · Center of the Home",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "hestia",
        domainUnicode: "hestiā.com",
        domainPunycode: "xn--hesti-jwa.com",
        colors: { primary: "#FF6B35", secondary: "#FFD700", glow: "rgba(255,107,53,0.3)" },
        mascotPath: "/sites/hestia/assets/hestia_mascot.png",
        mascotFallback: "/sites/hestia/assets/hestia_mascot.png",
        logomarkPath: "/sites/hestia/assets/hestia_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "kobe",
        name: "Kōbe",
        greek: "神戸",
        domain: "Port City, Hyōgo",
        tagline: "Door to the gods or support door",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "japanese",
        folder: "kobe",
        domainUnicode: "Kōbe.com",
        domainPunycode: "xn--Kbe-qxa.com",
        domainAlt: ["kobe.com"],
        colors: { primary: "#FF6B6B", secondary: "#4ECDC4", glow: "rgba(255,107,107,0.3)" },
        logomarkPath: "/sites/kobe/assets/kobe_logomark.png",
        mascotPath: "/sites/kobe/assets/kobe_logomark.png",
        mascotFallback: "/sites/kobe/assets/kobe_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "kyoto",
        name: "Kyōto",
        greek: "京都",
        domain: "Imperial Capital, Kansai",
        tagline: "Capital city",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "japanese",
        folder: "kyoto",
        domainUnicode: "Kyōto.com",
        domainPunycode: "xn--Kyto-m3a.com",
        domainAlt: ["kyoto.com"],
        colors: { primary: "#FF6B6B", secondary: "#4ECDC4", glow: "rgba(255,107,107,0.3)" },
        logomarkPath: "/sites/kyoto/assets/kyoto_logomark.png",
        mascotPath: "/sites/kyoto/assets/kyoto_logomark.png",
        mascotFallback: "/sites/kyoto/assets/kyoto_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "libye",
        name: "Libyē",
        greek: "Λιβύη",
        domain: "Personified Continent of Africa",
        tagline: "The African continent (etymology uncertain)",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "greek-location",
        folder: "libye",
        domainUnicode: "Libyē.com",
        domainPunycode: "xn--Liby-eva.com",
        domainAlt: ["libye.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/libye/assets/libye_mascot.png",
        mascotFallback: "/sites/libye/assets/libye_mascot.png",
        logomarkPath: "/sites/libye/assets/libye_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "osaka",
        name: "Ōsaka",
        greek: "大阪",
        domain: "Merchant City, Kansai",
        tagline: "Large hill or slope",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "japanese",
        folder: "osaka",
        domainUnicode: "Ōsaka.com",
        domainPunycode: "xn--saka-f3a.com",
        domainAlt: ["osaka.com"],
        colors: { primary: "#FF6B6B", secondary: "#4ECDC4", glow: "rgba(255,107,107,0.3)" },
        logomarkPath: "/sites/osaka/assets/osaka_logomark.png",
        mascotPath: "/sites/osaka/assets/osaka_logomark.png",
        mascotFallback: "/sites/osaka/assets/osaka_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "persephone",
        name: "Persephonē",
        greek: "Περσεφόνη",
        domain: "Queen of the Underworld",
        tagline: "The Maiden · The Iron Queen",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "chthonic",
        folder: "persephone",
        domainUnicode: "persephonē.com",
        domainPunycode: "xn--persephon-jhb.com",
        colors: { primary: "#DC143C", secondary: "#8B008B", glow: "rgba(220,20,60,0.3)" },
        mascotPath: "/sites/persephone/assets/persephone_mascot.png",
        mascotFallback: "/sites/persephone/assets/persephone_mascot.png",
        logomarkPath: "/sites/persephone/assets/persephone_logomark.png",
        built: true,
        darkPunchline: true
    },
    {
        id: "poseidon",
        name: "Poseidōn",
        greek: "Ποσειδῶν",
        domain: "Lord of the Sea",
        tagline: "The Earth-Shaker · Master of Waves",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "poseidon",
        domainUnicode: "poseidōn.com",
        domainPunycode: "xn--poseidn-bmb.com",
        colors: { primary: "#1E90FF", secondary: "#00CED1", glow: "rgba(30,144,255,0.3)" },
        mascotPath: "/sites/poseidon/assets/poseidon_mascot.png",
        mascotFallback: "/sites/poseidon/assets/poseidon_mascot.png",
        logomarkPath: "/sites/poseidon/assets/poseidon_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "prometheus",
        name: "Promētheus",
        greek: "Προμηθεύς",
        domain: "The Fire-Bringer",
        tagline: "The Forethinker · Champion of Mortals",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "titan",
        folder: "prometheus",
        domainUnicode: "promētheus.com",
        domainPunycode: "xn--promtheus-ehb.com",
        colors: { primary: "#FF4500", secondary: "#4169E1", glow: "rgba(255,69,0,0.3)" },
        mascotPath: "/sites/prometheus/assets/prometheus_mascot.png",
        mascotFallback: "/sites/prometheus/assets/prometheus_mascot.png",
        logomarkPath: "/sites/prometheus/assets/prometheus_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "selene",
        name: "Selene",
        greek: "Σελήνη",
        domain: "Goddess of the Moon",
        tagline: "The Radiant · Driver of the Silver Chariot",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "selene",
        domainUnicode: "selene.com",
        domainPunycode: "selene.com",
        colors: { primary: "#E6E6FA", secondary: "#C0C0C0", glow: "rgba(230,230,250,0.3)" },
        mascotPath: "/sites/selene/assets/selene_mascot.png",
        mascotFallback: "/sites/selene/assets/selene_mascot.png",
        logomarkPath: "/sites/selene/assets/selene_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "sparte",
        name: "Spártē",
        greek: "Σπάρτη",
        domain: "Warrior City",
        tagline: "Sown land (from σπείρω)",
        tier: "tier-1",
        tierDetail: "tier-1",
        pantheon: "greek-location",
        folder: "sparte",
        domainUnicode: "Spártē.com",
        domainPunycode: "xn--Sprt-6na61a.com",
        domainAlt: ["sparte.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        logomarkPath: "/sites/sparte/assets/sparte_logomark.png",
        mascotPath: "/sites/sparte/assets/sparte_logomark.png",
        mascotFallback: "/sites/sparte/assets/sparte_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "zeus",
        name: "Zeús",
        greek: "Ζεύς",
        domain: "King of the Gods",
        tagline: "Lord of the Sky · Wielder of the Thunderbolt",
        tier: "tier-1",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "zeus",
        domainUnicode: "zeús.com",
        domainPunycode: "xn--zes-9na.com",
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/zeus/assets/zeus_mascot.png",
        mascotFallback: "/sites/zeus/assets/zeus_mascot.png",
        logomarkPath: "/sites/zeus/assets/zeus_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "alfheimr",
        name: "Álfheimr",
        greek: "—",
        domain: "Realm of the Light Elves",
        tagline: "Elf-home (from álfr + heimr)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "norse",
        folder: "alfheimr",
        domainUnicode: "Álfheimr.com",
        domainPunycode: "xn--lfheimr-4oa.com",
        domainAlt: ["alfheimr.com"],
        colors: { primary: "#4A90D9", secondary: "#8B0000", glow: "rgba(74,144,217,0.3)" },
        logomarkPath: "/sites/alfheimr/assets/alfheimr_logomark.png",
        mascotPath: "/sites/alfheimr/assets/alfheimr_logomark.png",
        mascotFallback: "/sites/alfheimr/assets/alfheimr_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "artemis",
        name: "Ártemis",
        greek: "Ἄρτεμις",
        domain: "Goddess of the Hunt",
        tagline: "The Virgin Huntress · Lady of Wild Beasts",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "artemis",
        domainUnicode: "ártemis.com",
        domainPunycode: "xn--rtemis-ota.com",
        colors: { primary: "#C0C0C0", secondary: "#228B22", glow: "rgba(192,192,192,0.3)" },
        mascotPath: "/sites/artemis/assets/artemis_mascot.png",
        mascotFallback: "/sites/artemis/assets/artemis_mascot.png",
        logomarkPath: "/sites/artemis/assets/artemis_logomark.png",
        built: true,
        darkPunchline: true
    },
    {
        id: "atlas",
        name: "Átlas",
        greek: "Ἄτλας",
        domain: "The Titan of Endurance",
        tagline: "The World-Bearer · Guardian of the Western Edge",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "titan",
        folder: "atlas",
        domainUnicode: "átlas.com",
        domainPunycode: "xn--tlas-4na.com",
        colors: { primary: "#CD7F32", secondary: "#8B4513", glow: "rgba(205,127,50,0.3)" },
        mascotPath: "/sites/atlas/assets/atlas_mascot.png",
        mascotFallback: "/sites/atlas/assets/atlas_mascot.png",
        logomarkPath: "/sites/atlas/assets/atlas_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "chaos",
        name: "Cháos",
        greek: "Χάος",
        domain: "The First Void",
        tagline: "Gap, yawning void (from χάος)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "greek",
        folder: "chaos",
        domainUnicode: "Cháos.com",
        domainPunycode: "xn--Chos-6na.com",
        domainAlt: ["chaos.com"],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        logomarkPath: "/sites/chaos/assets/chaos_logomark.png",
        mascotPath: "/sites/chaos/assets/chaos_logomark.png",
        mascotFallback: "/sites/chaos/assets/chaos_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "delphoi",
        name: "Delphoí",
        greek: "Δελφοί",
        domain: "Oracle of Apollo",
        tagline: "Womb (from δελφύς)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "greek-location",
        folder: "delphoi",
        domainUnicode: "Delphoí.com",
        domainPunycode: "xn--Delpho-8va.com",
        domainAlt: ["delphoi.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        logomarkPath: "/sites/delphoi/assets/delphoi_logomark.png",
        mascotPath: "/sites/delphoi/assets/delphoi_logomark.png",
        mascotFallback: "/sites/delphoi/assets/delphoi_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "dionysos",
        name: "Diónysos",
        greek: "Διόνυσος",
        domain: "God of Wine & Ecstasy",
        tagline: "The Liberator · Twice-Born",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "olympian",
        folder: "dionysos",
        domainUnicode: "diónysos.com",
        domainPunycode: "xn--dinysos-m0a.com",
        colors: { primary: "#800080", secondary: "#DAA520", glow: "rgba(128,0,128,0.3)" },
        mascotPath: "/sites/dionysos/assets/dionysos_mascot.png",
        mascotFallback: "/sites/dionysos/assets/dionysos_mascot.png",
        logomarkPath: "/sites/dionysos/assets/dionysos_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "helheimr",
        name: "Helheimr",
        greek: "—",
        domain: "Realm of the Dead",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "norse",
        folder: "helheimr",
        domainUnicode: "Helheimr.com",
        domainPunycode: "Helheimr.com",
        domainAlt: ["helheimr.com"],
        colors: { primary: "#4A90D9", secondary: "#8B0000", glow: "rgba(74,144,217,0.3)" },
        logomarkPath: "/sites/helheimr/assets/helheimr_logomark.png",
        mascotPath: "/sites/helheimr/assets/helheimr_logomark.png",
        mascotFallback: "/sites/helheimr/assets/helheimr_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "jotunheimr",
        name: "Jötunheimr",
        greek: "—",
        domain: "Land of the Giants",
        tagline: "Giant-home (from jötunn + heimr)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "norse",
        folder: "jotunheimr",
        domainUnicode: "Jötunheimr.com",
        domainPunycode: "xn--Jtunheimr-07a.com",
        domainAlt: ["jotunheimr.com"],
        colors: { primary: "#4A90D9", secondary: "#8B0000", glow: "rgba(74,144,217,0.3)" },
        logomarkPath: "/sites/jotunheimr/assets/jotunheimr_logomark.png",
        mascotPath: "/sites/jotunheimr/assets/jotunheimr_logomark.png",
        mascotFallback: "/sites/jotunheimr/assets/jotunheimr_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "ker",
        name: "Kēr",
        greek: "Κήρ",
        domain: "Spirit of Violent Death",
        tagline: "The Dark Angel · Minister of Doom",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "chthonic",
        folder: "ker",
        domainUnicode: "kēr.com",
        domainPunycode: "xn--kr-wma.com",
        colors: { primary: "#4A4A4A", secondary: "#8B0000", glow: "rgba(74,74,74,0.3)" },
        mascotPath: "/sites/ker/assets/ker_mascot.png",
        mascotFallback: "/sites/ker/assets/ker_mascot.png",
        logomarkPath: "/sites/ker/assets/ker_logomark.png",
        built: true,
        darkPunchline: true
    },
    {
        id: "medousa",
        name: "Médousa",
        greek: "Μέδουσα",
        domain: "The Gorgon",
        tagline: "The Petrifying · Guardian of the Threshold",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "other",
        folder: "medousa",
        domainUnicode: "médousa.com",
        domainPunycode: "xn--mdousa-bva.com",
        colors: { primary: "#2E8B57", secondary: "#556B2F", glow: "rgba(46,139,87,0.3)" },
        mascotPath: "/sites/medousa/assets/medusa_mascot.png",
        mascotFallback: "/sites/medousa/assets/medusa_mascot.png",
        logomarkPath: "/sites/medousa/assets/medusa_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "midgardr",
        name: "Miðgarðr",
        greek: "—",
        domain: "Middle Enclosure (Earth)",
        tagline: "Middle enclosure (from mið + garðr)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "norse",
        folder: "midgardr",
        domainUnicode: "Miðgarðr.com",
        domainPunycode: "xn--Migarr-qwad.com",
        domainAlt: ["midgardr.com"],
        colors: { primary: "#4A90D9", secondary: "#8B0000", glow: "rgba(74,144,217,0.3)" },
        logomarkPath: "/sites/midgardr/assets/midgardr_logomark.png",
        mascotPath: "/sites/midgardr/assets/midgardr_logomark.png",
        mascotFallback: "/sites/midgardr/assets/midgardr_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "muspellheimr",
        name: "Muspellheimr",
        greek: "—",
        domain: "World of Fire",
        tagline: "Muspel-home (world-ender)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "norse",
        folder: "muspellheimr",
        domainUnicode: "Muspellheimr.com",
        domainPunycode: "Muspellheimr.com",
        domainAlt: ["muspellheimr.com"],
        colors: { primary: "#4A90D9", secondary: "#8B0000", glow: "rgba(74,144,217,0.3)" },
        logomarkPath: "/sites/muspellheimr/assets/muspellheimr_logomark.png",
        mascotPath: "/sites/muspellheimr/assets/muspellheimr_logomark.png",
        mascotFallback: "/sites/muspellheimr/assets/muspellheimr_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "maat",
        name: "Mꜣꜥt",
        greek: "—",
        domain: "Truth, Justice, Order",
        tagline: "Truth, straightness (Egyptian mꜣꜥt)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        folder: "maat",
        domainUnicode: "Mꜣꜥt.com",
        domainPunycode: "xn--Mt-sq8hia.com",
        domainAlt: ["maat.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/maat/assets/maat_mascot.png",
        mascotFallback: "/sites/maat/assets/maat_mascot.png",
        logomarkPath: "/sites/maat/assets/maat_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "maa",
        name: "Mꜥ",
        greek: "—",
        domain: "Vision, Perception, Understanding",
        tagline: "To see, to perceive, to understand. A core verb root, extremely common in texts",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        folder: "maa",
        domainUnicode: "Mꜥ.com",
        domainPunycode: "xn--M-2w3e.com",
        domainAlt: ["maa.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/maa/assets/maa_mascot.png",
        mascotFallback: "/sites/maa/assets/maa_mascot.png",
        logomarkPath: "/sites/maa/assets/maa_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "odinn",
        name: "Óðinn",
        greek: "Óðinn",
        domain: "Allfather",
        tagline: "The Frenzied One · Lord of the Hanged",
        tier: "tier-2",
        tierDetail: "single-tier",
        pantheon: "norse",
        folder: "odinn",
        domainUnicode: "ódinn.com",
        domainPunycode: "xn--dinn-pqa.com",
        colors: { primary: "#5C5C5C", secondary: "#4169E1", glow: "rgba(92,92,92,0.3)" },
        mascotPath: "/sites/odinn/assets/odinn_mascot.png",
        mascotFallback: "/sites/odinn/assets/odinn_mascot.png",
        logomarkPath: "/sites/odinn/assets/odinn_logomark.png",
        built: true,
        darkPunchline: true
    },
    {
        id: "olympos",
        name: "Ólympos",
        greek: "Ὄλυμπος",
        domain: "Mountain of the Gods",
        tagline: "Bright, shining mountain",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "greek-location",
        folder: "olympos",
        domainUnicode: "Ólympos.com",
        domainPunycode: "xn--lympos-vqa.com",
        domainAlt: ["olympos.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        logomarkPath: "/sites/olympos/assets/olympos_logomark.png",
        mascotPath: "/sites/olympos/assets/olympos_logomark.png",
        mascotFallback: "/sites/olympos/assets/olympos_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "pontos",
        name: "Póntos",
        greek: "Πόντος",
        domain: "The Primordial Sea",
        tagline: "Sea (from πόντος)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "greek",
        folder: "pontos",
        domainUnicode: "Póntos.com",
        domainPunycode: "xn--Pntos-0ta.com",
        domainAlt: ["pontos.com"],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        logomarkPath: "/sites/pontos/assets/pontos_logomark.png",
        mascotPath: "/sites/pontos/assets/pontos_logomark.png",
        mascotFallback: "/sites/pontos/assets/pontos_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "ragnarok",
        name: "Ragnarǫk",
        greek: "—",
        domain: "Doom of the Gods",
        tagline: "Twilight of the gods (from ragna + rǫk)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "norse",
        folder: "ragnarok",
        domainUnicode: "Ragnarǫk.com",
        domainPunycode: "xn--Ragnark-fnc.com",
        domainAlt: ["ragnarok.com"],
        colors: { primary: "#4A90D9", secondary: "#8B0000", glow: "rgba(74,144,217,0.3)" },
        logomarkPath: "/sites/ragnarok/assets/ragnarok_logomark.png",
        mascotPath: "/sites/ragnarok/assets/ragnarok_logomark.png",
        mascotFallback: "/sites/ragnarok/assets/ragnarok_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "ra",
        name: "Rꜥ",
        greek: "—",
        domain: "Sun, Creation, Kingship",
        tagline: "Sun (from Egyptian rꜥ)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        folder: "ra",
        domainUnicode: "Rꜥ.com",
        domainPunycode: "xn--R-2w3e.com",
        domainAlt: ["ra.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/ra/assets/ra_mascot.png",
        mascotFallback: "/sites/ra/assets/ra_mascot.png",
        logomarkPath: "/sites/ra/assets/ra_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "sia",
        name: "Sia",
        greek: "—",
        domain: "Divine Archetype",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "greek",
        folder: "sia",
        domainUnicode: "sia.com",
        domainPunycode: "sia.com",
        domainAlt: ["sia.com"],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/sia/assets/sia_mascot.png",
        mascotFallback: "/sites/sia/assets/sia_mascot.png",
        logomarkPath: "/sites/sia/assets/sia_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "shiva",
        name: "Śiva",
        greek: "—",
        domain: "Destruction, Transformation, Dance",
        tagline: "Auspicious, kind (from शिव)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "sanskrit",
        folder: "shiva",
        domainUnicode: "Śiva.com",
        domainPunycode: "xn--iva-6ya.com",
        domainAlt: ["shiva.com"],
        colors: { primary: "#FF9933", secondary: "#138808", glow: "rgba(255,153,51,0.3)" },
        mascotPath: "/sites/shiva/assets/siva_mascot.png",
        mascotFallback: "/sites/shiva/assets/siva_mascot.png",
        logomarkPath: "/sites/shiva/assets/siva_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "shu",
        name: "Šw",
        greek: "—",
        domain: "Air, Wind, Lions",
        tagline: "Emptiness, he who rises up",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        folder: "shu",
        domainUnicode: "Šw.com",
        domainPunycode: "xn--w-2ma.com",
        domainAlt: ["shu.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/shu/assets/shu_mascot.png",
        mascotFallback: "/sites/shu/assets/shu_mascot.png",
        logomarkPath: "/sites/shu/assets/shu_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "tartaros",
        name: "Tártaros",
        greek: "Τάρταρος",
        domain: "The Primordial Abyss",
        tagline: "Deep place (from τάρταρος)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "greek",
        folder: "tartaros",
        domainUnicode: "Tártaros.com",
        domainPunycode: "xn--Trtaros-hwa.com",
        domainAlt: ["tartaros.com"],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        logomarkPath: "/sites/tartaros/assets/tartaros_logomark.png",
        mascotPath: "/sites/tartaros/assets/tartaros_logomark.png",
        mascotFallback: "/sites/tartaros/assets/tartaros_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "thor",
        name: "Þórr",
        greek: "—",
        domain: "Thunder, Storms, Oak",
        tagline: "Thunder (from *þunraz)",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "norse",
        folder: "thor",
        domainUnicode: "Þórr.com",
        domainPunycode: "xn--rr-cia8f.com",
        domainAlt: ["thor.com"],
        colors: { primary: "#4A90D9", secondary: "#8B0000", glow: "rgba(74,144,217,0.3)" },
        mascotPath: "/sites/thor/assets/thorr_mascot.png",
        mascotFallback: "/sites/thor/assets/thorr_mascot.png",
        logomarkPath: "/sites/thor/assets/thorr_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "ab",
        name: "Ꜣb",
        greek: "—",
        domain: "Heart, Conscience, Emotion",
        tagline: "Heart. Central to the weighing of the heart ritual. Represents conscience, emotion, moral worth",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        folder: "ab",
        domainUnicode: "Ꜣb.com",
        domainPunycode: "xn--b-vw3e.com",
        domainAlt: ["ab.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/ab/assets/ab_mascot.png",
        mascotFallback: "/sites/ab/assets/ab_mascot.png",
        logomarkPath: "/sites/ab/assets/ab_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "akh",
        name: "Ꜣḫ",
        greek: "—",
        domain: "Soul, Afterlife, Transfiguration",
        tagline: "Akh, transfigured spirit; effective, luminous being. One of the highest forms of the soul",
        tier: "tier-2",
        tierDetail: "tier-2",
        pantheon: "egyptian",
        folder: "akh",
        domainUnicode: "Ꜣḫ.com",
        domainPunycode: "xn--9gg7559c.com",
        domainAlt: ["akh.com"],
        colors: { primary: "#D4AF37", secondary: "#228B22", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/akh/assets/akh_mascot.png",
        mascotFallback: "/sites/akh/assets/akh_mascot.png",
        logomarkPath: "/sites/akh/assets/akh_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "apollon",
        name: "Ápollōn",
        greek: "Ἀπόλλων",
        domain: "God of Light, Music & Prophecy",
        tagline: "The Far-Shooter · Lord of the Silver Bow",
        tier: "dual-tier",
        tierDetail: "dual-tier",
        pantheon: "olympian",
        folder: "apollon",
        domainUnicode: "ápollōn.com",
        domainPunycode: "xn--polln-wqa47e.com",
        domainAlt: ["apollon.com"],
        colors: { primary: "#D4AF37", secondary: "#4169E1", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/apollon/assets/apollon_mascot.png",
        mascotFallback: "/sites/apollon/assets/apollon_mascot.png",
        logomarkPath: "/sites/apollon/assets/apollon_logomark.png",
        built: true,
        darkPunchline: false
    },
    {
        id: "hades",
        name: "Hádēs",
        greek: "Ἅιδης",
        domain: "Lord of the Underworld",
        tagline: "The Unseen King · Warden of the Dead",
        tier: "dual-tier",
        tierDetail: "dual-tier",
        pantheon: "chthonic",
        folder: "hades",
        domainUnicode: "hádēs.com",
        domainPunycode: "xn--hds-ela5w.com",
        domainAlt: ["hades.com", "hādēs.com"],
        colors: { primary: "#8B0000", secondary: "#D4AF37", glow: "rgba(139,0,0,0.3)" },
        mascotPath: "/sites/hades/assets/hades_mascot.png",
        mascotFallback: "/sites/hades/assets/hades_mascot.png",
        logomarkPath: "/sites/hades/assets/hades_logomark.png",
        built: true,
        darkPunchline: true
    },
    {
        id: "hekate",
        name: "Hekátē",
        greek: "Ἑκάτη",
        domain: "Goddess of Magic & Crossroads",
        tagline: "The Torch-Bearer · Queen of Ghosts",
        tier: "dual-tier",
        tierDetail: "dual-tier",
        pantheon: "chthonic",
        folder: "hekate",
        domainUnicode: "hekátē.com",
        domainPunycode: "xn--hekt-7na51a.com",
        domainAlt: ["hekate.com"],
        colors: { primary: "#FF6B35", secondary: "#8B00FF", glow: "rgba(255,107,53,0.3)" },
        mascotPath: "/sites/hekate/assets/hekate_mascot.png",
        mascotFallback: "/sites/hekate/assets/hekate_mascot.png",
        logomarkPath: "/sites/hekate/assets/hekate_logomark.png",
        built: true,
        darkPunchline: true
    },
    {
        id: "nike",
        name: "Níkē",
        greek: "Νίκη",
        domain: "Goddess of Victory",
        tagline: "The Winged Herald · Bringer of Triumph",
        tier: "dual-tier",
        tierDetail: "dual-tier",
        pantheon: "olympian",
        folder: "nike",
        domainUnicode: "níkē.com",
        domainPunycode: "xn--nk-nja7m.com",
        domainAlt: ["nike.com"],
        colors: { primary: "#D4AF37", secondary: "#FFFFFF", glow: "rgba(212,175,55,0.3)" },
        mascotPath: "/sites/nike/assets/nike_mascot.png",
        mascotFallback: "/sites/nike/assets/nike_mascot.png",
        logomarkPath: "/sites/nike/assets/nike_logomark.png",
        built: true,
        darkPunchline: false
    },
];
