/**
 * PUNICODEX — Domain Dispute Research Helper
 *
 * Neutral case tracking and evidence-package generation for internal review.
 */

const crypto = require('node:crypto');
const { getDb } = require('../db/connection.js');
const { appendAuditLog } = require('./audit-log.js');
const { all, run, get, insert } = require('../db/operational.js');

const SYSTEM_TENANT_ID = 'system';
const auditDb = { all, run, get, insert };

function sha256(input) {
  return crypto.createHash('sha256').update(String(input)).digest('hex');
}

function generateCaseId() {
  return `udrp_${Date.now().toString(36)}_${crypto.randomBytes(4).toString('hex')}`;
}

function generateReportId() {
  return `udrp_report_${Date.now().toString(36)}_${crypto.randomBytes(4).toString('hex')}`;
}

async function logUdrpAction(action, resourceId, metadata = {}) {
  await appendAuditLog(auditDb, {
    tenant_id: SYSTEM_TENANT_ID,
    actor_type: 'system',
    actor_id: 'udrp-service',
    action,
    resource_type: 'udrp_case',
    resource_id: resourceId,
    metadata,
  });
}

async function createUdrpCase({
  caseId = generateCaseId(),
  domain,
  complainant = null,
  respondent = null,
  status = 'pending',
  outcome = null,
  decidedAt = null,
}) {
  if (!domain) {
    throw new Error('domain is required');
  }

  const now = new Date().toISOString();
  getDb()
    .prepare(
      `INSERT INTO udrp_cases
       (case_id, domain, complainant, respondent, status, outcome, decided_at, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`
    )
    .run(caseId, domain, complainant, respondent, status, outcome, decidedAt, now, now);

  await logUdrpAction('udrp_case_created', caseId, { domain, complainant, status });

  return getDb().prepare('SELECT * FROM udrp_cases WHERE case_id = ?').get(caseId);
}

function getUdrpStatus(domain) {
  return (
    getDb()
      .prepare('SELECT * FROM udrp_cases WHERE domain = ? ORDER BY created_at DESC LIMIT 1')
      .get(domain) || null
  );
}

function getUdrpCaseById(caseId) {
  return getDb().prepare('SELECT * FROM udrp_cases WHERE case_id = ?').get(caseId) || null;
}

async function generateEvidencePackage(domain, classificationSnapshot = null) {
  const startedAt = Date.now();
  const db = getDb();
  const existingCase = getUdrpStatus(domain);

  const packageBody = {
    reportId: generateReportId(),
    generatedAt: new Date().toISOString(),
    domain,
    forum: 'WIPO',
    caseId: existingCase?.case_id || null,
    complainant: existingCase?.complainant || null,
    respondent: existingCase?.respondent || null,
    classificationSnapshot: classificationSnapshot
      ? {
          verdict: classificationSnapshot.verdict,
          severity: classificationSnapshot.severity,
          canonicalMatch: classificationSnapshot.canonicalMatch || null,
          reason: classificationSnapshot.reason || null,
        }
      : null,
    exhibits: [
      {
        label: 'Name authenticity classification',
        data: classificationSnapshot || null,
      },
      {
        label: 'WHOIS / RDAP registration record',
        data: null,
        note: 'Populate from registrar RDAP response before submission.',
      },
      {
        label: 'Rendered glyph comparison screenshots',
        data: null,
        note: 'Attach browser or SDK-rendered side-by-side images.',
      },
    ],
    recommendedAction:
      classificationSnapshot && ['critical', 'high'].includes(classificationSnapshot.severity)
        ? 'file_udrp'
        : 'monitor',
    legalNotes:
      'Generated by the PUNICODEX Name Authenticity Shield. This package is intended as evidence support and does not constitute legal advice.',
  };

  packageBody.chainOfCustodyHash = sha256(JSON.stringify(packageBody));

  if (existingCase) {
    db.prepare('UPDATE udrp_cases SET evidence_package = ?, updated_at = ? WHERE id = ?').run(
      JSON.stringify(packageBody),
      new Date().toISOString(),
      existingCase.id
    );
  }

  await logUdrpAction('udrp_evidence_generated', packageBody.reportId, {
    domain,
    caseId: existingCase?.case_id || null,
    durationMs: Date.now() - startedAt,
  });

  return packageBody;
}

async function recordOutcome(caseId, outcome, decidedAt = new Date().toISOString()) {
  const existing = getUdrpCaseById(caseId);
  if (!existing) {
    throw new Error(`UDRP case not found: ${caseId}`);
  }

  getDb()
    .prepare(
      `UPDATE udrp_cases
       SET status = 'decided',
           outcome = ?,
           decided_at = ?,
           updated_at = ?
       WHERE id = ?`
    )
    .run(outcome, decidedAt, new Date().toISOString(), existing.id);

  await logUdrpAction('udrp_outcome_recorded', caseId, { outcome, decidedAt });

  return getUdrpCaseById(caseId);
}

module.exports = {
  createUdrpCase,
  getUdrpStatus,
  getUdrpCaseById,
  generateEvidencePackage,
  recordOutcome,
};
