// Auto-generated from js/archetypes-v2.js
// 1. Redirects deity domains → punycodex.com/{id} (bypasses homograph warnings)
// 2. Rewrites punycodex.com/{id}/* → /sites/{id}/* (clean ASCII URLs)

const DOMAIN_MAP = {
  'aígyptos.com': '/sites/aigyptos',
  'álfheimr.com': '/sites/alfheimr',
  'aphrodítē.com': '/sites/aphrodite',
  'aphrodītē.com': '/sites/aphrodite',
  'apollōn.com': '/sites/apollon',
  'apóllōn.com': '/sites/apollon',
  'árēs.com': '/sites/ares',
  'ártemis.com': '/sites/artemis',
  'asía.com': '/sites/asia',
  'athénā.com': '/sites/athena',
  'athēnai.com': '/sites/athenai',
  'átlas.com': '/sites/atlas',
  'cháos.com': '/sites/chaos',
  'delphoí.com': '/sites/delphoi',
  'dēmētēr.com': '/sites/demeter',
  'diónysos.com': '/sites/dionysos',
  'eurōpē.com': '/sites/europe',
  'eurṓpē.com': '/sites/europe',
  'gaîa.com': '/sites/gaia',
  'hádēs.com': '/sites/hades',
  'hekatē.com': '/sites/hekate',
  'hekátē.com': '/sites/hekate',
  'helheimr.com': '/sites/helheimr',
  'hēlios.com': '/sites/helios',
  'hēphaistos.com': '/sites/hephaistos',
  'hēra.com': '/sites/hera',
  'hermês.com': '/sites/hermes',
  'hermēs.com': '/sites/hermes',
  'hestía.com': '/sites/hestia',
  'jötunheimr.com': '/sites/jotunheimr',
  'kēr.com': '/sites/ker',
  'kōbe.com': '/sites/kobe',
  'kyōto.com': '/sites/kyoto',
  'libyē.com': '/sites/libye',
  'médousa.com': '/sites/medousa',
  'miðgarðr.com': '/sites/midgardr',
  'muspellheimr.com': '/sites/muspellheimr',
  'mꜣ.com': '/sites/maat',
  'mꜥ.com': '/sites/maa',
  'nikē.com': '/sites/nike',
  'níkê.com': '/sites/nike',
  'níkē.com': '/sites/nike',
  'óðinn.com': '/sites/odinn',
  'ólympos.com': '/sites/olympos',
  'ōsaka.com': '/sites/osaka',
  'persephonē.com': '/sites/persephone',
  'póntos.com': '/sites/pontos',
  'poseidôn.com': '/sites/poseidon',
  'poseidōn.com': '/sites/poseidon',
  'promētheus.com': '/sites/prometheus',
  'ragnarǫk.com': '/sites/ragnarok',
  'rꜥ.com': '/sites/ra',
  'selēnē.com': '/sites/selene',
  'śiva.com': '/sites/shiva',
  'spártē.com': '/sites/sparte',
  'šw.com': '/sites/shu',
  'sꜥ.com': '/sites/sia',
  'tártaros.com': '/sites/tartaros',
  'www.aígyptos.com': '/sites/aigyptos',
  'www.álfheimr.com': '/sites/alfheimr',
  'www.aphrodítē.com': '/sites/aphrodite',
  'www.aphrodītē.com': '/sites/aphrodite',
  'www.apollōn.com': '/sites/apollon',
  'www.apóllōn.com': '/sites/apollon',
  'www.árēs.com': '/sites/ares',
  'www.ártemis.com': '/sites/artemis',
  'www.asía.com': '/sites/asia',
  'www.athénā.com': '/sites/athena',
  'www.athēnai.com': '/sites/athenai',
  'www.átlas.com': '/sites/atlas',
  'www.cháos.com': '/sites/chaos',
  'www.delphoí.com': '/sites/delphoi',
  'www.dēmētēr.com': '/sites/demeter',
  'www.diónysos.com': '/sites/dionysos',
  'www.eurōpē.com': '/sites/europe',
  'www.eurṓpē.com': '/sites/europe',
  'www.gaîa.com': '/sites/gaia',
  'www.hádēs.com': '/sites/hades',
  'www.hekatē.com': '/sites/hekate',
  'www.hekátē.com': '/sites/hekate',
  'www.helheimr.com': '/sites/helheimr',
  'www.hēlios.com': '/sites/helios',
  'www.hēphaistos.com': '/sites/hephaistos',
  'www.hēra.com': '/sites/hera',
  'www.hermês.com': '/sites/hermes',
  'www.hermēs.com': '/sites/hermes',
  'www.hestía.com': '/sites/hestia',
  'www.jötunheimr.com': '/sites/jotunheimr',
  'www.kēr.com': '/sites/ker',
  'www.kōbe.com': '/sites/kobe',
  'www.kyōto.com': '/sites/kyoto',
  'www.libyē.com': '/sites/libye',
  'www.médousa.com': '/sites/medousa',
  'www.miðgarðr.com': '/sites/midgardr',
  'www.muspellheimr.com': '/sites/muspellheimr',
  'www.mꜣ.com': '/sites/maat',
  'www.mꜥ.com': '/sites/maa',
  'www.nikē.com': '/sites/nike',
  'www.níkê.com': '/sites/nike',
  'www.níkē.com': '/sites/nike',
  'www.óðinn.com': '/sites/odinn',
  'www.ólympos.com': '/sites/olympos',
  'www.ōsaka.com': '/sites/osaka',
  'www.persephonē.com': '/sites/persephone',
  'www.póntos.com': '/sites/pontos',
  'www.poseidôn.com': '/sites/poseidon',
  'www.poseidōn.com': '/sites/poseidon',
  'www.promētheus.com': '/sites/prometheus',
  'www.ragnarǫk.com': '/sites/ragnarok',
  'www.rꜥ.com': '/sites/ra',
  'www.selēnē.com': '/sites/selene',
  'www.śiva.com': '/sites/shiva',
  'www.spártē.com': '/sites/sparte',
  'www.šw.com': '/sites/shu',
  'www.sꜥ.com': '/sites/sia',
  'www.tártaros.com': '/sites/tartaros',
  'www.xn--9gg9559c.com': '/sites/akh',
  'www.xn--agyptos-7ya.com': '/sites/aigyptos',
  'www.xn--aphrodt-27a8s.com': '/sites/aphrodite',
  'www.xn--aphrodt-dza75a.com': '/sites/aphrodite',
  'www.xn--aplln-1ta64d.com': '/sites/apollon',
  'www.xn--apolln-fgb.com': '/sites/apollon',
  'www.xn--asa-sma.com': '/sites/asia',
  'www.xn--athn-dpa9l.com': '/sites/athena',
  'www.xn--athnai-r3a.com': '/sites/athenai',
  'www.xn--b-xw3e.com': '/sites/ab',
  'www.xn--chos-6na.com': '/sites/chaos',
  'www.xn--delpho-8va.com': '/sites/delphoi',
  'www.xn--dinysos-m0a.com': '/sites/dionysos',
  'www.xn--dmtr-bvabb.com': '/sites/demeter',
  'www.xn--eurp-eva0406b.com': '/sites/europe',
  'www.xn--eurp-eva06a.com': '/sites/europe',
  'www.xn--gaa-wma.com': '/sites/gaia',
  'www.xn--hds-ela5w.com': '/sites/hades',
  'www.xn--hekat-mza.com': '/sites/hekate',
  'www.xn--hekt-7na51a.com': '/sites/hekate',
  'www.xn--herms-ksa.com': '/sites/hermes',
  'www.xn--herms-lza.com': '/sites/hermes',
  'www.xn--hesta-2sa.com': '/sites/hestia',
  'www.xn--hlios-iza.com': '/sites/helios',
  'www.xn--hphaistos-bhb.com': '/sites/hephaistos',
  'www.xn--hra-3qa.com': '/sites/hera',
  'www.xn--inn-2mao.com': '/sites/odinn',
  'www.xn--iva-bza.com': '/sites/shiva',
  'www.xn--jtunheimr-07a.com': '/sites/jotunheimr',
  'www.xn--kbe-qxa.com': '/sites/kobe',
  'www.xn--kr-wma.com': '/sites/ker',
  'www.xn--kyto-m3a.com': '/sites/kyoto',
  'www.xn--lfheimr-gwa.com': '/sites/alfheimr',
  'www.xn--liby-eva.com': '/sites/libye',
  'www.xn--lympos-9wa.com': '/sites/olympos',
  'www.xn--m-2w3e.com': '/sites/maa',
  'www.xn--m-yw3e.com': '/sites/maat',
  'www.xn--mdousa-bva.com': '/sites/medousa',
  'www.xn--migarr-qwad.com': '/sites/midgardr',
  'www.xn--nik-5qa.com': '/sites/nike',
  'www.xn--nk-fjak.com': '/sites/nike',
  'www.xn--nk-nja7m.com': '/sites/nike',
  'www.xn--persephon-jhb.com': '/sites/persephone',
  'www.xn--pntos-0ta.com': '/sites/pontos',
  'www.xn--poseidn-bmb.com': '/sites/poseidon',
  'www.xn--poseidn-y0a.com': '/sites/poseidon',
  'www.xn--promtheus-ehb.com': '/sites/prometheus',
  'www.xn--r-2w3e.com': '/sites/ra',
  'www.xn--ragnark-fnc.com': '/sites/ragnarok',
  'www.xn--rr-4ja7b.com': '/sites/thor',
  'www.xn--rs-lia5r.com': '/sites/ares',
  'www.xn--rtemis-ota.com': '/sites/artemis',
  'www.xn--s-2w3e.com': '/sites/sia',
  'www.xn--saka-k3a.com': '/sites/osaka',
  'www.xn--seln-dvab.com': '/sites/selene',
  'www.xn--sprt-6na61a.com': '/sites/sparte',
  'www.xn--tlas-4na.com': '/sites/atlas',
  'www.xn--trtaros-hwa.com': '/sites/tartaros',
  'www.xn--w-4ma.com': '/sites/shu',
  'www.xn--zes-9na.com': '/sites/zeus',
  'www.zeús.com': '/sites/zeus',
  'www.þórr.com': '/sites/thor',
  'www.ꜣb.com': '/sites/ab',
  'www.ꜣḫ.com': '/sites/akh',
  'xn--9gg9559c.com': '/sites/akh',
  'xn--agyptos-7ya.com': '/sites/aigyptos',
  'xn--aphrodt-27a8s.com': '/sites/aphrodite',
  'xn--aphrodt-dza75a.com': '/sites/aphrodite',
  'xn--aplln-1ta64d.com': '/sites/apollon',
  'xn--apolln-fgb.com': '/sites/apollon',
  'xn--asa-sma.com': '/sites/asia',
  'xn--athn-dpa9l.com': '/sites/athena',
  'xn--athnai-r3a.com': '/sites/athenai',
  'xn--b-xw3e.com': '/sites/ab',
  'xn--chos-6na.com': '/sites/chaos',
  'xn--delpho-8va.com': '/sites/delphoi',
  'xn--dinysos-m0a.com': '/sites/dionysos',
  'xn--dmtr-bvabb.com': '/sites/demeter',
  'xn--eurp-eva0406b.com': '/sites/europe',
  'xn--eurp-eva06a.com': '/sites/europe',
  'xn--gaa-wma.com': '/sites/gaia',
  'xn--hds-ela5w.com': '/sites/hades',
  'xn--hekat-mza.com': '/sites/hekate',
  'xn--hekt-7na51a.com': '/sites/hekate',
  'xn--herms-ksa.com': '/sites/hermes',
  'xn--herms-lza.com': '/sites/hermes',
  'xn--hesta-2sa.com': '/sites/hestia',
  'xn--hlios-iza.com': '/sites/helios',
  'xn--hphaistos-bhb.com': '/sites/hephaistos',
  'xn--hra-3qa.com': '/sites/hera',
  'xn--inn-2mao.com': '/sites/odinn',
  'xn--iva-bza.com': '/sites/shiva',
  'xn--jtunheimr-07a.com': '/sites/jotunheimr',
  'xn--kbe-qxa.com': '/sites/kobe',
  'xn--kr-wma.com': '/sites/ker',
  'xn--kyto-m3a.com': '/sites/kyoto',
  'xn--lfheimr-gwa.com': '/sites/alfheimr',
  'xn--liby-eva.com': '/sites/libye',
  'xn--lympos-9wa.com': '/sites/olympos',
  'xn--m-2w3e.com': '/sites/maa',
  'xn--m-yw3e.com': '/sites/maat',
  'xn--mdousa-bva.com': '/sites/medousa',
  'xn--migarr-qwad.com': '/sites/midgardr',
  'xn--nik-5qa.com': '/sites/nike',
  'xn--nk-fjak.com': '/sites/nike',
  'xn--nk-nja7m.com': '/sites/nike',
  'xn--persephon-jhb.com': '/sites/persephone',
  'xn--pntos-0ta.com': '/sites/pontos',
  'xn--poseidn-bmb.com': '/sites/poseidon',
  'xn--poseidn-y0a.com': '/sites/poseidon',
  'xn--promtheus-ehb.com': '/sites/prometheus',
  'xn--r-2w3e.com': '/sites/ra',
  'xn--ragnark-fnc.com': '/sites/ragnarok',
  'xn--rr-4ja7b.com': '/sites/thor',
  'xn--rs-lia5r.com': '/sites/ares',
  'xn--rtemis-ota.com': '/sites/artemis',
  'xn--s-2w3e.com': '/sites/sia',
  'xn--saka-k3a.com': '/sites/osaka',
  'xn--seln-dvab.com': '/sites/selene',
  'xn--sprt-6na61a.com': '/sites/sparte',
  'xn--tlas-4na.com': '/sites/atlas',
  'xn--trtaros-hwa.com': '/sites/tartaros',
  'xn--w-4ma.com': '/sites/shu',
  'xn--zes-9na.com': '/sites/zeus',
  'zeús.com': '/sites/zeus',
  'þórr.com': '/sites/thor',
  'ꜣb.com': '/sites/ab',
  'ꜣḫ.com': '/sites/akh'
};

// Build reverse map: domain → archetype id
const DOMAIN_TO_ID = {};
for (const [domain, path] of Object.entries(DOMAIN_MAP)) {
  const id = path.replace('/sites/', '');
  DOMAIN_TO_ID[domain] = id;
}

// Set of archetype IDs for path-based routing on punycodex.com
const ARCHETYPE_IDS = new Set(Object.values(DOMAIN_MAP).map(p => p.replace('/sites/', '')));

export const config = {
  matcher: '/:path*',
};

export default function middleware(request) {
  const url = new URL(request.url);
  // Normalize host: lowercase, strip port, trim whitespace
  const host = (request.headers.get('host') || '').toLowerCase().split(':')[0].trim();

  // ─── 1. Domain redirect ────────────────────────────────────────────
  // Unicode/punycode domains → 301 redirect to punycodex.com/{id}
  const id = DOMAIN_TO_ID[host];
  if (id) {
    url.hostname = 'punycodex.com';
    url.pathname = '/' + id + url.pathname;
    const response = Response.redirect(url.toString(), 301);
    // Prevent edge caching of this redirect; force revalidation
    response.headers.set('Cache-Control', 'public, max-age=0, must-revalidate');
    return response;
  }

  // ─── 2. Archetype path rewrite ─────────────────────────────────────
  // punycodex.com/{id}/* → internally serves /sites/{id}/*
  // URL stays as /{id}/* for clean SEO and UX
  const pathParts = url.pathname.split('/').filter(Boolean);
  const potentialId = pathParts[0];

  if (ARCHETYPE_IDS.has(potentialId)) {
    const prefix = '/' + potentialId;
    if (url.pathname === prefix || url.pathname.startsWith(prefix + '/')) {
      url.pathname = '/sites' + url.pathname;
      return fetch(url);
    }
  }

  return fetch(request);
}
