name: punicodex_authenticity
description: Flutter wrapper for the PuniCodex Name Authenticity Shield.
version: 2.0.0
homepage: https://punicodex.com

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_js: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.punicodex.authenticity
        pluginClass: PunicodexAuthenticityPlugin
      ios:
        pluginClass: PunicodexAuthenticityPlugin
