/**
 * New flagship domains (2026-07-20 batch) — canonical manifest.
 * Every field is hand-reviewed against ACCURACY.md doctrine: stress and
 * length marks only where the source attests them; circumflex where Greek
 * uses it; stacked macron+acute only on unambiguously long stressed η/ω.
 */
module.exports = [
  // ── Greek deities, heroes, and places ──
  {
    id: 'achilleus', ascii: 'achilleus', unicode: 'Achilleús', greek: 'Ἀχιλλεύς',
    pantheon: 'greek', tier: '1', tierLabel: 'Tier 1',
    domain: 'War, Glory, Rage',
    meaning: "Possibly 'grief of the people' (from ἄχος + λαός), or a pre-Greek name",
    sources: ['LSJ', 'Iliad', 'Beekes'],
    domainUnicode: 'achilleús.com', domainPunycode: 'xn--achilles-i3a.com',
    tagline: 'The Wrath and the Heel',
    rentalTier: 'A',
    colors: { primary: '#B22222', secondary: '#FFD700', glow: 'rgba(178,34,34,0.3)' },
    effect: { id: 'achilleusWrath', canvasId: 'wrath-canvas', motif: 'flame' },
    industry: ['sports', 'gaming', 'security'],
    ipa: '/a.kʰil.leús/',
  },
  {
    id: 'asklepios', ascii: 'asklepios', unicode: 'Asklēpiós', greek: 'Ἀσκληπιός',
    pantheon: 'greek', tier: '1', tierLabel: 'Tier 1',
    domain: 'Medicine, Healing, Renewal',
    meaning: 'Uncertain; possibly related to ἀσκαλαβώτης (lizard) or a pre-Greek healing root',
    sources: ['LSJ', 'Homeric Hymns', 'Pausanias'],
    domainUnicode: 'asklēpiós.com', domainPunycode: 'xn--asklpios-e5a.com',
    tagline: 'The Physician of the Gods',
    rentalTier: 'S',
    colors: { primary: '#2E8B57', secondary: '#F5E3A8', glow: 'rgba(46,139,87,0.3)' },
    effect: { id: 'asklepiosRenewal', canvasId: 'renewal-canvas', motif: 'light' },
    industry: ['health', 'pharma', 'wellness'],
    ipa: '/a.skliː.pi.ós/',
  },
  {
    id: 'atropos', ascii: 'atropos', unicode: 'Átropos', greek: 'Ἄτροπος',
    pantheon: 'greek', tier: '2', tierLabel: 'Tier 2',
    domain: 'Fate, Endings, Measure',
    meaning: "'Inflexible, unturnable' (from ἀ- + τρέπω)",
    sources: ['LSJ', 'Hesiod', 'Plato'],
    domainUnicode: 'átropos.com', domainPunycode: 'xn--atropos-f2a.com',
    tagline: 'She Who Cannot Be Turned',
    rentalTier: 'B',
    colors: { primary: '#4B0082', secondary: '#C0C0C0', glow: 'rgba(75,0,130,0.3)' },
    effect: { id: 'atroposThread', canvasId: 'thread-canvas', motif: 'time' },
    industry: ['insurance', 'analytics', 'legal'],
    ipa: '/á.tro.pos/',
  },
  {
    id: 'delos', ascii: 'delos', unicode: 'Dêlos', greek: 'Δῆλος',
    pantheon: 'greek-location', tier: '1', tierLabel: 'Tier 1',
    domain: 'Island, Sanctuary, Birth of Light',
    meaning: 'Possibly pre-Greek; later folk-etymologized as δῆλος, "visible, manifest"',
    sources: ['LSJ', 'Homeric Hymn to Apollo', 'Thucydides'],
    domainUnicode: 'dêlos.com', domainPunycode: 'xn--dlos-r3a.com',
    tagline: 'Where Apollo Was Born',
    rentalTier: 'A',
    colors: { primary: '#1E90FF', secondary: '#FFF8DC', glow: 'rgba(30,144,255,0.3)' },
    effect: { id: 'delosSanctuary', canvasId: 'sanctuary-canvas', motif: 'water' },
    industry: ['travel', 'heritage', 'hospitality'],
    ipa: '/dɛ̂ː.los/',
  },
  {
    id: 'drakon', ascii: 'drakon', unicode: 'Drákōn', greek: 'Δράκων',
    pantheon: 'greek', tier: '1', tierLabel: 'Tier 1',
    domain: 'Serpent, Guardian, Vigilance',
    meaning: "'The one who sees clearly' (from δέρκομαι, to see)",
    sources: ['LSJ', 'Beekes', 'Apollodorus'],
    domainUnicode: 'drákōn.com', domainPunycode: 'xn--drakn-4sa.com',
    tagline: 'The Sleepless Watcher',
    rentalTier: 'A',
    colors: { primary: '#006400', secondary: '#FFD700', glow: 'rgba(0,100,0,0.3)' },
    effect: { id: 'drakonVigil', canvasId: 'vigil-canvas', motif: 'flame' },
    industry: ['gaming', 'security', 'entertainment'],
    ipa: '/drá.kɔːn/',
  },
  {
    id: 'monokeros', ascii: 'monokeros', unicode: 'Monókerōs', greek: 'Μονόκερως',
    pantheon: 'greek', tier: '1', tierLabel: 'Tier 1',
    domain: 'Purity, Rarity, Wonder',
    meaning: "'Single-horned' (from μόνος + κέρας)",
    sources: ['LSJ', 'Ctesias', 'Pliny'],
    domainUnicode: 'monókerōs.com', domainPunycode: 'xn--monkros-93a.com',
    tagline: 'The Single Horn',
    rentalTier: 'A',
    colors: { primary: '#E6E6FA', secondary: '#D4AF37', glow: 'rgba(230,230,250,0.3)' },
    effect: { id: 'monokerosHorn', canvasId: 'horn-canvas', motif: 'light' },
    industry: ['venture', 'startups', 'luxury'],
    ipa: '/mo.nó.kɛː.rɔːs/',
  },
  {
    id: 'phanes', ascii: 'phanes', unicode: 'Phánēs', greek: 'Φάνης',
    pantheon: 'greek', tier: '1', tierLabel: 'Tier 1',
    domain: 'Light, Revelation, Firstborn',
    meaning: "'The one who appears, the Revealer' (from φαίνω)",
    sources: ['LSJ', 'Orphic Hymns', 'Derveni Papyrus'],
    domainUnicode: 'phánēs.com', domainPunycode: 'xn--phans-6la.com',
    tagline: 'The First Shining One',
    rentalTier: 'B',
    colors: { primary: '#FFD700', secondary: '#FFFACD', glow: 'rgba(255,215,0,0.3)' },
    effect: { id: 'phanesDawn', canvasId: 'dawn-canvas', motif: 'sun' },
    industry: ['media', 'publishing', 'ai'],
    ipa: '/pʰá.nɛːs/',
  },
  {
    id: 'pegasos', ascii: 'pegasos', unicode: 'Pḗgasos', greek: 'Πήγασος',
    pantheon: 'greek', tier: '1', tierLabel: 'Tier 1',
    domain: 'Flight, Inspiration, Freedom',
    meaning: 'Possibly from πηγή (spring) or a pre-Greek name',
    sources: ['LSJ', 'Hesiod', 'Pindar'],
    domainUnicode: 'pḗgasos.com', domainPunycode: 'xn--pgasos-jhb.com',
    tagline: 'The Winged Horse',
    rentalTier: 'S',
    colors: { primary: '#F0F8FF', secondary: '#D4AF37', glow: 'rgba(240,248,255,0.3)' },
    effect: { id: 'pegasosFlight', canvasId: 'flight-canvas', motif: 'stars' },
    industry: ['travel', 'logistics', 'venture'],
    ipa: '/pɛ̌ː.ɡa.sos/',
  },
  {
    id: 'seiren', ascii: 'seiren', unicode: 'Seirḗn', greek: 'Σειρήν',
    pantheon: 'greek', tier: '1', tierLabel: 'Tier 1',
    domain: 'Song, Allure, Threshold',
    meaning: 'Uncertain; possibly from σειρά (cord, rope) or a pre-Greek name',
    sources: ['LSJ', 'Odyssey', 'Apollonius Rhodius'],
    domainUnicode: 'seirḗn.com', domainPunycode: 'xn--seirn-fmb.com',
    tagline: 'The Song on the Rocks',
    rentalTier: 'A',
    colors: { primary: '#20B2AA', secondary: '#F5E3A8', glow: 'rgba(32,178,170,0.3)' },
    effect: { id: 'seirenSong', canvasId: 'song-canvas', motif: 'water' },
    industry: ['audio', 'music', 'podcasting'],
    ipa: '/sɛː.rɛ̌ːn/',
  },
  {
    id: 'troia', ascii: 'troia', unicode: 'Troíā', greek: 'Τροία',
    pantheon: 'greek-location', tier: '1', tierLabel: 'Tier 1',
    domain: 'Citadel, Siege, Memory',
    meaning: 'Pre-Greek place name; the city of Ilion',
    sources: ['LSJ', 'Iliad', 'Strabo'],
    domainUnicode: 'troíā.com', domainPunycode: 'xn--troa-2pa.com',
    tagline: 'The City That Fell Twice',
    rentalTier: 'A',
    colors: { primary: '#8B4513', secondary: '#FFD700', glow: 'rgba(139,69,19,0.3)' },
    effect: { id: 'troiaSiege', canvasId: 'siege-canvas', motif: 'flame' },
    industry: ['security', 'gaming', 'heritage'],
    ipa: '/troí.aː/',
  },
  {
    id: 'tyche', ascii: 'tyche', unicode: 'Týchē', greek: 'Τύχη',
    pantheon: 'greek', tier: '1', tierLabel: 'Tier 1',
    domain: 'Fortune, Chance, Turning',
    meaning: "'That which happens' (from τυγχάνω)",
    sources: ['LSJ', 'Pausanias', 'Polybius'],
    domainUnicode: 'týchē.com', domainPunycode: 'xn--tych-9qa.com',
    tagline: 'The Turning of the Wheel',
    rentalTier: 'S',
    colors: { primary: '#9370DB', secondary: '#FFD700', glow: 'rgba(147,112,219,0.3)' },
    effect: { id: 'tycheWheel', canvasId: 'wheel-canvas', motif: 'stars' },
    industry: ['gaming', 'fintech', 'lottery'],
    ipa: '/tý.kʰɛː/',
  },

  // ── Roman deities ──
  {
    id: 'diana', ascii: 'diana', unicode: 'Diāna', greek: 'Diāna',
    pantheon: 'roman', tier: '2', tierLabel: 'Tier 2',
    domain: 'Moon, Hunt, Wilderness',
    meaning: "'The bright one, goddess' (from the root *dyēu-, to shine)",
    sources: ['Lewis & Short', 'Varro', 'Horace'],
    domainUnicode: 'diāna.com', domainPunycode: 'xn--diana-hpa.com',
    tagline: 'The Huntress of the Moon',
    rentalTier: 'S',
    colors: { primary: '#C0C0C0', secondary: '#191970', glow: 'rgba(192,192,192,0.3)' },
    effect: { id: 'dianaMoon', canvasId: 'moon-canvas', motif: 'stars' },
    industry: ['outdoor', 'optics', 'luxury'],
    ipa: '/diˈaː.na/',
  },
  {
    id: 'ianus', ascii: 'ianus', unicode: 'Iānus', greek: 'Iānus',
    pantheon: 'roman', tier: '2', tierLabel: 'Tier 2',
    domain: 'Beginnings, Doors, Transitions',
    meaning: "'Passage, arched door' (from ianua)",
    sources: ['Lewis & Short', 'Ovid', 'Macrobius'],
    domainUnicode: 'iānus.com', domainPunycode: 'xn--ianus-l2a.com',
    tagline: 'The God of Two Faces',
    rentalTier: 'A',
    colors: { primary: '#B8860B', secondary: '#F0F0F0', glow: 'rgba(184,134,11,0.3)' },
    effect: { id: 'ianusGates', canvasId: 'gates-canvas', motif: 'time' },
    industry: ['fintech', 'security', 'infrastructure'],
    ipa: '/ˈjaː.nus/',
  },
  {
    id: 'iuno', ascii: 'iuno', unicode: 'Iūnō', greek: 'Iūnō',
    pantheon: 'roman', tier: '2', tierLabel: 'Tier 2',
    domain: 'Queenship, Marriage, Sky',
    meaning: 'From the same root as Iuppiter, the bright sky',
    sources: ['Lewis & Short', 'Virgil', 'Ovid'],
    domainUnicode: 'iūnō.com', domainPunycode: 'xn--iun-zpa.com',
    tagline: 'The Queen of Heaven',
    rentalTier: 'A',
    colors: { primary: '#4169E1', secondary: '#FFD700', glow: 'rgba(65,105,225,0.3)' },
    effect: { id: 'iunoPeacock', canvasId: 'peacock-canvas', motif: 'stars' },
    industry: ['luxury', 'bridal', 'beauty'],
    ipa: '/ˈjuː.noː/',
  },
  {
    id: 'iuppiter', ascii: 'iuppiter', unicode: 'Iūppiter', greek: 'Iūppiter',
    pantheon: 'roman', tier: '2', tierLabel: 'Tier 2',
    domain: 'Sky, Thunder, Sovereignty',
    meaning: "'Sky-father' (from *Dyēu-pater)",
    sources: ['Lewis & Short', 'Ennius', 'Virgil'],
    domainUnicode: 'iūppiter.com', domainPunycode: 'xn--iuppiter-93a.com',
    tagline: 'The Father of the Sky',
    rentalTier: 'S',
    colors: { primary: '#FFD700', secondary: '#1E90FF', glow: 'rgba(255,215,0,0.3)' },
    effect: { id: 'iuppiterThunder', canvasId: 'thunder-canvas', motif: 'storm' },
    industry: ['finance', 'cloud', 'energy'],
    ipa: '/ˈjuːp.pi.ter/',
  },
  {
    id: 'neptunus', ascii: 'neptunus', unicode: 'Neptūnus', greek: 'Neptūnus',
    pantheon: 'roman', tier: '2', tierLabel: 'Tier 2',
    domain: 'Sea, Horses, Earthquake',
    meaning: 'Possibly related to nepos (descendant) or a pre-Roman water root',
    sources: ['Lewis & Short', 'Varro', 'Virgil'],
    domainUnicode: 'neptūnus.com', domainPunycode: 'xn--neptnus-c7a.com',
    tagline: 'The Lord of Waters',
    rentalTier: 'S',
    colors: { primary: '#006994', secondary: '#F0F8FF', glow: 'rgba(0,105,148,0.3)' },
    effect: { id: 'neptunusTide', canvasId: 'tide-canvas', motif: 'water' },
    industry: ['marine', 'travel', 'energy'],
    ipa: '/nepˈtuː.nus/',
  },
  {
    id: 'vulcanus', ascii: 'vulcanus', unicode: 'Vulcānus', greek: 'Vulcānus',
    pantheon: 'roman', tier: '2', tierLabel: 'Tier 2',
    domain: 'Fire, Forge, Craft',
    meaning: 'Possibly from fulgere (to flash) or a pre-Roman fire root',
    sources: ['Lewis & Short', 'Virgil', 'Ovid'],
    domainUnicode: 'vulcānus.com', domainPunycode: 'xn--vulcanus-9ib.com',
    tagline: 'The Smith of the Gods',
    rentalTier: 'A',
    colors: { primary: '#FF4500', secondary: '#696969', glow: 'rgba(255,69,0,0.3)' },
    effect: { id: 'vulcanusForge', canvasId: 'forge-canvas', motif: 'flame' },
    industry: ['manufacturing', 'tools', 'engineering'],
    ipa: '/vulˈkaː.nus/',
  },
];

// ── Egyptian deities ──
module.exports.push(
  {
    id: 'anubis', ascii: 'anubis', unicode: 'ꜣnpw', greek: '—',
    pantheon: 'egyptian', tier: '2', tierLabel: 'Tier 2',
    domain: 'Embalming, Passage, Vigil',
    meaning: "'Royal child' (from jnpw); Greek Ἄνουβις",
    sources: ['Faulkner', 'Gardiner', 'Pyramid Texts'],
    domainUnicode: 'ꜣnpw.com', domainPunycode: 'xn--npw-c4a.com',
    tagline: 'He Who Is Upon His Mountain',
    rentalTier: 'A',
    colors: { primary: '#1a1a2e', secondary: '#D4AF37', glow: 'rgba(26,26,46,0.4)' },
    effect: { id: 'anubisVigil', canvasId: 'vigil-canvas-2', motif: 'void' },
    industry: ['security', 'memorial', 'insurance'],
    ipa: '/jaːˈnaː.paw/',
    originalScript: {
      script: '𓇋𓈖𓊊𓅱', scriptName: 'Hieroglyphs',
      provenance: {
        original: '𓇋𓈖𓊊𓅱', transliteration: 'jnpw',
        steps: [
          'M17 reed (𓇋) = j',
          'N35 ripple of water (𓈖) = n',
          'O31 mouth and basket (𓊊) = p',
          'G43 quail chick (𓅱) = w',
          'jnpw is the jackal god of the necropolis, later Greek Ἄνουβις (Anubis)',
        ],
        sources: ['Faulkner', 'Allen, Middle Egyptian', 'Gardiner'],
      },
    },
  },
  {
    id: 'steh', ascii: 'steh', unicode: 'Stḫ', greek: '—',
    pantheon: 'egyptian', tier: '2', tierLabel: 'Tier 2',
    domain: 'Desert, Storm, Strength',
    meaning: 'The god Seth/Setekh; etymology disputed, possibly "the one who separates"',
    sources: ['Faulkner', 'Gardiner', 'Te Velde'],
    domainUnicode: 'stḫ.com', domainPunycode: 'xn--sth-z8a.com',
    tagline: 'The Lord of the Red Land',
    rentalTier: 'B',
    colors: { primary: '#8B0000', secondary: '#D4AF37', glow: 'rgba(139,0,0,0.3)' },
    effect: { id: 'stehDesert', canvasId: 'desert-canvas-2', motif: 'storm' },
    industry: ['energy', 'outdoor', 'sports'],
    ipa: '/ˈsɛː.tɛx/',
    originalScript: {
      script: '𓋴𓏏𓐍', scriptName: 'Hieroglyphs',
      provenance: {
        original: '𓋴𓏏𓐍', transliteration: 'stḫ',
        steps: [
          'S29 folded cloth (𓋴) = s',
          'X1 bread loaf (𓏏) = t',
          'V28 wick of twisted flax (𓐍) = ḫ (cheth)',
          'stḫ is the god of the desert and foreign lands, Greek Σήθ (Seth)',
        ],
        sources: ['Faulkner', 'Allen, Middle Egyptian', 'Gardiner'],
      },
    },
  },
  {
    id: 'seshat', ascii: 'seshat', unicode: 'Sšꜣt', greek: '—',
    pantheon: 'egyptian', tier: '2', tierLabel: 'Tier 2',
    domain: 'Writing, Wisdom, Measure',
    meaning: "'The female scribe' (from sš, to write)",
    sources: ['Faulkner', 'Gardiner', 'Wilkinson'],
    domainUnicode: 'sšꜣt.com', domainPunycode: 'xn--sat-v6a.com',
    tagline: 'The Mistress of the Hall of Books',
    rentalTier: 'A',
    colors: { primary: '#2F4F4F', secondary: '#D4AF37', glow: 'rgba(47,79,79,0.3)' },
    effect: { id: 'seshatInk', canvasId: 'ink-canvas', motif: 'stars' },
    industry: ['publishing', 'ai', 'education'],
    ipa: '/ˈsɛː.ʃat/',
    originalScript: {
      script: '𓋴𓈙𓄿𓏏', scriptName: 'Hieroglyphs',
      provenance: {
        original: '𓋴𓈙𓄿𓏏', transliteration: 'sšꜣt',
        steps: [
          'S29 folded cloth (𓋴) = s',
          'Q1 hillside (𓈙) = š',
          'G1 vulture (𓄿) = ꜣ',
          'X1 bread loaf (𓏏) = t',
          'sšꜣt is the goddess of writing and reckoning, "the female scribe"',
        ],
        sources: ['Faulkner', 'Allen, Middle Egyptian', 'Gardiner'],
      },
    },
  },
  {
    id: 'hp', ascii: 'hp', unicode: 'Ḥp', greek: '—',
    pantheon: 'egyptian', tier: '2', tierLabel: 'Tier 2',
    domain: 'Nile, Inundation, Abundance',
    meaning: 'The Nile flood god Hapi; from ḥꜥpj',
    sources: ['Faulkner', 'Gardiner', 'Bonneau'],
    domainUnicode: 'ḥp.com', domainPunycode: 'xn--hp-zfa.com',
    tagline: 'The Bringer of the Flood',
    rentalTier: 'A',
    colors: { primary: '#1E90FF', secondary: '#3CB371', glow: 'rgba(30,144,255,0.3)' },
    effect: { id: 'hpFlood', canvasId: 'flood-canvas', motif: 'water' },
    industry: ['agriculture', 'water', 'food'],
    ipa: '/ˈħaː.pi/',
    originalScript: {
      script: '𓎛𓊪', scriptName: 'Hieroglyphs',
      provenance: {
        original: '𓎛𓊪', transliteration: 'ḥp',
        steps: [
          '𓎛 twisted wick of plant fibre = ḥ',
          'Q3 basket (𓊪) = p',
          'ḥp is the consonantal skeleton of ḥꜥpj, the Nile inundation god',
        ],
        sources: ['Faulkner', 'Gardiner'],
      },
    },
  }
);

// ── Vedic / Hindu deities ──
module.exports.push(
  {
    id: 'amsa', ascii: 'amsa', unicode: 'Aṃśa', greek: '—',
    pantheon: 'sanskrit', tier: '2', tierLabel: 'Tier 2',
    domain: 'Share, Portion, Light',
    meaning: "'Portion, share' (from aṃśa), one of the twelve Ādityas",
    sources: ['Rigveda', 'Monier-Williams', 'Macdonell'],
    domainUnicode: 'aṃśa.com', domainPunycode: 'xn--aaa-4pa.com',
    tagline: 'The Portion of the Sun',
    rentalTier: 'B',
    colors: { primary: '#FF8C00', secondary: '#FFD700', glow: 'rgba(255,140,0,0.3)' },
    effect: { id: 'amsaRay', canvasId: 'ray-canvas', motif: 'sun' },
    industry: ['fintech', 'energy', 'saas'],
    ipa: '/ɐmˈɕɐ/',
    originalScript: {
      script: 'अंश', scriptName: 'Devanagari',
      provenance: {
        original: 'अंश', transliteration: 'aṃśa',
        steps: [
          'अ = a',
          'ं anusvāra = ṃ (nasal)',
          'श = śa',
          'aṃśa is one of the Ādityas, a solar portion or ray',
        ],
        sources: ['Rigveda', 'Monier-Williams'],
      },
    },
  },
  {
    id: 'daksa', ascii: 'daksa', unicode: 'Dakṣa', greek: '—',
    pantheon: 'sanskrit', tier: '2', tierLabel: 'Tier 2',
    domain: 'Skill, Creation, Order',
    meaning: "'The skilled, the able' (from dakṣa), a Prajāpati",
    sources: ['Rigveda', 'Mahabharata', 'Monier-Williams'],
    domainUnicode: 'dakṣa.com', domainPunycode: 'xn--daksa-j3a.com',
    tagline: 'The Father of Order',
    rentalTier: 'B',
    colors: { primary: '#8B4513', secondary: '#FFD700', glow: 'rgba(139,69,19,0.3)' },
    effect: { id: 'daksaCraft', canvasId: 'craft-canvas', motif: 'stars' },
    industry: ['education', 'saas', 'consulting'],
    ipa: '/ˈd̪ɐk.ʂɐ/',
    originalScript: {
      script: 'दक्ष', scriptName: 'Devanagari',
      provenance: {
        original: 'दक्ष', transliteration: 'dakṣa',
        steps: ['द = da', 'क = ka', 'ष = ṣa (retroflex)', 'dakṣa is the Prajāpati of ritual order and father of many gods'],
        sources: ['Rigveda', 'Monier-Williams'],
      },
    },
  },
  {
    id: 'dhatr', ascii: 'dhatr', unicode: 'Dhātṛ', greek: '—',
    pantheon: 'sanskrit', tier: '2', tierLabel: 'Tier 2',
    domain: 'Creation, Ordinance, Support',
    meaning: "'The Ordainer, the Establisher' (from dhā, to place), an Āditya",
    sources: ['Rigveda', 'Monier-Williams', 'Macdonell'],
    domainUnicode: 'dhātṛ.com', domainPunycode: 'xn--dhat-h1a.com',
    tagline: 'The One Who Sets the World',
    rentalTier: 'B',
    colors: { primary: '#DAA520', secondary: '#FFF8DC', glow: 'rgba(218,165,32,0.3)' },
    effect: { id: 'dhatrOrder', canvasId: 'order-canvas', motif: 'sun' },
    industry: ['cloud', 'infrastructure', 'governance'],
    ipa: '/d̪ʱɑːˈt̪r̩/',
    originalScript: {
      script: 'धातृ', scriptName: 'Devanagari',
      provenance: {
        original: 'धातृ', transliteration: 'dhātṛ',
        steps: ['ध = dha', 'आ = ā (long)', 'तृ = tṛ (vocalic ṛ)', 'dhātṛ is the Āditya of creation and ordinance, "the Establisher"'],
        sources: ['Rigveda', 'Monier-Williams'],
      },
    },
  },
);

module.exports.push(
  {
    id: 'pusan', ascii: 'pusan', unicode: 'Pūṣan', greek: '—',
    pantheon: 'sanskrit', tier: '2', tierLabel: 'Tier 2',
    domain: 'Journeys, Nourishment, Roads',
    meaning: "'The Nourisher' (from puṣ, to thrive), Vedic solar guide of roads",
    sources: ['Rigveda', 'Monier-Williams', 'Macdonell'],
    domainUnicode: 'pūṣan.com', domainPunycode: 'xn--psan-3ya.com',
    tagline: 'The Guide of All Roads',
    rentalTier: 'B',
    colors: { primary: '#FF7F50', secondary: '#FFFACD', glow: 'rgba(255,127,80,0.3)' },
    effect: { id: 'pusanRoad', canvasId: 'road-canvas', motif: 'sun' },
    industry: ['logistics', 'travel', 'food'],
    ipa: '/ˈpuː.ʂɐn/',
    originalScript: {
      script: 'पूषन्', scriptName: 'Devanagari',
      provenance: {
        original: 'पूषन्', transliteration: 'pūṣan',
        steps: ['प = pa', 'ू = ū (long)', 'ष = ṣa', 'न् = na', 'pūṣan is the Vedic solar god who protects travelers and herds'],
        sources: ['Rigveda', 'Monier-Williams'],
      },
    },
  },
  {
    id: 'tvastr', ascii: 'tvastr', unicode: 'Tvaṣṭṛ', greek: '—',
    pantheon: 'sanskrit', tier: '2', tierLabel: 'Tier 2',
    domain: 'Craft, Making, Form',
    meaning: "'The Fashioner, the Maker' (from tvaṣ, to form), the divine craftsman",
    sources: ['Rigveda', 'Monier-Williams', 'Macdonell'],
    domainUnicode: 'tvaṣṭṛ.com', domainPunycode: 'xn--tvastr-55a.com',
    tagline: 'The Architect of the Gods',
    rentalTier: 'B',
    colors: { primary: '#CD853F', secondary: '#F5E3A8', glow: 'rgba(205,133,63,0.3)' },
    effect: { id: 'tvastrForge', canvasId: 'forge-canvas-2', motif: 'flame' },
    industry: ['engineering', 'design', 'manufacturing'],
    ipa: '/ˈt̪ʋɐʂ.ʈr̩/',
    originalScript: {
      script: 'त्वष्टृ', scriptName: 'Devanagari',
      provenance: {
        original: 'त्वष्टृ', transliteration: 'tvaṣṭṛ',
        steps: ['त्व = tva', 'ष = ṣa', 'टृ = ṭṛ (vocalic ṛ)', 'tvaṣṭṛ is the divine craftsman who shapes the forms of the gods'],
        sources: ['Rigveda', 'Monier-Williams'],
      },
    },
  }
);

module.exports.push(
  {
    id: 'fuxi', ascii: 'fuxi', unicode: 'Fúxī', greek: '—',
    pantheon: 'chinese', tier: '2', tierLabel: 'Tier 2',
    domain: 'Creation, Writing, Order',
    meaning: "'Crouching breath' (伏羲), the culture hero who gave writing and the trigrams",
    sources: ['Shiji', 'Huainanzi', 'Legge'],
    domainUnicode: 'fúxī.com', domainPunycode: 'xn--fuxi-2pa.com',
    tagline: 'The First Teacher',
    rentalTier: 'A',
    colors: { primary: '#228B22', secondary: '#FFD700', glow: 'rgba(34,139,34,0.3)' },
    effect: { id: 'fuxiTrigrams', canvasId: 'trigrams-canvas', motif: 'tree' },
    industry: ['education', 'ai', 'publishing'],
    ipa: '/fu˧˥ ɕi˥/',
  },
  {
    id: 'guanyin', ascii: 'guanyin', unicode: 'Guānyīn', greek: '—',
    pantheon: 'chinese', tier: '2', tierLabel: 'Tier 2',
    domain: 'Compassion, Mercy, Hearing',
    meaning: "'She who hears the cries of the world' (觀音, Guānshìyīn)",
    sources: ['Lotus Sutra', 'Zurcher', 'Watson'],
    domainUnicode: 'guānyīn.com', domainPunycode: 'xn--guanyin-90a.com',
    tagline: 'She Who Hears the World',
    rentalTier: 'S',
    colors: { primary: '#F5F5F5', secondary: '#2E8B57', glow: 'rgba(245,245,245,0.3)' },
    effect: { id: 'guanyinLotus', canvasId: 'lotus-canvas', motif: 'water' },
    industry: ['wellness', 'health', 'nonprofit'],
    ipa: '/kwan˥ ɥin˥/',
  },
  {
    id: 'mengpo', ascii: 'mengpo', unicode: 'Méngpó', greek: '—',
    pantheon: 'chinese', tier: '2', tierLabel: 'Tier 2',
    domain: 'Forgetting, Passage, Tea',
    meaning: "'Old Lady Meng' (孟婆), the goddess who brews the tea of forgetfulness",
    sources: ['Journey to the West', 'Chinese folk religion', 'Werner'],
    domainUnicode: 'méngpó.com', domainPunycode: 'xn--mengpo-i3a.com',
    tagline: 'The Tea at the Bridge',
    rentalTier: 'B',
    colors: { primary: '#8B4513', secondary: '#D4AF37', glow: 'rgba(139,69,19,0.3)' },
    effect: { id: 'mengpoTea', canvasId: 'tea-canvas', motif: 'void' },
    industry: ['tea', 'wellness', 'hospitality'],
    ipa: '/məŋ˥˩ pʰwo˧˥/',
  },
  {
    id: 'nuwa', ascii: 'nuwa', unicode: 'Nǚwā', greek: '—',
    pantheon: 'chinese', tier: '2', tierLabel: 'Tier 2',
    domain: 'Creation, Mending, Motherhood',
    meaning: "'Womanly frog' or from an old creation root (女媧), the mender of the sky",
    sources: ['Shanhaijing', 'Huainanzi', 'Birrell'],
    domainUnicode: 'nǚwā.com', domainPunycode: 'xn--nuwa-3pa.com',
    tagline: 'The Mender of the Sky',
    rentalTier: 'A',
    colors: { primary: '#20B2AA', secondary: '#FFD700', glow: 'rgba(32,178,170,0.3)' },
    effect: { id: 'nuwaStones', canvasId: 'stones-canvas', motif: 'stars' },
    industry: ['sustainability', 'materials', 'education'],
    ipa: '/ny˨˩˦ wa˥/',
  },
  {
    id: 'pangu', ascii: 'pangu', unicode: 'Pángǔ', greek: '—',
    pantheon: 'chinese', tier: '2', tierLabel: 'Tier 2',
    domain: 'Creation, Separation, Foundation',
    meaning: "'Coiled antiquity' (盤古), the giant who split heaven from earth",
    sources: ['Sanguozhi', 'Xu Zheng', 'Birrell'],
    domainUnicode: 'pángǔ.com', domainPunycode: 'xn--pang-0pa.com',
    tagline: 'The Giant Between Heaven and Earth',
    rentalTier: 'A',
    colors: { primary: '#696969', secondary: '#FFD700', glow: 'rgba(105,105,105,0.3)' },
    effect: { id: 'panguSplit', canvasId: 'split-canvas', motif: 'mountain' },
    industry: ['cloud', 'infrastructure', 'construction'],
    ipa: '/pʰa˧˥ ku˨˩˦/',
  },
  {
    id: 'yanluo', ascii: 'yanluo', unicode: 'Yánluó', greek: '—',
    pantheon: 'chinese', tier: '2', tierLabel: 'Tier 2',
    domain: 'Judgment, Underworld, Order',
    meaning: "'King Yan' (閻羅, from Yama), the judge of the dead",
    sources: ['Fengshen Yanyi', 'Chinese Buddhist canon', 'Teiser'],
    domainUnicode: 'yánluó.com', domainPunycode: 'xn--yanluo-8pa.com',
    tagline: 'The Judge Below',
    rentalTier: 'A',
    colors: { primary: '#8B0000', secondary: '#D4AF37', glow: 'rgba(139,0,0,0.35)' },
    effect: { id: 'yanluoJudgment', canvasId: 'judgment-canvas', motif: 'void' },
    industry: ['gaming', 'legal', 'entertainment'],
    ipa: '/jɛn˧˥ lwo˧˥/',
  }
);

module.exports.push(
  {
    id: 'hokkaido', ascii: 'hokkaido', unicode: 'Hokkaidō', greek: '—',
    pantheon: 'japanese', tier: '2', tierLabel: 'Tier 2',
    domain: 'North, Snow, Frontier',
    meaning: "'Northern sea road' (北海道)",
    sources: ['Nihon Shoki', 'Kokugo dictionaries', 'JET'],
    domainUnicode: 'hokkaidō.com', domainPunycode: 'xn--hokkaido-9pa.com',
    tagline: 'The Northern Road',
    rentalTier: 'A',
    colors: { primary: '#B0E0E6', secondary: '#1E90FF', glow: 'rgba(176,224,230,0.3)' },
    effect: { id: 'hokkaidoSnow', canvasId: 'snow-canvas', motif: 'mountain' },
    industry: ['travel', 'winter-sports', 'food'],
    ipa: '/hok.kai.doː/',
  },
  {
    id: 'honshu', ascii: 'honshu', unicode: 'Honshū', greek: '—',
    pantheon: 'japanese', tier: '2', tierLabel: 'Tier 2',
    domain: 'Center, Mainland, Heart',
    meaning: "'Main island' (本州)",
    sources: ['Nihon Shoki', 'Kokugo dictionaries'],
    domainUnicode: 'honshū.com', domainPunycode: 'xn--honshu-7pa.com',
    tagline: 'The Heart of the Islands',
    rentalTier: 'B',
    colors: { primary: '#2E8B57', secondary: '#F5E3A8', glow: 'rgba(46,139,87,0.3)' },
    effect: { id: 'honshuPeak', canvasId: 'peak-canvas', motif: 'mountain' },
    industry: ['travel', 'real-estate', 'logistics'],
    ipa: '/hon.ɕuː/',
  },
  {
    id: 'kyushu', ascii: 'kyushu', unicode: 'Kyūshū', greek: '—',
    pantheon: 'japanese', tier: '2', tierLabel: 'Tier 2',
    domain: 'South, Volcanoes, Origins',
    meaning: "'Nine provinces' (九州)",
    sources: ['Nihon Shoki', 'Kokugo dictionaries'],
    domainUnicode: 'kyūshū.com', domainPunycode: 'xn--kyushu-3pa.com',
    tagline: 'The Nine Provinces',
    rentalTier: 'B',
    colors: { primary: '#FF7F50', secondary: '#2F4F4F', glow: 'rgba(255,127,80,0.3)' },
    effect: { id: 'kyushuEmber', canvasId: 'ember-canvas', motif: 'mountain' },
    industry: ['travel', 'food', 'energy'],
    ipa: '/kjɯː.ɕɯː/',
  }
);

module.exports.push(
  {
    id: 'tezcatlipoca', ascii: 'tezcatlipoca', unicode: 'Tezcatlipōca', greek: '—',
    pantheon: 'nahuatl', tier: '2', tierLabel: 'Tier 2',
    domain: 'Night, Sorcery, Kingship',
    meaning: "'Smoking Mirror' (tezcatl + pōca), the Aztec lord of night and fate",
    sources: ['Florentine Codex', 'Sahagún', 'León-Portilla'],
    domainUnicode: 'tezcatlipōca.com', domainPunycode: 'xn--tezcatlipoca-90a.com',
    tagline: 'The Smoking Mirror',
    rentalTier: 'A',
    colors: { primary: '#191970', secondary: '#D4AF37', glow: 'rgba(25,25,112,0.4)' },
    effect: { id: 'tezcatlipocaMirror', canvasId: 'mirror-canvas', motif: 'void' },
    industry: ['gaming', 'media', 'entertainment'],
    ipa: '/teːs.kat.liˈpoː.ka/',
  },
  {
    id: 'xolotl', ascii: 'xolotl', unicode: 'Xōlōtl', greek: '—',
    pantheon: 'nahuatl', tier: '2', tierLabel: 'Tier 2',
    domain: 'Twins, Guides, Transformation',
    meaning: "'Dog, twin' (xōlōtl), the dog-headed guide of the dead and of the sun",
    sources: ['Florentine Codex', 'Sahagún', 'León-Portilla'],
    domainUnicode: 'xōlōtl.com', domainPunycode: 'xn--xlotl-w6a.com',
    tagline: 'The Twin Who Leads the Sun',
    rentalTier: 'B',
    colors: { primary: '#8B4513', secondary: '#FFD700', glow: 'rgba(139,69,19,0.3)' },
    effect: { id: 'xolotlGuide', canvasId: 'guide-canvas', motif: 'void' },
    industry: ['pets', 'gaming', 'branding'],
    ipa: '/ˈʃoː.loːtɬ/',
  },
  {
    id: 'ogun', ascii: 'ogun', unicode: 'Ògún', greek: '—',
    pantheon: 'yoruba', tier: '2', tierLabel: 'Tier 2',
    domain: 'Iron, War, Labor',
    meaning: 'The orisha of iron and war; from an old root for medicine/skill',
    sources: ['Abimbola', 'Verger', 'Bascom'],
    domainUnicode: 'ògún.com', domainPunycode: 'xn--ogun-cpa.com',
    tagline: 'The Master of Iron',
    rentalTier: 'A',
    colors: { primary: '#2F4F4F', secondary: '#FF4500', glow: 'rgba(47,79,79,0.4)' },
    effect: { id: 'ogunIron', canvasId: 'iron-canvas', motif: 'flame' },
    industry: ['manufacturing', 'defense', 'tools'],
    ipa: '/ò.gṹ/',
  },
  {
    id: 'tumatauenga', ascii: 'tumatauenga', unicode: 'Tūmatauenga', greek: '—',
    pantheon: 'polynesian', tier: '2', tierLabel: 'Tier 2',
    domain: 'War, Humanity, Strength',
    meaning: "'The man of furious face' (tū + mata + ēngā), god of war and of humankind",
    sources: ['Grey, Polynesian Mythology', 'Best', 'Tregear'],
    domainUnicode: 'tūmatauenga.com', domainPunycode: 'xn--tumatauenga-5xa.com',
    tagline: 'The Face of Battle',
    rentalTier: 'B',
    colors: { primary: '#8B0000', secondary: '#F5E3A8', glow: 'rgba(139,0,0,0.3)' },
    effect: { id: 'tumatauengaHaka', canvasId: 'haka-canvas', motif: 'storm' },
    industry: ['sports', 'fitness', 'defense'],
    ipa: '/tuː.ma.taʊ.ˈe.ŋa/',
  }
);
