/**
 * 2026-07-20 third-wave flagship manifest (15 domains).
 * Philology reviewed with the user: Kārttikeya (IAST, e unmarked) confirmed;
 * Xiuhtecuhtli kept ASCII as domain (display Xiuhtēcuhtli); Ọba/Ọrun are
 * domain-maximal forms (tone marks unregistrable).
 */
module.exports = [
  {
    id: 'guandi', ascii: 'guandi', unicode: 'Guāndì', greek: '關帝',
    pantheon: 'chinese', tier: '1', tierLabel: 'Tier 1',
    domain: 'War, Loyalty, Protection',
    meaning: '"Emperor Guan" — the deified general Guān Yǔ, god of war, loyalty, and righteousness',
    sources: ['Sanguozhi', 'Chinese folk religion', 'Birrell', 'Chinese folklore', 'Fengshen Yanyi', 'Cambridge'],
    domainUnicode: 'guāndì.com', domainPunycode: 'xn--guand-eua.com',
    tagline: 'The General Who Became a God',
    rentalTier: 'A',
    colors: { primary: '#7A1F1F', secondary: '#C9A227', glow: 'rgba(122,31,31,0.3)' },
    effect: { id: 'guandiHalberd', canvasId: 'halberd-canvas', motif: 'flame' },
    industry: ['defense', 'leadership', 'legal-justice'],
  },
  {
    id: 'gauri', ascii: 'gauri', unicode: 'Gaurī', greek: 'गौरी',
    pantheon: 'sanskrit', tier: '1', tierLabel: 'Tier 1',
    domain: 'Motherhood, Beauty, Austerity',
    meaning: '"The Golden One" — the radiant form of the Great Goddess, mother of the universe',
    sources: ['Puranas', 'Shiva Purana', 'Devi Mahatmya', 'Monier-Williams', 'MW', 'Cambridge'],
    domainUnicode: 'gaurī.com', domainPunycode: 'xn--gaur-rxa.com',
    tagline: 'The Golden Mother',
    rentalTier: 'A',
    colors: { primary: '#B8860B', secondary: '#6B4E12', glow: 'rgba(184,134,11,0.3)' },
    effect: { id: 'gauriMandala', canvasId: 'mandala-canvas', motif: 'sun' },
    industry: ['femtech', 'wedding-family', 'beauty-fashion'],
  },
  {
    id: 'sani', ascii: 'sani', unicode: 'Śani', greek: 'शनि',
    pantheon: 'sanskrit', tier: '1', tierLabel: 'Tier 1',
    domain: 'Justice, Saturn, Karma',
    meaning: '"The Slow One" — Saturn as the lord of karma, justice, discipline, and time',
    sources: ['Puranas', 'Mahabharata', 'Monier-Williams', 'MW', 'Brāhmaṇas', 'Cambridge'],
    domainUnicode: 'śani.com', domainPunycode: 'xn--ani-9qa.com',
    tagline: 'The Slow Reckoning',
    rentalTier: 'B',
    colors: { primary: '#2E3A59', secondary: '#8C93A8', glow: 'rgba(46,58,89,0.35)' },
    effect: { id: 'saniRings', canvasId: 'rings-canvas', motif: 'stars' },
    industry: ['legal-justice', 'horology', 'insurance'],
  },
  {
    id: 'orun', ascii: 'orun', unicode: 'Ọrun', greek: '—',
    pantheon: 'yoruba', tier: '1', tierLabel: 'Tier 1',
    domain: 'Sky, Heaven, Destiny',
    meaning: '"Heaven" — the sky-realm of the orisha, the divine order above the world',
    sources: ['Idowu', 'Bascom', 'Abraham', 'Folklore', 'Cambridge', 'Oxford'],
    domainUnicode: 'ọrun.com', domainPunycode: 'xn--run-9ua.com',
    tagline: 'The Heaven Above the Heavens',
    rentalTier: 'B',
    colors: { primary: '#1E3A5F', secondary: '#C9A227', glow: 'rgba(30,58,95,0.35)' },
    effect: { id: 'orunVault', canvasId: 'vault-canvas', motif: 'stars' },
    industry: ['faith', 'philosophy-ethics', 'education'],
  },
  {
    id: 'xiuhtecuhtli', ascii: 'xiuhtecuhtli', unicode: 'Xiuhtēcuhtli', greek: '—',
    pantheon: 'nahuatl', tier: '1', tierLabel: 'Tier 1',
    domain: 'Fire, Time, Hearth',
    meaning: '"Fire Lord" — the Aztec fire god, lord of the hearth and of the year',
    sources: ['Florentine Codex', 'Sahagún', 'Karttunen', 'Nahuatl dictionary', 'Cambridge'],
    domainUnicode: 'xiuhtecuhtli.com', domainPunycode: 'xiuhtecuhtli.com',
    tagline: 'The First Fire',
    rentalTier: 'B',
    colors: { primary: '#8B3A1E', secondary: '#C98A27', glow: 'rgba(139,58,30,0.3)' },
    effect: { id: 'xiuhtecuhtliEmber', canvasId: 'ember-canvas', motif: 'flame' },
    industry: ['thermal-energy', 'manufacturing-craft', 'faith'],
  },
  {
    id: 'pluto', ascii: 'pluto', unicode: 'Plūtō', greek: '—',
    pantheon: 'roman', tier: '1', tierLabel: 'Tier 1',
    domain: 'Underworld, Wealth, the Dead',
    meaning: '"The Rich One" — Roman lord of the underworld and of buried wealth',
    sources: ['Lewis & Short', 'Varro', 'Cicero', 'Ovid', 'Macrobius', 'Cambridge'],
    domainUnicode: 'plūtō.com', domainPunycode: 'xn--plt-2ua.com',
    tagline: 'The Rich One Below',
    rentalTier: 'A',
    colors: { primary: '#3A3F4A', secondary: '#B08D2E', glow: 'rgba(58,63,74,0.35)' },
    effect: { id: 'plutoVault', canvasId: 'underworld-canvas', motif: 'void' },
    industry: ['mining-resources', 'finance-commerce', 'funerary-memorial'],
  },
  {
    id: 'ceres', ascii: 'ceres', unicode: 'Cerēs', greek: '—',
    pantheon: 'roman', tier: '1', tierLabel: 'Tier 1',
    domain: 'Agriculture, Grain, Harvest',
    meaning: 'Goddess of grain and growth — the source of the word "cereal"',
    sources: ['Lewis & Short', 'Varro', 'Ovid', 'Cicero', 'Horace', 'Cambridge'],
    domainUnicode: 'cerēs.com', domainPunycode: 'xn--cers-g8a.com',
    tagline: 'The Grain Mother',
    rentalTier: 'A',
    colors: { primary: '#9C7A1E', secondary: '#5E4A10', glow: 'rgba(156,122,30,0.3)' },
    effect: { id: 'ceresWheat', canvasId: 'wheat-canvas', motif: 'sun' },
    industry: ['agriculture-food', 'wine-hospitality', 'environment-climate'],
  },
  {
    id: 'mixcoatl', ascii: 'mixcoatl', unicode: 'Mixcōātl', greek: '—',
    pantheon: 'nahuatl', tier: '1', tierLabel: 'Tier 1',
    domain: 'Clouds, Hunting, the Milky Way',
    meaning: '"Cloud Serpent" — god of the hunt, of clouds, and of the starry road',
    sources: ['Florentine Codex', 'Sahagún', 'Karttunen', 'Nahuatl dictionary', 'Cambridge'],
    domainUnicode: 'mixcōātl.com', domainPunycode: 'xn--mixcatl-01a.com',
    tagline: 'The Serpent in the Clouds',
    rentalTier: 'B',
    colors: { primary: '#3E4A5C', secondary: '#9AA5B5', glow: 'rgba(62,74,92,0.35)' },
    effect: { id: 'mixcoatlSerpent', canvasId: 'cloudserpent-canvas', motif: 'storm' },
    industry: ['space-astronomy', 'sports-athletics', 'environment-climate'],
  },
  {
    id: 'oba', ascii: 'oba', unicode: 'Ọba', greek: '—',
    pantheon: 'yoruba', tier: '1', tierLabel: 'Tier 1',
    domain: 'River, Devotion, Sanctuary',
    meaning: 'The river orisha Ọba — co-wife of the thunder god, lady of the sacred waters',
    sources: ['Idowu', 'Bascom', 'Abraham', 'Folklore', 'Cambridge', 'Oxford'],
    domainUnicode: 'ọba.com', domainPunycode: 'xn--oba-5ua.com',
    tagline: 'The River that Endures',
    rentalTier: 'B',
    colors: { primary: '#1F4A5C', secondary: '#7FA8B8', glow: 'rgba(31,74,92,0.35)' },
    effect: { id: 'obaRiver', canvasId: 'river-canvas', motif: 'water' },
    industry: ['water-utilities', 'faith', 'travel-tourism'],
  },
];
