/**
 * Meditation second paragraphs (pads) for entries whose blog posts still fall
 * short of the 2400-word band. Appended to lore extendedMeditation by
 * apply-pads.js (which then clears the scholars 'meditation' section for
 * re-synthesis). Each pad is a genuine continuation of the reflection —
 * concrete modern resonance, never filler.
 */

module.exports = {
  atropos: `<p>There is a reason programmers, actuaries, and hospice workers all know her name without knowing it: every system that terminates correctly implements her. The thread that ends on schedule is not a tragedy but a design — the Moirai were never death-dealers but measure-keepers, and she is simply the sister who reads the measurement aloud. A culture that can name its ending honestly, the Greeks understood, is freer than one that cannot: the cut is only cruel when the weaving was dishonest.</p>`,

  drakon: `<p>Every field still keeps its dragons: the unslept watcher at the edge of the mapped world, guarding the one thing the mapmaker most wants. The Greeks' honesty was to leave the watcher a reason — the spring, the tree, the fleece are never worthless — and their warning was that the slaying is never free: Kadmos founds Thebes on a dragon's grave and pays for it in generations. To name the guardian is to ask the oldest question of ambition: what does this treasure cost, and who was keeping it, and why?</p>`,

  monokeros: `<p>Perhaps that is why the unicorn survives every debunking: it was never a zoological claim but a standard of rarity. Ktēsias wrote down what he heard, the translators chose the word they had, the medievals made a theology of it, and the financiers made a valuation — each age reporting the beast it needs. The one horn points, in every century, at the same thing: the value of what cannot be bred, bound, or brought to market.</p>`,

  phanes: `<p>The Orphic initiates buried with their gold tablets understood him as instruction, not cosmology: remember that you are hatched from light, and the dark of the grave is only the egg's second shell. That is why his cult left no temples and his myth left no images — the first-shining one is not worshipped but recognized, in every first draft, every first light, every beginning that must be swallowed before the real world can begin.</p>`,

  pegasos: `<p>And he remains the honest emblem of inspiration because the myth hides none of it: the gift is caught, not earned — a bridle in a dream, a spring in a stone — and it throws the rider who mistakes it for his own wings. Every artist who has flown on something they did not make, and every one who has been dropped for flying too high on it, knows exactly whose back they were on.</p>`,

  seiren: `<p>Her question has only sharpened in the age of the infinite song. Every feed is the meadow now — a voice that knows your name, your war, your wants, and promises wisdom if you only stop rowing. The Odyssey's answer was never ignorance: hear everything, keep the ropes, and let your crew row deaf through the meadow of bones. Attention is the last navigable strait, and she still sings on both shores of it.</p>`,

  troia: `<p>Her deepest lesson is the one the victors learned first: that a story is stronger than a wall. The Greeks won the war and spent three thousand years inside the city's aftermath — and Rome, wiser than all of them, simply claimed to be her. Every culture since has faced the same choice at her gate: to besiege the past, or to inherit it.</p>`,

  tyche: `<p>To worship chance, the Hellenistic cities understood, is not to surrender to her but to be honest about her: the cornucopia and the rudder in the same hands, gifts and steering at once. Every risk model, every insurance premium, every prayer before a voyage is her liturgy translated — the human attempt to stand in a fair relation to what happens. She alone of the gods never pretended the world was just; that is why they trusted her.</p>`,

  diana: `<p>Her question to every managed wilderness is the lake's own: can you look without touching? The Actaeon myth is not about a peeping hunter but about the gaze that consumes what it sees — and the grove at Nemi, where the priest-king guarded the tree with a sword, admits the paradox outright: some things are protected only by being made dangerous to approach. The wild she keeps is the wild that keeps itself.</p>`,

  ianus: `<p>Modernity made him its secret patron: every pivot, every launch, every new year, every door held open for a stranger is his small liturgy. The Romans began everything — journeys, marriages, consulates, the year itself — by naming him first, on the principle that a beginning honoured is half accomplished. His two faces are the correct posture for any threshold: gratitude backward, attention forward, and then — the god's whole point — through.</p>`,

  iuppiter: `<p>And the oaths continue, translated but recognizable: every courtroom's "the whole truth," every inauguration's raised hand, every treaty signed before witnesses rehearses the per Iovem Lapidem — the appeal to a witness greater than the parties. The Romans' insight stands unimproved: promises between mortals need a sky to be sworn by, or they are only weather.</p>`,

  neptunus: `<p>The drought-festival and the sea-empire belong together, and the old god keeps both books still: the water we pray for and the water we fear, the well and the wave. Every age that pumps an aquifer or insures a coastline is doing his liturgy in engineering — asking the question his festival asked in the July heat: will the water come, will it be enough, and what will it cost when it does?</p>`,

  vulcanus: `<p>His contract is written now in building codes and reactor protocols, in firewalls and safety factors: the fire is not the enemy — the distance is the discipline. Rome worshipped him outside the walls on purpose, and every civilization since has redrawn that line where the useful flame ends and the other kind begins. To keep a forge is to renegotiate his treaty daily, in steel, in silica, in code.</p>`,

  hp: `<p>The dam ended his flood in a single generation, and Egypt's ambivalence about the Aswan High Dam is his modern myth: the silt no longer comes, the fields are fed by chemistry, the delta retreats — and no one would vote to bring the drowning back. ḥp's question outlives his river: abundance engineered is abundance owed to what? The flood that fed for five thousand years was never free; it was merely invoiced in a currency — rhythm, silt, patience — that modernity is only now learning to price again.</p>`,

  amsa: `<p>The portion-god is the least dramatic and most daily of the Ādityas, and that is his teaching: justice is mostly arithmetic — the fair share, the counted month, the inheritance divided without sleight. A sacrifice, a will, a budget, a calendar: all are his small liturgies. The sun rises each morning and apportions the day evenly to all; the rest of the work — the hymn says with characteristic bluntness — is ours.</p>`,

  daksa: `<p>His cycle is retold wherever competence grows proud: the flawless system, the perfect rite, the immaculate procedure — and the one excluded name that brings it all down. India keeps the story as a standing audit of institutions: correctness is not completeness, and the guest list is a moral document. The goat's head he wears is the gentlest icon in the Purāṇas: the skilled man, restored — thinking, at last, with a humbler head.</p>`,

  dhatr: `<p>His is the least visible and most load-bearing idea in the Veda: that the world holds because things have been set where they belong — the sun in its path, the word in its form, the root in its dhātu. Grammar and medicine, the two great Indian sciences, both took his root-word for their elements, as if to say: reality is well-placed, and knowledge is learning the placements. Every foundation poured, every standard ratified, every definition fixed is a small act of Dhātṛ — the setting-down on which everything else stands.</p>`,

  pusan: `<p>And his offices have only multiplied: every search-and-rescue, every lost-and-found, every convoy and escort, every road-prayer murmured at a journey's start is his sūkta continued. The hymns call him the god of what is on the way — not the hearth but the road, not the feast but the drive home. The herdsman with the goad and the goat-chariot remains the patron of the least heroic and most necessary of human acts: going out, and coming back, and bringing everyone along.</p>`,

  tvastr: `<p>The Vṛtra story's warning has become the engineer's daily proverb: the specification is destiny — a misplaced accent, a wrong unit, a flipped sign, and the thing built to save will kill. Tvaṣṭṛ forged perfectly and spoke imperfectly, and the monster inherited the error. Every craft since has known his double lesson: the work must be true, and the intention legible — because what we make will act on what we meant, not on what we wished we had meant.</p>`,

  fuxi: `<p>Leibniz saw the trigrams and recognized binary arithmetic; the information age looked again and found the whole grammar of bits — the broken and unbroken line as zero and one. Whether or not the old sage intended the code, his lesson stands: the world's patterns are legible to whoever looks long enough, and three lines, honestly observed, can hold a civilization's worth of distinctions. The first technology was attention.</p>`,

  guanyin: `<p>Her vow scales with the century: more cries than ever, more channels than ever — and the same first requirement. The bodhisattva's thousand arms and thousand eyes are not a fantasy of power but of capacity: to hear without triage, to reach without ranking. Every crisis line, every rescue service, every stranger who simply stays on the phone is her liturgy in action: the sounds of the world, answered one at a time.</p>`,

  mengpo: `<p>Her bowl is the folk answer to a question philosophy never settled: whether a person is their memories. The underworld's mercy is also its amnesty — the murderer and the mother drink alike, and both are reborn unburdened. We moderns keep our records differently: nothing is forgotten, everything is archived. She stands at the bridge asking the question the digital age most needs: what is forgiveness, if not a permission to forget — and who will serve the tea?</p>`,

  nuwa: `<p>The rope and the handmade figures remain the tradition's quiet self-critique: some are shaped with care, some flung from a rope — and the goddess who made both is the one who mends the sky for all of them. Repair is her gospel and her rebuke: the world will break — pillars snap, heavens leak — and the measure of the maker is not the first creation but the mending. She is, for every restorer, nurse, and engineer of last resort, the patron of the second day.</p>`,

  hokkaido: `<p>The island's two names have begun, at last, to speak to each other: the Ainu language taught in Upopoy's halls, the iomante explained rather than exoticized, the snow country marketed by its indigenous name's dignity. Frontiers are usually where names die; Hokkaidō is attempting the rarer thing — a map where the new name carries the old one's meaning. It is the experiment every settler society eventually must run, and the north island is running it in public.</p>`,

  honshu: `<p>The twenty-year rebuilding of Ise is the island's deepest answer to modernity: continuity is not preservation but repetition — the shrine is never old and never new, the cypress always fresh, the craft always taught. Honshū holds its megacities and its mirror with the same hands, and its lesson to every anxious age is the carpenter's: what you rebuild on schedule, you never have to save.</p>`,

  kyushu: `<p>The gateway's pattern persists in silicon: the island that took in rice, iron, scripture, and surgery now takes in the semiconductor supply chain, and Kumamoto's fabs are Tsukushi's old role in new matter. Every borderland knows its double exposure — first to the gift, first to the invasion — and Kyūshū's answer has been constant for two thousand years: translate everything, fear nothing twice, and keep the door's hinges oiled.</p>`,

  xolotl: `<p>The axolotl's refusal to grow up — keeping its gills, its larval smile, its power to regrow a heart — has made it the scientist's darling and the city's emblem, and it is the god's final joke: the deity who begged not to die survives as the animal that regenerates everything. Xōlōtl's question is the guide's own: transformation is not escape — but sometimes, in the last lake, it is enough.</p>`,

  ogun: `<p>Every driver who splashes gin on a bumper in Lagos, every mechanic who taps the anvil before the first weld, is keeping his liturgy without needing its name: tools are moral — they open roads or open wounds — and the hand must be steadier than the blade. Ògún's myth admits what no other war-god's does: that the rage is his own. The road-opener who cut down his own town is the honest patron of a technological age: the strength is real, the forest is real, and so is the apology owed when the blade turns.</p>`,
};
