/**
 * Curated flagship taglines — the 2026-07 editorial pass.
 * Voice rules: 2-6 word mythic epithet (or dual "X · Y"); never an etymology
 * gloss, never a dictionary snippet, never a repeat of the domain text.
 * Defensible in the lore; enticing in the hero; consistent across all 252.
 * Only entries whose current tagline fails the voice rules are included —
 * the rest keep their existing taglines.
 */

module.exports = {
  helheimr: 'The Misty Hall of the Dead',
  sia: 'The Perception of the Divine',
  nirmata: 'The Architect of the Gods',
  // ── Greek core & locations ──
  europe: 'The Broad-Faced Shore of the West',
  gaia: 'The Mother Under Everything',
  helios: 'The Eye of the Day',
  sparte: 'The City Forged for War',
  alfheimr: 'The Realm of Living Light',
  chaos: 'The Yawn Before the World',
  delphoi: 'The Navel of the World',
  jotunheimr: 'The Land of Stone and Ice',
  midgardr: 'The Fenced World of Men',
  pontos: 'The Sea Before It Had a Name',
  ragnarok: 'The Twilight of the Gods',
  ra: 'The First Light of Morning',
  asia: 'The Continent of the Rising Sun',
  athenai: 'The City of the Owl',
  kobe: 'The Door of the Gods',
  kyoto: 'The Thousand-Year Capital',
  libye: 'The Sun-Baked Continent',
  osaka: 'The Kitchen of the Country',
  muspellheimr: 'The Furnace of the End',
  olympos: 'The Home Above the Storm',
  helheimr: 'The Misty Hall of the Dead',
  erebus: 'The Deepest Dark',
  aither: 'The Bright Air the Gods Breathe',
  ouranos: 'The Sky that Covered All',
  tartaros: 'The Prison Beneath the Roots',
  shu: 'The Breath Between Sky and Earth',
  heka: 'The First Work of Magic',
  eros: 'The Oldest Arrow',
  kali: 'The Black One, Time Itself',
  vishnu: 'The Preserver of All Things',
  herakles: 'The Glory of Labors',
  horus: 'The Falcon on the Horizon',
  ganesha: 'The Lord of Beginnings',
  eos: 'The Rosy-Fingered Dawn',
  njordr: 'The Wealth of Quiet Harbors',
  jormungandr: 'The Serpent that Girds the World',
  manannan: 'The Mist-Walker of the Sea',
  tane: 'The Father of Forests',
  modi: 'The Wrath that Outlives the Storm',
  phoenix: 'The Fire that Always Returns',
  dagan: 'The Grain of the Two Rivers',
  varuna: 'The Keeper of the Cosmic Waters',
  hygieia: 'The Clean Hand of Health',
  theia: 'The Sight that Sees the Light',
  iris: 'The Rainbow Sent Down',
  hydra: 'The Heads that Grow Back',
  ge: 'The Ground of Every Step',
  isis: 'The Throne that Walks',
  sekhmet: 'The Powerful One',
  bastet: 'The Lady of the Hearth-Cats',
  amun: 'The Hidden One',
  wadjet: 'The Green Guardian',
  ankh: 'The Sign of Life Itself',
  ashur: 'The God of the Assyrian Spear',
  shamash: 'The Sun of Justice',
  andromeda: 'The Princess of the Rock',
  adamas: 'The Stone Nothing Breaks',
  arachne: 'The Weaver of the Web',
  dagan2: null,
  dazhbog: 'The Giver of Gold',
  thoth: 'The Ibis of the Measured Word',
  eggther: 'The Watchman of the Last Morning',
  apep: 'The Serpent of Unmaking',
  amitabha: 'The Light Without Measure',
  surya: 'The Sun that Sees All',
  perkunas: 'The Thunder of the Oaks',
  buri: 'The First to Wake from Ice',
  xian: 'The One Who Transcends',
  tian: 'The Heaven that Governs',
  mictlantecutli: 'The Lord of the Land of the Dead',
  trengtreng: 'The Thunder of the Mapuche',
  ka: 'The Vital Double',
  prajapati: 'The Father of All Creatures',
  okeanos: 'The River that Rings the World',
  anu: 'The Sky of the First Kings',
  apsu: 'The Sweet Water Below',
  ea: 'The Deep of Wisdom',
  enlil: 'The Lord of the Command',
  tiamat: 'The Salt Mother of All',
  ishtar: 'The Morning Star at War',
  astart: 'The Queen of Heaven',
  asa: 'The Order that Holds the Sky',
  aseratu: 'She Who Treads the Sea',
  leviathan: 'The Coil of the Deep',
  mot: 'The God of the Last Sleep',
  quetzalcoatl: 'The Feathered Serpent',
  moses: 'The Voice from the Mountain',
  david: 'The Singer on the Throne',
  solomon: 'The Builder of the House',
  noah: 'The Keeper of the Ark',
  cain: 'The Mark of the First Crime',
  abel: 'The Breath of the First Offering',
  hemera: 'The Day that Never Ends',
  long: 'The Dragon of the Rivers',
  taichi: 'The Great Extreme',
  yinyang: 'The Two that Make the One',
  wuji: 'The Nothing Before the Limit',
  bagua: 'The Eight Signs of Change',
  wuxing: 'The Five that Turn the Seasons',
  laozi: 'The Old Master of the Way',
  papatuanuku: 'The Land that Births All',
  taishang: 'The Lord on High',
  tiandi: 'The Heaven-and-Earth Order',
  yam: 'The Ocean that Raged First',
  shapash: 'The Sun of the Canaanites',
  he: 'The Receptacle of the Divine',
  hypnos: 'The Gentle Unbinding',
  hebe: 'The Cup of Youth',
  moirai: 'The Weavers of the Thread',
  delphoi2: null,
  acheron: 'The River of Sorrows',
  adamas2: null,
  aer: 'The Lower Air We Breathe',
  aganju: 'The Volcano of the Orisha',
  ahuramazda: 'The Wise Lord of Light',
  aigyptos: 'The Black Land Itself',
  akh: 'The Luminous Spirit',
  alexandros: 'The Defender of Men',
  alkmene: 'The Mother of the Strong One',
  amsa: 'The Allotted Share',
  ananke: 'The Necessity that Rules',
  anat: 'The Virgin of the Hunt and War',
  anubis: 'The Jackal of the Scales',
  antigone: 'The Daughter of Defiance',
  antilochus: 'The Loyal Shield of Achilles',
  anuket: 'The Lady of the Cataract',
  aphrodite: 'Born of Sea-Foam · The Irresistible',
  ares: 'The Battle Fury · The Bloody Spear',
  arete: 'The Excellence that Costs',
  asclepius: null,
  asklepios: 'The Physician of the Gods',
  astraeus: 'The Titan of the Stars',
  astrid: null,
  atalanta: 'The Foot that Won the Race',
  ate: 'The Blindness of Ruin',
  athena: 'The Grey-Eyed Strategist · Patron of Athens',
  athens: null,
  atlas: 'The World-Bearer · Guardian of the Western Edge',
  atman: 'The Self that Is All',
  atropos: 'The Inflexible Cut',
  attis: 'The Beloved of the Mountain Mother',
  autolycus: 'The Wolf of Tricks',
  aven: 'The Shadow of the Shrine',
  ba: 'The Soul that Takes Form',
  bellerophon: 'The Rider of the Winged Horse',
  bhima: 'The Strength of the Wolf',
  briareos: 'The Hundred-Handed Watch',
  calypso: 'The Isle of the Hidden',
  cassandra: 'The Truth No One Believes',
  centeotl: 'The Maize Made Divine',
  chalchiuhtlicue: 'The Lady of the Jade Skirt',
  chimaira: 'The Three-Part Fire',
  chicomecoatl: 'The Mother of Maize',
  chrysaor: 'The Sword Born of Gold',
  citlalicue: 'The Star of the Skirt',
  coeus: 'The Titan of the Mind',
  coatlicue: 'The Mother of Serpents',
  creusa: 'The Quiet of the Cave',
  daksa: 'The Skilled Father',
  deimos: 'The Fear Before the Charge',
  demeter: 'The Corn Mother · Bringer of Seasons',
  dhatr: 'The Establisher of Worlds',
  diana: 'The Huntress of the Groves',
  diancecht: 'The Physician of the Tuatha',
  diomedes: 'The Counsel of War',
  draupadi: 'The Fire-Born Queen',
  eileithyia: 'The Helper of Birth',
  eirene: 'The Peace that Holds',
  elektra: 'The Amber Light',
  eleusis: 'The Town of the Mysteries',
  elysion: 'The Fields of the Blessed',
  enyo: 'The Waster of Cities',
  epeiros: 'The Mainland of the West',
  erato: 'The Muse of the Lovely',
  erebus2: null,
  ethos: 'The Character of the City',
  etzel: null,
  eudaimonia: 'The Good Spirit Within',
  eurypylus: 'The Broad Gate of War',
  fides: 'The Bond that Holds Rome',
  fujin: 'The Wind in the Bag',
  ganga: 'The River That Fell From Heaven',
  geras: 'The Weight of Years',
  gnosis: 'The Knowing that Saves',
  guanyin: 'The One Who Hears',
  hades: 'The Unseen One · Lord of the Dead',
  harpokrates: 'The Child on the Lotus',
  harpyia: 'The Snatch of the Storm',
  hecate: null,
  hector: 'The Shield of Troy',
  hekate: 'The Torch-Bearer · Queen of Ghosts',
  helios2: null,
  hen: 'The One Above the Many',
  hephaistos: 'The Lame-Smith · Worker of Wonder',
  hera: 'The Golden-Throned · Guardian of Marriage',
  hermes: 'The Soul-Guide · Lord of Boundaries',
  hestia: 'The Eternal Flame · Center of the Home',
  hiiaka: 'The Cloud of the Sacred Isle',
  hokkaido: 'The North Sea Road',
  honshu: 'The Spine of Japan',
  hraesvelgr: 'The Eagle at the Edge',
  huitzilopochtli: 'The Hummingbird of the South',
  ianus: 'The God of the Door',
  iapetus: 'The Titan of the West',
  icarus: 'The Wax and the Warning',
  idomeneus: 'The Spear of Crete',
  itzpapalotl: 'The Obsidian Butterfly',
  iuno: 'The Queen of Heaven',
  iuppiter: 'The Sky Father',
  jizo: 'The Guardian of Travelers',
  kairos: 'The Moment that Matters',
  kamapuaa: 'The Hog Child of the Isles',
  kanaloa: 'The Deep of the Pacific',
  kane: 'The Maker of the Islands',
  kartikeya: 'The Commander of the Gods',
  ker: 'The Dark Angel · Minister of Doom',
  khonsu: 'The Moon of Thebes',
  kore: 'The Maiden of Spring',
  kothar: 'The Smith of the Gods',
  kreios: 'The Ram of the Titans',
  krishna: 'The Dark One, the Beloved',
  kunlun: 'The Mountain of the Immortals',
  lakshmi: 'The Lotus of Fortune',
  lanling: 'The Orchid of the Battlefield',
  limos: 'The Hunger that Teaches',
  lugh: 'The Long-Armed Master',
  lumbini: 'The Garden of the Birth',
  maa: 'The Eye that Sees Straight',
  maat: 'The Feather of Truth',
  mahakala: 'The Great Black One',
  manu: 'The First of Men',
  marici: 'The Ray of Dawn',
  maui: 'The Trickster of the Isles',
  maya: 'The Veil of the Real',
  mayahuel: 'The Mother of the Agave',
  mazda: null,
  megaera: 'The Jealous Flame',
  meleagros: 'The Brand and the Burning',
  menelaus: 'The King Who Sailed for Helen',
  mengpo: 'The Tea of Oblivion',
  minos: 'The Judge of the Labyrinth',
  mirage: null,
  mithra: 'The Covenant of Light',
  mnemosyne: 'The Mother of Memory',
  monokeros: 'The One Horn',
  morrigan: 'The Phantom Queen',
  nabu: 'The Scribe of the Gods',
  nagarjuna: 'The Master of the Middle Way',
  narke: 'The Numbness of the Deep',
  neoptolemus: 'The Son Who Finished the War',
  neptunus: 'The Lord of Waters',
  nht: 'The Strong, the Victorious',
  nidhogg: 'The Gnawer of Roots',
  nike: 'The Winged Herald · Bringer of Triumph',
  nikko: 'The Sunlight of the Shrines',
  nirvana: 'The Stillness Beyond',
  nix: 'The Veil of Night',
  nous: 'The Mind that Moves All',
  numen: 'The Presence in the Place',
  nuwa: 'The Mender of Heaven',
  odysseus: 'The Man of Many Turns',
  oedipus: 'The King Who Asked the Riddle',
  oizys: 'The Weight of Woe',
  okuninushi: 'The Master of the Land',
  ometecuhtli: 'The Lord of Duality',
  omecihuatl: 'The Lady of Duality',
  ometeotl: 'The God of Two',
  orpheus: 'The Singer of the World',
  orun: 'The Heaven Above the Heavens',
  pandora: 'The Gift that Opened Everything',
  pangu: 'The First Giant',
  parvati: 'The Daughter of the Mountain',
  patroclus: 'The Friend of the Swift-Footed',
  pegasus: 'The Thunder-Horse',
  pentheus: 'The King Who Denied the God',
  perseus: 'The Slayer of the Gorgon',
  phaethon: 'The Chariot of Fire',
  philoctetes: 'The Bow that Won Troy',
  phobos: 'The Rout Before the Spear',
  phoenix2: null,
  pneuma: 'The Breath of the World',
  podalirius: 'The Healer of the Host',
  praxis: 'The Doing of the Word',
  priamos: 'The Last King of Troy',
  prometheus: 'The Forethinker · Champion of Mortals',
  psyche: 'The Soul that Earned Its Wings',
  ptah: 'The Sculptor of the Gods',
  pusan: 'The Guide of Roads',
  putana: 'The Nurse of Shadows',
  pyr: 'The First Flame',
  radha: 'The Beloved of the Cowherd',
  rama: 'The Best of Men',
  ratri: 'The Night that Covers All',
  rhea: 'The Mother of the Gods',
  rta: 'The Order of the Real',
  saraswati: 'The River of Eloquence',
  sati: 'The True and Devoted',
  savitri: 'The Sun that Stirs All',
  seiren: 'The Song that Knows',
  selene: 'The Radiant · Driver of the Silver Chariot',
  seshat: 'The Lady of the Record',
  shango: 'The Thunder of the Orisha',
  shiva: 'The Auspicious Destroyer',
  sia: 'The Perception of the Divine',
  sikyon: 'The Citadel of the Isthmus',
  sinon: 'The Lie that Opened Troy',
  sisyphus: 'The Stone of Forever',
  sita: 'The Daughter of the Furrow',
  skadi: 'The Hunter of the Mountains',
  steh: 'The Necessary Storm',
  tara: 'The Star that Saves',
  tantalus: 'The Thirst of Forever',
  teiresias: 'The Seer of Both Lives',
  telamon: 'The Father of the Bow',
  teucer: 'The Archer of the Shore',
  tezcatlipoca: 'The Smoking Mirror',
  thaleia: 'The Muse of the Meadow',
  thanatos: 'The Quiet of the End',
  themis: 'The Law Before the Laws',
  thetis: 'The Silver-Footed Sea',
  thjazi: 'The Giant of the Winds',
  thor: 'The Thunder of the Oaks',
  tirnanog: 'The Land of the Young',
  toci: 'The Grandmother of Birth',
  tonacatecuhtli: 'The Lord of Our Flesh',
  troia: 'The City of Story',
  tvastr: 'The Fashioner of the Gods',
  tyche: 'The Happening',
  uranus: 'The Sky Before the Gods',
  ushas: 'The Dawn in Her Chariot',
  vac: 'The Voice of the Vedas',
  vajrapani: 'The Thunderbolt in Hand',
  valmiki: 'The Poet of the First Song',
  vashistha: 'The Wisest of the Sages',
  vidarr: 'The Silent Avenger',
  virtus: 'The Courage of Rome',
  vyasa: 'The Arranger of the Veda',
  vulcanus: 'The Fire that Serves',
  xolotl: 'The Twin in the Dark',
  yanluo: 'The Judge of the Dead',
  zephyros: 'The Gentle West Wind',
  zeus: 'Lord of the Sky · Wielder of the Thunderbolt',
  zhangdaoling: 'The Master of the Celestial Way',
  zhenwu: 'The Warrior of the North',
  zhongliquan: 'The Eldest of the Immortals',
  zhuangzi: 'The Dreamer of the Butterfly',
  zhurong: 'The Fire of the South',
  zmeygorynych: 'The Dragon of the Mountain',
};
