'use strict';
const c = require('C:/projects/punycodex/platform/texts/bible-kjv/eng.json');
const get = (id) => c.sections.find((s) => s.id === id);
const g = get('genesis');
const ch1 = g.text.split('\n\n')[0];
console.log('Genesis ch1 verse count:', (ch1.match(/1:\d+/g) || []).length, '(expect 31)');
console.log('Genesis 1:1:', ch1.slice(0, 80));
console.log('Genesis ch1 tail:', ch1.slice(-140));
const ps = get('psalms').text.split('\n\n');
console.log('Psalm 23:', ps[22].slice(0, 120));
console.log('Psalm 23 verse count:', (ps[22].match(/23:\d+/g) || []).length, '(expect 6)');
const s1 = get('1-samuel');
const s1ch1 = s1.text.split('\n\n')[0];
console.log('1Sam ch1 verse count:', (s1ch1.match(/1:\d+/g) || []).length, '(expect 28)');
console.log('1Sam 1:1:', s1ch1.slice(0, 120));
const mt = get('matthew').text.split('\n\n');
console.log('Matt ch5 verse count:', (mt[4].match(/5:\d+/g) || []).length, '(expect 48)');
const rev = get('revelation').text.split('\n\n');
console.log('Rev 22 tail:', rev[21].slice(-180));
const all = c.sections.map((s) => s.text).join('\n');
console.log('alias leak:', /Otherwise Called|Commonly Called/.test(all) ? 'FOUND' : 'none');
console.log('Gutenberg leak:', /Gutenberg/.test(all) ? 'FOUND' : 'none');
console.log('Jonah full:', get('jonah').text.split('\n\n').length, 'chapters;');
console.log('Song 1:1:', get('song-of-solomon').text.slice(0, 100));
