/**
 * PuniCodex — Canonical industry-alias vocabulary
 *
 * Companion to type/js/industry-patterns.js. Maps the fragment professions,
 * trades, and search terms a real sponsor would type ("plumber", "poet",
 * "church") onto the 57 curated industries of the pattern map (1,300+ terms).
 * Powers the Find Your Pattern autocomplete on /patterns/ and the
 * /api/v1/industry-patterns/match endpoint.
 *
 * Curation discipline:
 *   - weight 2 (direct): a direct synonym for the industry or a core
 *     profession inside it (plumber → water-utilities).
 *   - weight 1 (adjacent): a neighboring fragment, sub-trade, or audience
 *     term that reliably implies the industry (irrigation → water-utilities).
 *   - One alias has exactly one home. A term that could serve two industries
 *     is assigned to the best fit only — precision over recall.
 *   - Terms are lowercase, singular preferred (plurals added only when
 *     natural), multi-word terms allowed. UK/US variants both included
 *     where a real person would type either (solicitor/attorney).
 *   - If no industry genuinely fits a profession, the term is omitted.
 *
 * Generated consumers (DO NOT edit by hand):
 *   - platform/api/industry-patterns.json (aliases index, meta.aliasCount)
 *   - platform/browser/renderer/industry-patterns.json
 *   - patterns/index.html (embedded in window.PATTERN_GRAPH)
 *
 * Run `npm run generate` after editing this file.
 */

'use strict';

const INDUSTRY_ALIASES = {
  'solar-energy': [
    { term: 'solar', weight: 2 },
    { term: 'solar power', weight: 2 },
    { term: 'solar panel', weight: 2 },
    { term: 'solar installer', weight: 2 },
    { term: 'solar company', weight: 2 },
    { term: 'solar farm', weight: 2 },
    { term: 'solar thermal', weight: 2 },
    { term: 'photovoltaic', weight: 2 },
    { term: 'renewable energy', weight: 2 },
    { term: 'pv installer', weight: 1 },
    { term: 'renewables', weight: 1 },
    { term: 'clean energy', weight: 1 },
    { term: 'green energy', weight: 1 },
    { term: 'sun power', weight: 1 },
    { term: 'solar energy', weight: 2 },
    { term: 'solar panels', weight: 2 },
    { term: 'solar installation', weight: 1 },
    { term: 'rooftop solar', weight: 1 },
    { term: 'solar battery', weight: 1 },
    { term: 'solar pv', weight: 1 },
    { term: 'solar developer', weight: 1 },
    { term: 'solar maintenance', weight: 1 },
    { term: 'solar panel cleaning', weight: 1 },
  ],
  'wind-energy': [
    { term: 'wind energy', weight: 2 },
    { term: 'wind power', weight: 2 },
    { term: 'wind farm', weight: 2 },
    { term: 'wind turbine', weight: 2 },
    { term: 'offshore wind', weight: 2 },
    { term: 'wind technician', weight: 2 },
    { term: 'wind engineer', weight: 2 },
    { term: 'windmill', weight: 1 },
    { term: 'turbine technician', weight: 1 },
    { term: 'aerogenerator', weight: 1 },
    { term: 'wind turbine technician', weight: 2 },
    { term: 'onshore wind', weight: 1 },
    { term: 'offshore wind farm', weight: 1 },
    { term: 'turbine', weight: 1 },
    { term: 'wind developer', weight: 1 },
    { term: 'wind turbine maintenance', weight: 1 },
    { term: 'wind energy company', weight: 1 },
    { term: 'wind farm operator', weight: 1 },
    { term: 'blade technician', weight: 1 },
  ],
  'thermal-energy': [
    { term: 'geothermal', weight: 2 },
    { term: 'geothermal energy', weight: 2 },
    { term: 'heating', weight: 2 },
    { term: 'hvac', weight: 2 },
    { term: 'boiler', weight: 2 },
    { term: 'heating engineer', weight: 2 },
    { term: 'thermal power', weight: 2 },
    { term: 'heat pump', weight: 2 },
    { term: 'furnace', weight: 1 },
    { term: 'fireplace', weight: 1 },
    { term: 'stove', weight: 1 },
    { term: 'district heating', weight: 1 },
    { term: 'gas engineer', weight: 1 },
    { term: 'hvac tech', weight: 1 },
    { term: 'hvac engineer', weight: 1 },
    { term: 'boiler repair', weight: 1 },
    { term: 'gas safe engineer', weight: 1 },
    { term: 'central heating', weight: 1 },
    { term: 'air conditioning', weight: 1 },
    { term: 'underfloor heating', weight: 1 },
    { term: 'boiler installation', weight: 1 },
    { term: 'heat pump installer', weight: 1 },
    { term: 'gas boiler', weight: 1 },
  ],
  'storm-forecasting': [
    { term: 'meteorologist', weight: 2 },
    { term: 'meteorology', weight: 2 },
    { term: 'weather', weight: 2 },
    { term: 'weather forecast', weight: 2 },
    { term: 'weather app', weight: 2 },
    { term: 'forecaster', weight: 2 },
    { term: 'weatherman', weight: 1 },
    { term: 'storm chaser', weight: 1 },
    { term: 'hurricane tracker', weight: 1 },
    { term: 'weather radar', weight: 1 },
    { term: 'weather station', weight: 1 },
    { term: 'storm warning', weight: 1 },
    { term: 'severe weather', weight: 1 },
    { term: 'hurricane', weight: 1 },
    { term: 'tornado', weight: 1 },
    { term: 'weather forecasting', weight: 1 },
    { term: 'weather data', weight: 1 },
    { term: 'rain radar', weight: 1 },
    { term: 'weather warning', weight: 1 },
    { term: 'weather presenter', weight: 1 },
  ],
  maritime: [
    { term: 'shipping', weight: 2 },
    { term: 'sailor', weight: 2 },
    { term: 'shipyard', weight: 2 },
    { term: 'shipbuilding', weight: 2 },
    { term: 'fishing', weight: 2 },
    { term: 'fisherman', weight: 2 },
    { term: 'cruise', weight: 2 },
    { term: 'ferry', weight: 2 },
    { term: 'port', weight: 2 },
    { term: 'boat', weight: 2 },
    { term: 'ship captain', weight: 2 },
    { term: 'seafarer', weight: 1 },
    { term: 'yacht', weight: 1 },
    { term: 'marine', weight: 1 },
    { term: 'dockworker', weight: 1 },
    { term: 'lighthouse', weight: 1 },
    { term: 'marine engineer', weight: 1 },
    { term: 'deckhand', weight: 1 },
    { term: 'cargo ship', weight: 1 },
    { term: 'sailing', weight: 1 },
    { term: 'boat builder', weight: 1 },
    { term: 'skipper', weight: 1 },
    { term: 'marine mechanic', weight: 1 },
    { term: 'harbour master', weight: 1 },
    { term: 'cruise ship', weight: 1 },
    { term: 'container ship', weight: 1 },
  ],
  'water-utilities': [
    { term: 'plumber', weight: 2 },
    { term: 'plumbing', weight: 2 },
    { term: 'water engineer', weight: 2 },
    { term: 'water company', weight: 2 },
    { term: 'water supply', weight: 2 },
    { term: 'water treatment', weight: 2 },
    { term: 'drainage', weight: 1 },
    { term: 'sewage', weight: 1 },
    { term: 'irrigation', weight: 1 },
    { term: 'hydrologist', weight: 1 },
    { term: 'wastewater', weight: 1 },
    { term: 'utility', weight: 1 },
    { term: 'pipe fitter', weight: 1 },
    { term: 'well driller', weight: 1 },
    { term: 'bathroom fitter', weight: 1 },
    { term: 'drainage engineer', weight: 1 },
    { term: 'plumbing company', weight: 1 },
    { term: 'emergency plumber', weight: 1 },
    { term: 'blocked drain', weight: 1 },
    { term: 'septic tank', weight: 1 },
    { term: 'water filtration', weight: 1 },
    { term: 'leak detection', weight: 1 },
    { term: 'plumbing and heating', weight: 1 },
  ],
  'aviation-aerospace': [
    { term: 'pilot', weight: 2 },
    { term: 'airline', weight: 2 },
    { term: 'airport', weight: 2 },
    { term: 'aviation', weight: 2 },
    { term: 'aerospace', weight: 2 },
    { term: 'flight attendant', weight: 2 },
    { term: 'drone', weight: 2 },
    { term: 'aircraft', weight: 2 },
    { term: 'air traffic controller', weight: 2 },
    { term: 'helicopter', weight: 1 },
    { term: 'flight school', weight: 1 },
    { term: 'balloonist', weight: 1 },
    { term: 'aircraft engineer', weight: 1 },
    { term: 'cabin crew', weight: 1 },
    { term: 'drone pilot', weight: 1 },
    { term: 'drone operator', weight: 1 },
    { term: 'aircraft maintenance', weight: 1 },
    { term: 'air charter', weight: 1 },
    { term: 'private jet', weight: 1 },
    { term: 'aerospace engineer', weight: 1 },
    { term: 'baggage handler', weight: 1 },
    { term: 'flight instructor', weight: 1 },
    { term: 'airline pilot', weight: 1 },
    { term: 'helicopter pilot', weight: 1 },
    { term: 'air hostess', weight: 1 },
  ],
  'space-astronomy': [
    { term: 'astronomer', weight: 2 },
    { term: 'space', weight: 2 },
    { term: 'observatory', weight: 2 },
    { term: 'telescope', weight: 2 },
    { term: 'astronaut', weight: 2 },
    { term: 'planetarium', weight: 2 },
    { term: 'space agency', weight: 2 },
    { term: 'astrophysics', weight: 2 },
    { term: 'rocket', weight: 1 },
    { term: 'satellite', weight: 1 },
    { term: 'stargazing', weight: 1 },
    { term: 'cosmology', weight: 1 },
    { term: 'nasa', weight: 1 },
    { term: 'astrophotography', weight: 1 },
    { term: 'space tourism', weight: 1 },
    { term: 'astrophysicist', weight: 1 },
    { term: 'satellite engineer', weight: 1 },
    { term: 'rocket launch', weight: 1 },
    { term: 'space startup', weight: 1 },
    { term: 'rocket scientist', weight: 1 },
    { term: 'satellite launch', weight: 1 },
    { term: 'space engineer', weight: 1 },
  ],
  defense: [
    { term: 'military', weight: 2 },
    { term: 'army', weight: 2 },
    { term: 'soldier', weight: 2 },
    { term: 'navy', weight: 2 },
    { term: 'air force', weight: 2 },
    { term: 'veteran', weight: 2 },
    { term: 'defense contractor', weight: 2 },
    { term: 'defence', weight: 2 },
    { term: 'security contractor', weight: 1 },
    { term: 'mercenary', weight: 1 },
    { term: 'marine corps', weight: 1 },
    { term: 'special forces', weight: 1 },
    { term: 'bodyguard', weight: 1 },
    { term: 'armed forces', weight: 1 },
    { term: 'reservist', weight: 1 },
    { term: 'defence contractor', weight: 1 },
    { term: 'peacekeeper', weight: 1 },
    { term: 'army officer', weight: 1 },
    { term: 'defence industry', weight: 1 },
    { term: 'security guard', weight: 1 },
    { term: 'airman', weight: 1 },
    { term: 'infantry', weight: 1 },
  ],
  cybersecurity: [
    { term: 'cybersecurity', weight: 2 },
    { term: 'cyber security', weight: 2 },
    { term: 'hacker', weight: 2 },
    { term: 'infosec', weight: 2 },
    { term: 'penetration tester', weight: 2 },
    { term: 'ethical hacker', weight: 2 },
    { term: 'security researcher', weight: 2 },
    { term: 'antivirus', weight: 2 },
    { term: 'soc analyst', weight: 1 },
    { term: 'malware', weight: 1 },
    { term: 'security operations', weight: 1 },
    { term: 'cryptographer', weight: 1 },
    { term: 'security engineer', weight: 1 },
    { term: 'ciso', weight: 1 },
    { term: 'pen tester', weight: 1 },
    { term: 'red team', weight: 1 },
    { term: 'bug bounty', weight: 1 },
    { term: 'cybersecurity consultant', weight: 1 },
    { term: 'it security', weight: 1 },
    { term: 'cyber security analyst', weight: 1 },
    { term: 'network security', weight: 1 },
    { term: 'security audit', weight: 1 },
    { term: 'ethical hacking', weight: 1 },
    { term: 'cyber attack', weight: 1 },
  ],
  'software-tech': [
    { term: 'software developer', weight: 2 },
    { term: 'software engineer', weight: 2 },
    { term: 'programmer', weight: 2 },
    { term: 'web developer', weight: 2 },
    { term: 'app developer', weight: 2 },
    { term: 'devops', weight: 2 },
    { term: 'cloud engineer', weight: 2 },
    { term: 'saas', weight: 2 },
    { term: 'software company', weight: 2 },
    { term: 'coding bootcamp', weight: 1 },
    { term: 'full stack developer', weight: 1 },
    { term: 'it support', weight: 1 },
    { term: 'tech company', weight: 1 },
    { term: 'devops engineer', weight: 1 },
    { term: 'sre', weight: 1 },
    { term: 'site reliability engineer', weight: 1 },
    { term: 'frontend developer', weight: 1 },
    { term: 'backend developer', weight: 1 },
    { term: 'mobile developer', weight: 1 },
    { term: 'indie hacker', weight: 1 },
    { term: 'saas founder', weight: 1 },
    { term: 'ux designer', weight: 1 },
    { term: 'product manager', weight: 1 },
    { term: 'web designer', weight: 1 },
    { term: 'qa engineer', weight: 1 },
    { term: 'software consultancy', weight: 1 },
    { term: 'app company', weight: 1 },
    { term: 'software agency', weight: 1 },
  ],
  'ai-forecasting': [
    { term: 'data scientist', weight: 2 },
    { term: 'machine learning', weight: 2 },
    { term: 'artificial intelligence', weight: 2 },
    { term: 'ai startup', weight: 2 },
    { term: 'data analyst', weight: 2 },
    { term: 'predictive analytics', weight: 2 },
    { term: 'ml engineer', weight: 2 },
    { term: 'ai researcher', weight: 2 },
    { term: 'forecasting', weight: 2 },
    { term: 'quant', weight: 1 },
    { term: 'big data', weight: 1 },
    { term: 'algorithmic trading', weight: 1 },
    { term: 'prompt engineer', weight: 1 },
    { term: 'data engineer', weight: 1 },
    { term: 'deep learning', weight: 1 },
    { term: 'ai consultant', weight: 1 },
    { term: 'llm', weight: 1 },
    { term: 'ai safety', weight: 1 },
    { term: 'ai developer', weight: 1 },
    { term: 'machine learning consultant', weight: 1 },
    { term: 'data science consultancy', weight: 1 },
    { term: 'ai company', weight: 1 },
    { term: 'chatbot developer', weight: 1 },
  ],
  'telecom-logistics': [
    { term: 'logistics', weight: 2 },
    { term: 'courier', weight: 2 },
    { term: 'delivery', weight: 2 },
    { term: 'supply chain', weight: 2 },
    { term: 'freight', weight: 2 },
    { term: 'messenger', weight: 2 },
    { term: 'postal service', weight: 2 },
    { term: 'telecom', weight: 2 },
    { term: 'freight forwarder', weight: 1 },
    { term: 'dispatcher', weight: 1 },
    { term: 'last mile delivery', weight: 1 },
    { term: 'broadband', weight: 1 },
    { term: 'removals', weight: 1 },
    { term: 'removal company', weight: 1 },
    { term: 'courier service', weight: 1 },
    { term: 'parcel delivery', weight: 1 },
    { term: 'same day delivery', weight: 1 },
    { term: 'warehouse', weight: 1 },
    { term: 'freight broker', weight: 1 },
    { term: 'isp', weight: 1 },
    { term: 'man with a van', weight: 1 },
    { term: 'pallet delivery', weight: 1 },
    { term: 'international shipping', weight: 1 },
    { term: 'delivery driver', weight: 1 },
    { term: 'courier company', weight: 1 },
  ],
  'cartography-geospatial': [
    { term: 'cartographer', weight: 2 },
    { term: 'gis', weight: 2 },
    { term: 'gis analyst', weight: 2 },
    { term: 'surveyor', weight: 2 },
    { term: 'land surveyor', weight: 2 },
    { term: 'mapping', weight: 2 },
    { term: 'mapmaker', weight: 2 },
    { term: 'gps', weight: 2 },
    { term: 'geospatial', weight: 2 },
    { term: 'remote sensing', weight: 1 },
    { term: 'navigation', weight: 1 },
    { term: 'topography', weight: 1 },
    { term: 'cartography', weight: 2 },
    { term: 'map', weight: 1 },
    { term: 'surveying', weight: 1 },
    { term: 'gis consultant', weight: 1 },
    { term: 'drone mapping', weight: 1 },
    { term: 'boundary surveyor', weight: 1 },
    { term: 'geomatics', weight: 1 },
    { term: 'satellite imagery', weight: 1 },
    { term: 'topographic survey', weight: 1 },
  ],
  'mining-resources': [
    { term: 'mining', weight: 2 },
    { term: 'miner', weight: 2 },
    { term: 'quarry', weight: 2 },
    { term: 'gold mining', weight: 2 },
    { term: 'coal', weight: 2 },
    { term: 'oil rig', weight: 2 },
    { term: 'oil and gas', weight: 2 },
    { term: 'drilling', weight: 1 },
    { term: 'prospector', weight: 1 },
    { term: 'geologist', weight: 1 },
    { term: 'roughneck', weight: 1 },
    { term: 'mining company', weight: 2 },
    { term: 'quarrying', weight: 1 },
    { term: 'gold miner', weight: 1 },
    { term: 'coal miner', weight: 1 },
    { term: 'petroleum engineer', weight: 1 },
    { term: 'mine surveyor', weight: 1 },
    { term: 'coal mining', weight: 1 },
    { term: 'mining engineer', weight: 1 },
    { term: 'quarry manager', weight: 1 },
    { term: 'mine worker', weight: 1 },
  ],
  'agriculture-food': [
    { term: 'farmer', weight: 2 },
    { term: 'farming', weight: 2 },
    { term: 'agriculture', weight: 2 },
    { term: 'rancher', weight: 2 },
    { term: 'agronomist', weight: 2 },
    { term: 'harvest', weight: 2 },
    { term: 'organic farm', weight: 2 },
    { term: 'food producer', weight: 2 },
    { term: 'dairy farm', weight: 1 },
    { term: 'market gardener', weight: 1 },
    { term: 'cattle', weight: 1 },
    { term: 'grain', weight: 1 },
    { term: 'farm equipment', weight: 1 },
    { term: 'farm shop', weight: 1 },
    { term: 'plant nursery', weight: 1 },
    { term: 'garden centre', weight: 1 },
    { term: 'agricultural contractor', weight: 1 },
    { term: 'arable farmer', weight: 1 },
    { term: 'sheep farmer', weight: 1 },
    { term: 'smallholding', weight: 1 },
    { term: 'crop farmer', weight: 1 },
    { term: 'pig farmer', weight: 1 },
    { term: 'farm manager', weight: 1 },
    { term: 'agricultural engineer', weight: 1 },
    { term: 'tractor driver', weight: 1 },
    { term: 'dairy farmer', weight: 1 },
  ],
  'forestry-conservation': [
    { term: 'forester', weight: 2 },
    { term: 'logging', weight: 2 },
    { term: 'lumber', weight: 2 },
    { term: 'timber', weight: 2 },
    { term: 'ranger', weight: 2 },
    { term: 'park ranger', weight: 2 },
    { term: 'arborist', weight: 2 },
    { term: 'conservationist', weight: 2 },
    { term: 'tree surgeon', weight: 1 },
    { term: 'wildlife biologist', weight: 1 },
    { term: 'forest service', weight: 1 },
    { term: 'lumberjack', weight: 1 },
    { term: 'national park', weight: 1 },
    { term: 'forestry contractor', weight: 1 },
    { term: 'woodland management', weight: 1 },
    { term: 'forest school', weight: 1 },
    { term: 'countryside ranger', weight: 1 },
    { term: 'gamekeeper', weight: 1 },
    { term: 'tree planting', weight: 1 },
    { term: 'forestry worker', weight: 1 },
    { term: 'conservation officer', weight: 1 },
    { term: 'tree work', weight: 1 },
    { term: 'tree felling', weight: 1 },
  ],
  'environment-climate': [
    { term: 'climate', weight: 2 },
    { term: 'sustainability', weight: 2 },
    { term: 'environmental consultant', weight: 2 },
    { term: 'environmental scientist', weight: 2 },
    { term: 'recycling', weight: 2 },
    { term: 'carbon offset', weight: 2 },
    { term: 'climate tech', weight: 2 },
    { term: 'ecologist', weight: 2 },
    { term: 'carbon accounting', weight: 1 },
    { term: 'green building', weight: 1 },
    { term: 'emissions', weight: 1 },
    { term: 'climate activist', weight: 1 },
    { term: 'net zero consultant', weight: 1 },
    { term: 'carbon consultant', weight: 1 },
    { term: 'esg consultant', weight: 1 },
    { term: 'environmental engineer', weight: 1 },
    { term: 'waste management', weight: 1 },
    { term: 'climate consultant', weight: 1 },
    { term: 'sustainability consultant', weight: 1 },
    { term: 'carbon footprint', weight: 1 },
    { term: 'environmental compliance', weight: 1 },
    { term: 'climate change', weight: 1 },
    { term: 'ecology survey', weight: 1 },
  ],
  'manufacturing-craft': [
    { term: 'manufacturer', weight: 2 },
    { term: 'factory', weight: 2 },
    { term: 'machinist', weight: 2 },
    { term: 'welder', weight: 2 },
    { term: 'blacksmith', weight: 2 },
    { term: 'craftsman', weight: 2 },
    { term: 'artisan', weight: 2 },
    { term: 'woodworker', weight: 1 },
    { term: 'metalworker', weight: 1 },
    { term: 'cnc operator', weight: 1 },
    { term: 'assembly line', weight: 1 },
    { term: 'potter', weight: 1 },
    { term: 'fabricator', weight: 1 },
    { term: 'sheet metal worker', weight: 1 },
    { term: 'toolmaker', weight: 1 },
    { term: 'factory worker', weight: 1 },
    { term: 'production manager', weight: 1 },
    { term: 'furniture maker', weight: 1 },
    { term: 'cabinet maker', weight: 1 },
    { term: 'welding', weight: 1 },
    { term: 'metal fabricator', weight: 1 },
    { term: 'cnc machinist', weight: 1 },
    { term: 'production operative', weight: 1 },
    { term: 'machine operator', weight: 1 },
    { term: 'factory manager', weight: 1 },
  ],
  'architecture-design': [
    { term: 'architect', weight: 2 },
    { term: 'interior designer', weight: 2 },
    { term: 'urban planner', weight: 2 },
    { term: 'landscape architect', weight: 1 },
    { term: 'drafter', weight: 1 },
    { term: 'design studio', weight: 1 },
    { term: 'building designer', weight: 1 },
    { term: 'architecture', weight: 2 },
    { term: 'interior design', weight: 2 },
    { term: 'architecture firm', weight: 1 },
    { term: 'town planner', weight: 1 },
    { term: 'interior decorator', weight: 1 },
    { term: 'residential architect', weight: 1 },
    { term: 'commercial architect', weight: 1 },
    { term: 'architectural technologist', weight: 1 },
    { term: 'landscape designer', weight: 1 },
    { term: 'cad technician', weight: 1 },
    { term: 'spatial design', weight: 1 },
    { term: 'kitchen designer', weight: 1 },
    { term: 'planning consultant', weight: 1 },
    { term: 'architectural designer', weight: 1 },
    { term: 'interior architecture', weight: 1 },
    { term: 'planning application', weight: 1 },
    { term: 'house designer', weight: 1 },
  ],
  textiles: [
    { term: 'tailor', weight: 2 },
    { term: 'weaver', weight: 2 },
    { term: 'textile', weight: 2 },
    { term: 'textile manufacturer', weight: 2 },
    { term: 'seamstress', weight: 2 },
    { term: 'fabric', weight: 2 },
    { term: 'dressmaker', weight: 2 },
    { term: 'knitter', weight: 1 },
    { term: 'yarn', weight: 1 },
    { term: 'spinning', weight: 1 },
    { term: 'embroiderer', weight: 1 },
    { term: 'upholsterer', weight: 1 },
    { term: 'alterations', weight: 1 },
    { term: 'bespoke tailor', weight: 1 },
    { term: 'curtain maker', weight: 1 },
    { term: 'milliner', weight: 1 },
    { term: 'haberdasher', weight: 1 },
    { term: 'pattern cutter', weight: 1 },
    { term: 'soft furnishings', weight: 1 },
    { term: 'weaving', weight: 1 },
    { term: 'textile designer', weight: 1 },
    { term: 'upholstery', weight: 1 },
    { term: 'costume maker', weight: 1 },
  ],
  'gems-jewelry': [
    { term: 'jeweler', weight: 2 },
    { term: 'jeweller', weight: 2 },
    { term: 'goldsmith', weight: 2 },
    { term: 'silversmith', weight: 2 },
    { term: 'diamond', weight: 2 },
    { term: 'gemstone', weight: 2 },
    { term: 'gemologist', weight: 2 },
    { term: 'lapidary', weight: 1 },
    { term: 'diamond dealer', weight: 1 },
    { term: 'engagement ring', weight: 1 },
    { term: 'luxury goods', weight: 1 },
    { term: 'pearl', weight: 1 },
    { term: 'jewelry', weight: 2 },
    { term: 'jewellery', weight: 2 },
    { term: 'jewellery designer', weight: 1 },
    { term: 'fine jewellery', weight: 1 },
    { term: 'gem dealer', weight: 1 },
    { term: 'diamond merchant', weight: 1 },
    { term: 'jewellery maker', weight: 1 },
    { term: 'gem cutter', weight: 1 },
    { term: 'silver jewellery', weight: 1 },
    { term: 'bespoke jewellery', weight: 1 },
    { term: 'gold dealer', weight: 1 },
  ],
  'beauty-fashion': [
    { term: 'fashion', weight: 2 },
    { term: 'fashion designer', weight: 2 },
    { term: 'model', weight: 2 },
    { term: 'modeling agency', weight: 2 },
    { term: 'makeup artist', weight: 2 },
    { term: 'cosmetics', weight: 2 },
    { term: 'stylist', weight: 2 },
    { term: 'hairdresser', weight: 2 },
    { term: 'barber', weight: 2 },
    { term: 'salon', weight: 2 },
    { term: 'beauty salon', weight: 2 },
    { term: 'nail technician', weight: 1 },
    { term: 'perfume', weight: 1 },
    { term: 'runway', weight: 1 },
    { term: 'barbershop', weight: 1 },
    { term: 'nail bar', weight: 1 },
    { term: 'tattoo studio', weight: 1 },
    { term: 'tattoo artist', weight: 1 },
    { term: 'beautician', weight: 2 },
    { term: 'hair salon', weight: 1 },
    { term: 'beauty therapist', weight: 1 },
    { term: 'clothing brand', weight: 1 },
    { term: 'lash technician', weight: 1 },
    { term: 'mobile hairdresser', weight: 1 },
    { term: 'bridal makeup', weight: 1 },
    { term: 'piercing studio', weight: 1 },
    { term: 'tanning salon', weight: 1 },
    { term: 'hair extensions', weight: 1 },
  ],
  'healthcare-pharma': [
    { term: 'doctor', weight: 2 },
    { term: 'nurse', weight: 2 },
    { term: 'dentist', weight: 2 },
    { term: 'hospital', weight: 2 },
    { term: 'pharmacist', weight: 2 },
    { term: 'pharmacy', weight: 2 },
    { term: 'surgeon', weight: 2 },
    { term: 'physician', weight: 2 },
    { term: 'clinic', weight: 2 },
    { term: 'pharma', weight: 2 },
    { term: 'paramedic', weight: 2 },
    { term: 'gp', weight: 1 },
    { term: 'pediatrician', weight: 1 },
    { term: 'dermatologist', weight: 1 },
    { term: 'caregiver', weight: 1 },
    { term: 'nursing home', weight: 1 },
    { term: 'general practitioner', weight: 1 },
    { term: 'family doctor', weight: 1 },
    { term: 'physiotherapist', weight: 1 },
    { term: 'physio', weight: 1 },
    { term: 'radiographer', weight: 1 },
    { term: 'occupational therapist', weight: 1 },
    { term: 'chemist', weight: 1 },
    { term: 'dental hygienist', weight: 1 },
    { term: 'chiropractor', weight: 1 },
    { term: 'speech therapist', weight: 1 },
    { term: 'fertility clinic', weight: 1 },
    { term: 'private gp', weight: 1 },
    { term: 'phlebotomist', weight: 1 },
  ],
  'mental-health': [
    { term: 'therapist', weight: 2 },
    { term: 'therapy', weight: 2 },
    { term: 'psychologist', weight: 2 },
    { term: 'psychiatrist', weight: 2 },
    { term: 'counselor', weight: 2 },
    { term: 'psychotherapist', weight: 2 },
    { term: 'mental health', weight: 2 },
    { term: 'counselling', weight: 1 },
    { term: 'counseling', weight: 1 },
    { term: 'anxiety coach', weight: 1 },
    { term: 'trauma therapist', weight: 1 },
    { term: 'grief counselor', weight: 1 },
    { term: 'addiction counselor', weight: 1 },
    { term: 'counsellor', weight: 2 },
    { term: 'clinical psychologist', weight: 1 },
    { term: 'cbt', weight: 1 },
    { term: 'hypnotherapist', weight: 1 },
    { term: 'psychology', weight: 1 },
    { term: 'child psychologist', weight: 1 },
    { term: 'online therapy', weight: 1 },
    { term: 'bereavement counsellor', weight: 1 },
    { term: 'mental health nurse', weight: 1 },
    { term: 'psychiatry', weight: 1 },
    { term: 'psychotherapy', weight: 1 },
  ],
  'sleep-recovery': [
    { term: 'sleep', weight: 2 },
    { term: 'mattress', weight: 2 },
    { term: 'sleep tracker', weight: 2 },
    { term: 'sleep clinic', weight: 2 },
    { term: 'insomnia', weight: 2 },
    { term: 'bedding', weight: 1 },
    { term: 'pillow', weight: 1 },
    { term: 'sleep coach', weight: 1 },
    { term: 'melatonin', weight: 1 },
    { term: 'white noise', weight: 1 },
    { term: 'sleep apnea', weight: 1 },
    { term: 'recovery tech', weight: 1 },
    { term: 'mattress store', weight: 1 },
    { term: 'sleep specialist', weight: 1 },
    { term: 'sleep consultant', weight: 1 },
    { term: 'snoring', weight: 1 },
    { term: 'cpap', weight: 1 },
    { term: 'bed shop', weight: 1 },
    { term: 'weighted blanket', weight: 1 },
    { term: 'sleep tech', weight: 1 },
    { term: 'insomnia treatment', weight: 1 },
  ],
  'wellness-mind': [
    { term: 'yoga', weight: 2 },
    { term: 'yoga teacher', weight: 2 },
    { term: 'meditation', weight: 2 },
    { term: 'mindfulness', weight: 2 },
    { term: 'wellness', weight: 2 },
    { term: 'spa', weight: 2 },
    { term: 'massage therapist', weight: 2 },
    { term: 'retreat', weight: 2 },
    { term: 'life coach', weight: 1 },
    { term: 'breathwork', weight: 1 },
    { term: 'pilates', weight: 1 },
    { term: 'holistic healer', weight: 1 },
    { term: 'reiki', weight: 1 },
    { term: 'ayurveda', weight: 1 },
    { term: 'yoga studio', weight: 1 },
    { term: 'massage', weight: 1 },
    { term: 'wellness coach', weight: 1 },
    { term: 'meditation teacher', weight: 1 },
    { term: 'acupuncturist', weight: 1 },
    { term: 'massage therapy', weight: 1 },
    { term: 'holistic therapist', weight: 1 },
    { term: 'yoga retreat', weight: 1 },
    { term: 'spa day', weight: 1 },
    { term: 'pilates instructor', weight: 1 },
  ],
  'biotech-longevity': [
    { term: 'biotech', weight: 2 },
    { term: 'biotech startup', weight: 2 },
    { term: 'longevity', weight: 2 },
    { term: 'longevity clinic', weight: 2 },
    { term: 'geneticist', weight: 2 },
    { term: 'gene therapy', weight: 2 },
    { term: 'genomics', weight: 2 },
    { term: 'anti aging', weight: 2 },
    { term: 'biohacker', weight: 1 },
    { term: 'biohacking', weight: 1 },
    { term: 'life extension', weight: 1 },
    { term: 'stem cell', weight: 1 },
    { term: 'crispr', weight: 1 },
    { term: 'biotech company', weight: 1 },
    { term: 'bioinformatician', weight: 1 },
    { term: 'genetic testing', weight: 1 },
    { term: 'biomedical scientist', weight: 1 },
    { term: 'cell therapy', weight: 1 },
    { term: 'clinical research', weight: 1 },
    { term: 'dna sequencing', weight: 1 },
    { term: 'microbiologist', weight: 1 },
  ],
  'occult-esoteric': [
    { term: 'astrologer', weight: 2 },
    { term: 'astrology', weight: 2 },
    { term: 'tarot', weight: 2 },
    { term: 'tarot reader', weight: 2 },
    { term: 'psychic', weight: 2 },
    { term: 'horoscope', weight: 2 },
    { term: 'occult', weight: 2 },
    { term: 'medium', weight: 1 },
    { term: 'palm reader', weight: 1 },
    { term: 'witch', weight: 1 },
    { term: 'numerologist', weight: 1 },
    { term: 'crystal healer', weight: 1 },
    { term: 'fortune teller', weight: 1 },
    { term: 'esoteric shop', weight: 1 },
    { term: 'clairvoyant', weight: 1 },
    { term: 'astrology reading', weight: 1 },
    { term: 'tarot reading', weight: 1 },
    { term: 'psychic medium', weight: 1 },
    { term: 'spiritual healer', weight: 1 },
    { term: 'zodiac', weight: 1 },
    { term: 'new age shop', weight: 1 },
    { term: 'birth chart', weight: 1 },
    { term: 'crystal shop', weight: 1 },
    { term: 'horoscope reading', weight: 1 },
    { term: 'palmistry', weight: 1 },
  ],
  faith: [
    { term: 'church', weight: 2 },
    { term: 'mosque', weight: 2 },
    { term: 'temple', weight: 2 },
    { term: 'synagogue', weight: 2 },
    { term: 'chapel', weight: 2 },
    { term: 'religion', weight: 2 },
    { term: 'priest', weight: 2 },
    { term: 'imam', weight: 2 },
    { term: 'pastor', weight: 2 },
    { term: 'rabbi', weight: 2 },
    { term: 'vicar', weight: 2 },
    { term: 'monk', weight: 1 },
    { term: 'nun', weight: 1 },
    { term: 'congregation', weight: 1 },
    { term: 'parish', weight: 1 },
    { term: 'ministry', weight: 1 },
    { term: 'worship', weight: 1 },
    { term: 'cathedral', weight: 1 },
    { term: 'bishop', weight: 1 },
    { term: 'cleric', weight: 1 },
    { term: 'gurdwara', weight: 1 },
    { term: 'monastery', weight: 1 },
    { term: 'abbey', weight: 1 },
    { term: 'shrine', weight: 1 },
    { term: 'convent', weight: 1 },
    { term: 'mandir', weight: 1 },
    { term: 'minster', weight: 1 },
  ],
  'publishing-media': [
    { term: 'poet', weight: 2 },
    { term: 'writer', weight: 2 },
    { term: 'author', weight: 2 },
    { term: 'journalist', weight: 2 },
    { term: 'novelist', weight: 2 },
    { term: 'copywriter', weight: 2 },
    { term: 'editor', weight: 2 },
    { term: 'publisher', weight: 2 },
    { term: 'reporter', weight: 2 },
    { term: 'newspaper', weight: 2 },
    { term: 'magazine', weight: 2 },
    { term: 'bard', weight: 1 },
    { term: 'blogger', weight: 1 },
    { term: 'screenwriter', weight: 1 },
    { term: 'storyteller', weight: 1 },
    { term: 'columnist', weight: 1 },
    { term: 'playwright', weight: 1 },
    { term: 'freelance writer', weight: 1 },
    { term: 'influencer', weight: 1 },
    { term: 'podcaster', weight: 1 },
    { term: 'content creator', weight: 1 },
    { term: 'ghostwriter', weight: 1 },
    { term: 'technical writer', weight: 1 },
    { term: 'proofreader', weight: 1 },
    { term: 'literary agent', weight: 1 },
    { term: 'digital marketer', weight: 1 },
    { term: 'growth marketer', weight: 1 },
    { term: 'seo consultant', weight: 1 },
  ],
  'music-arts': [
    { term: 'musician', weight: 2 },
    { term: 'singer', weight: 2 },
    { term: 'composer', weight: 2 },
    { term: 'band', weight: 2 },
    { term: 'dj', weight: 2 },
    { term: 'orchestra', weight: 2 },
    { term: 'painter', weight: 2 },
    { term: 'artist', weight: 2 },
    { term: 'dancer', weight: 2 },
    { term: 'actor', weight: 2 },
    { term: 'theater', weight: 2 },
    { term: 'theatre', weight: 2 },
    { term: 'concert', weight: 2 },
    { term: 'sculptor', weight: 1 },
    { term: 'opera', weight: 1 },
    { term: 'guitarist', weight: 1 },
    { term: 'record label', weight: 1 },
    { term: 'filmmaker', weight: 1 },
    { term: 'music producer', weight: 1 },
    { term: 'singer songwriter', weight: 1 },
    { term: 'session musician', weight: 1 },
    { term: 'comedian', weight: 1 },
    { term: 'voice actor', weight: 1 },
    { term: 'violinist', weight: 1 },
    { term: 'tribute band', weight: 1 },
    { term: 'choir', weight: 1 },
    { term: 'recording studio', weight: 1 },
    { term: 'dj hire', weight: 1 },
  ],
  'gaming-entertainment': [
    { term: 'game developer', weight: 2 },
    { term: 'game designer', weight: 2 },
    { term: 'game studio', weight: 2 },
    { term: 'video game', weight: 2 },
    { term: 'esports', weight: 2 },
    { term: 'streamer', weight: 2 },
    { term: 'board game', weight: 1 },
    { term: 'rpg', weight: 1 },
    { term: 'game publisher', weight: 1 },
    { term: 'dungeon master', weight: 1 },
    { term: 'arcade', weight: 1 },
    { term: 'cosplay', weight: 1 },
    { term: 'esports player', weight: 1 },
    { term: 'pro gamer', weight: 1 },
    { term: 'gamer', weight: 1 },
    { term: 'indie game developer', weight: 1 },
    { term: 'game tester', weight: 1 },
    { term: 'game artist', weight: 1 },
    { term: 'live streamer', weight: 1 },
    { term: 'mobile game developer', weight: 1 },
    { term: 'games company', weight: 1 },
    { term: 'esports team', weight: 1 },
  ],
  'sports-athletics': [
    { term: 'athlete', weight: 2 },
    { term: 'gym', weight: 2 },
    { term: 'personal trainer', weight: 2 },
    { term: 'football', weight: 2 },
    { term: 'football club', weight: 2 },
    { term: 'basketball', weight: 2 },
    { term: 'coach', weight: 2 },
    { term: 'sports team', weight: 2 },
    { term: 'olympics', weight: 1 },
    { term: 'marathon', weight: 1 },
    { term: 'runner', weight: 1 },
    { term: 'triathlete', weight: 1 },
    { term: 'boxer', weight: 1 },
    { term: 'wrestler', weight: 1 },
    { term: 'crossfit box', weight: 1 },
    { term: 'dojo', weight: 1 },
    { term: 'boxing club', weight: 1 },
    { term: 'martial arts', weight: 1 },
    { term: 'rugby', weight: 1 },
    { term: 'cricket', weight: 1 },
    { term: 'tennis', weight: 1 },
    { term: 'golf club', weight: 1 },
    { term: 'football academy', weight: 1 },
    { term: 'athletics', weight: 1 },
    { term: 'netball club', weight: 1 },
    { term: 'fitness instructor', weight: 1 },
    { term: 'personal training', weight: 1 },
  ],
  'wine-hospitality': [
    { term: 'winemaker', weight: 2 },
    { term: 'winery', weight: 2 },
    { term: 'vineyard', weight: 2 },
    { term: 'brewer', weight: 2 },
    { term: 'brewery', weight: 2 },
    { term: 'hotel', weight: 2 },
    { term: 'bartender', weight: 2 },
    { term: 'distiller', weight: 1 },
    { term: 'innkeeper', weight: 1 },
    { term: 'bed and breakfast', weight: 1 },
    { term: 'distillery', weight: 2 },
    { term: 'hotelier', weight: 2 },
    { term: 'wine bar', weight: 1 },
    { term: 'wine merchant', weight: 1 },
    { term: 'wine tasting', weight: 1 },
    { term: 'craft beer', weight: 1 },
    { term: 'craft brewery', weight: 1 },
    { term: 'brewpub', weight: 1 },
    { term: 'cellar door', weight: 1 },
    { term: 'guest house', weight: 1 },
    { term: 'boutique hotel', weight: 1 },
    { term: 'b&b', weight: 1 },
    { term: 'viticulturist', weight: 1 },
    { term: 'winemaking', weight: 1 },
    { term: 'microbrewery', weight: 1 },
    { term: 'wine club', weight: 1 },
    { term: 'hotel manager', weight: 1 },
  ],
  'travel-tourism': [
    { term: 'travel agent', weight: 2 },
    { term: 'travel agency', weight: 2 },
    { term: 'tour guide', weight: 2 },
    { term: 'tour operator', weight: 2 },
    { term: 'tourism', weight: 2 },
    { term: 'travel blogger', weight: 1 },
    { term: 'vacation rental', weight: 1 },
    { term: 'safari', weight: 1 },
    { term: 'ecotourism', weight: 1 },
    { term: 'destination marketing', weight: 1 },
    { term: 'cruise line', weight: 1 },
    { term: 'travel', weight: 1 },
    { term: 'holiday', weight: 1 },
    { term: 'vacation', weight: 1 },
    { term: 'hostel', weight: 1 },
    { term: 'resort', weight: 1 },
    { term: 'travel consultant', weight: 1 },
    { term: 'holiday let', weight: 1 },
    { term: 'tour company', weight: 1 },
    { term: 'walking tour', weight: 1 },
    { term: 'cruise agent', weight: 1 },
    { term: 'adventure tour', weight: 1 },
  ],
  'real-estate-home': [
    { term: 'realtor', weight: 2 },
    { term: 'real estate agent', weight: 2 },
    { term: 'estate agent', weight: 2 },
    { term: 'letting agent', weight: 2 },
    { term: 'property developer', weight: 2 },
    { term: 'landlord', weight: 2 },
    { term: 'property management', weight: 2 },
    { term: 'mortgage broker', weight: 1 },
    { term: 'home staging', weight: 1 },
    { term: 'realty', weight: 1 },
    { term: 'property investor', weight: 1 },
    { term: 'conveyancer', weight: 1 },
    { term: 'home inspector', weight: 1 },
    { term: 'real estate', weight: 2 },
    { term: 'property', weight: 1 },
    { term: 'property manager', weight: 1 },
    { term: 'lettings', weight: 1 },
    { term: 'estate agency', weight: 1 },
    { term: 'conveyancing', weight: 1 },
    { term: 'commercial property', weight: 1 },
    { term: 'buy to let', weight: 1 },
    { term: 'property agency', weight: 1 },
    { term: 'online estate agent', weight: 1 },
    { term: 'rental agency', weight: 1 },
    { term: 'new build homes', weight: 1 },
    { term: 'house valuation', weight: 1 },
  ],
  petcare: [
    { term: 'vet', weight: 2 },
    { term: 'veterinarian', weight: 2 },
    { term: 'dog groomer', weight: 2 },
    { term: 'pet sitter', weight: 2 },
    { term: 'dog walker', weight: 2 },
    { term: 'pet shop', weight: 2 },
    { term: 'animal shelter', weight: 2 },
    { term: 'dog trainer', weight: 2 },
    { term: 'kennel', weight: 1 },
    { term: 'cat breeder', weight: 1 },
    { term: 'pet food', weight: 1 },
    { term: 'horse trainer', weight: 1 },
    { term: 'stable', weight: 1 },
    { term: 'farrier', weight: 1 },
    { term: 'vet nurse', weight: 1 },
    { term: 'veterinary nurse', weight: 1 },
    { term: 'animal hospital', weight: 1 },
    { term: 'veterinary clinic', weight: 1 },
    { term: 'pet boarding', weight: 1 },
    { term: 'cattery', weight: 1 },
    { term: 'doggy daycare', weight: 1 },
    { term: 'pet groomer', weight: 1 },
    { term: 'pet store', weight: 2 },
    { term: 'dog breeder', weight: 1 },
    { term: 'farm vet', weight: 1 },
    { term: 'dog boarding', weight: 1 },
    { term: 'pet taxi', weight: 1 },
    { term: 'cat sitter', weight: 1 },
  ],
  'finance-commerce': [
    { term: 'banker', weight: 2 },
    { term: 'accountant', weight: 2 },
    { term: 'investor', weight: 2 },
    { term: 'hedge fund', weight: 2 },
    { term: 'investment bank', weight: 2 },
    { term: 'financial advisor', weight: 2 },
    { term: 'stockbroker', weight: 2 },
    { term: 'fintech', weight: 2 },
    { term: 'trader', weight: 2 },
    { term: 'wealth manager', weight: 2 },
    { term: 'merchant', weight: 2 },
    { term: 'private equity', weight: 1 },
    { term: 'bookkeeper', weight: 1 },
    { term: 'cfo', weight: 1 },
    { term: 'tax advisor', weight: 1 },
    { term: 'auditor', weight: 1 },
    { term: 'chartered accountant', weight: 2 },
    { term: 'ifa', weight: 1 },
    { term: 'independent financial adviser', weight: 1 },
    { term: 'cpa', weight: 1 },
    { term: 'accountancy', weight: 1 },
    { term: 'financial planner', weight: 1 },
    { term: 'investment manager', weight: 1 },
    { term: 'portfolio manager', weight: 1 },
    { term: 'fund manager', weight: 1 },
    { term: 'forex', weight: 1 },
    { term: 'crypto', weight: 1 },
    { term: 'stocks and shares', weight: 1 },
  ],
  insurance: [
    { term: 'insurance agent', weight: 2 },
    { term: 'insurance broker', weight: 2 },
    { term: 'insurance company', weight: 2 },
    { term: 'insurer', weight: 2 },
    { term: 'underwriter', weight: 2 },
    { term: 'actuary', weight: 2 },
    { term: 'life insurance', weight: 2 },
    { term: 'claims adjuster', weight: 1 },
    { term: 'health insurance', weight: 1 },
    { term: 'car insurance', weight: 1 },
    { term: 'reinsurance', weight: 1 },
    { term: 'risk manager', weight: 1 },
    { term: 'insurance', weight: 2 },
    { term: 'home insurance', weight: 1 },
    { term: 'travel insurance', weight: 1 },
    { term: 'cyber insurance', weight: 1 },
    { term: 'loss adjuster', weight: 1 },
    { term: 'business insurance', weight: 1 },
    { term: 'landlord insurance', weight: 1 },
    { term: 'public liability insurance', weight: 1 },
    { term: 'life assurance', weight: 1 },
  ],
  'legal-justice': [
    { term: 'lawyer', weight: 2 },
    { term: 'solicitor', weight: 2 },
    { term: 'attorney', weight: 2 },
    { term: 'barrister', weight: 2 },
    { term: 'judge', weight: 2 },
    { term: 'law firm', weight: 2 },
    { term: 'paralegal', weight: 1 },
    { term: 'notary', weight: 1 },
    { term: 'prosecutor', weight: 1 },
    { term: 'public defender', weight: 1 },
    { term: 'compliance officer', weight: 1 },
    { term: 'legal counsel', weight: 1 },
    { term: 'litigator', weight: 1 },
    { term: 'magistrate', weight: 1 },
    { term: 'police officer', weight: 1 },
    { term: 'detective', weight: 1 },
    { term: 'qc', weight: 1 },
    { term: 'family lawyer', weight: 1 },
    { term: 'criminal lawyer', weight: 1 },
    { term: 'immigration lawyer', weight: 1 },
    { term: 'legal advice', weight: 1 },
    { term: 'law practice', weight: 1 },
    { term: 'legal aid', weight: 1 },
    { term: 'criminal defence', weight: 1 },
    { term: 'commercial lawyer', weight: 1 },
  ],
  leadership: [
    { term: 'mayor', weight: 2 },
    { term: 'president', weight: 2 },
    { term: 'politician', weight: 2 },
    { term: 'senator', weight: 2 },
    { term: 'governor', weight: 2 },
    { term: 'government', weight: 2 },
    { term: 'civil servant', weight: 2 },
    { term: 'diplomat', weight: 2 },
    { term: 'prime minister', weight: 2 },
    { term: 'public administration', weight: 2 },
    { term: 'city council', weight: 1 },
    { term: 'ambassador', weight: 1 },
    { term: 'campaign manager', weight: 1 },
    { term: 'policy advisor', weight: 1 },
    { term: 'minister', weight: 1 },
    { term: 'councillor', weight: 1 },
    { term: 'mp', weight: 1 },
    { term: 'congressman', weight: 1 },
    { term: 'local government', weight: 1 },
    { term: 'town hall', weight: 1 },
    { term: 'civil service', weight: 1 },
    { term: 'parish council', weight: 1 },
    { term: 'local council', weight: 1 },
  ],
  education: [
    { term: 'teacher', weight: 2 },
    { term: 'professor', weight: 2 },
    { term: 'university', weight: 2 },
    { term: 'school', weight: 2 },
    { term: 'tutor', weight: 2 },
    { term: 'researcher', weight: 2 },
    { term: 'lecturer', weight: 2 },
    { term: 'academic', weight: 2 },
    { term: 'student', weight: 1 },
    { term: 'librarian', weight: 1 },
    { term: 'phd', weight: 1 },
    { term: 'online course', weight: 1 },
    { term: 'kindergarten', weight: 1 },
    { term: 'principal', weight: 1 },
    { term: 'edtech', weight: 1 },
    { term: 'college', weight: 2 },
    { term: 'academy', weight: 1 },
    { term: 'mooc', weight: 1 },
    { term: 'bootcamp', weight: 1 },
    { term: 'music teacher', weight: 1 },
    { term: 'teaching assistant', weight: 1 },
    { term: 'high school', weight: 1 },
    { term: 'primary school', weight: 1 },
    { term: 'tutoring', weight: 1 },
    { term: 'piano teacher', weight: 1 },
    { term: 'sixth form', weight: 1 },
    { term: 'grammar school', weight: 1 },
    { term: 'private tutor', weight: 1 },
  ],
  'philosophy-ethics': [
    { term: 'philosopher', weight: 2 },
    { term: 'ethicist', weight: 2 },
    { term: 'think tank', weight: 2 },
    { term: 'ethics committee', weight: 1 },
    { term: 'standards body', weight: 1 },
    { term: 'bioethicist', weight: 1 },
    { term: 'logician', weight: 1 },
    { term: 'moral philosopher', weight: 1 },
    { term: 'policy institute', weight: 1 },
    { term: 'board of ethics', weight: 1 },
    { term: 'futurist', weight: 1 },
    { term: 'philosophy', weight: 1 },
    { term: 'ethics consultant', weight: 1 },
    { term: 'academic philosopher', weight: 1 },
    { term: 'bioethics', weight: 1 },
    { term: 'ethics', weight: 1 },
    { term: 'ai ethics', weight: 1 },
    { term: 'business ethics', weight: 1 },
    { term: 'medical ethics', weight: 1 },
  ],
  'history-archives': [
    { term: 'historian', weight: 2 },
    { term: 'archivist', weight: 2 },
    { term: 'archive', weight: 2 },
    { term: 'records office', weight: 2 },
    { term: 'librarian', weight: 2 },
    { term: 'curator', weight: 2 },
    { term: 'manuscript', weight: 1 },
    { term: 'museum collection', weight: 1 },
    { term: 'special collections', weight: 1 },
    { term: 'record keeping', weight: 1 },
  ],
  'genealogy-ancestry': [
    { term: 'genealogist', weight: 2 },
    { term: 'dna test', weight: 2 },
    { term: 'ancestry research', weight: 2 },
    { term: 'family tree', weight: 2 },
    { term: 'heritage', weight: 2 },
    { term: 'family historian', weight: 1 },
    { term: 'lineage society', weight: 1 },
    { term: 'heraldry', weight: 1 },
    { term: 'museum', weight: 1 },
    { term: 'family history', weight: 1 },
    { term: 'local historian', weight: 1 },
    { term: 'heir hunter', weight: 1 },
    { term: 'surname research', weight: 1 },
    { term: 'dna ancestry', weight: 1 },
    { term: 'coat of arms', weight: 1 },
    { term: 'birth records', weight: 1 },
  ],
  'startups-venture': [
    { term: 'entrepreneur', weight: 2 },
    { term: 'business owner', weight: 2 },
    { term: 'founder', weight: 2 },
    { term: 'startup founder', weight: 2 },
    { term: 'startup', weight: 2 },
    { term: 'small business', weight: 2 },
    { term: 'venture capitalist', weight: 1 },
    { term: 'solopreneur', weight: 1 },
    { term: 'incubator', weight: 1 },
    { term: 'angel investor', weight: 1 },
    { term: 'side hustle', weight: 1 },
    { term: 'accelerator', weight: 1 },
    { term: 'serial entrepreneur', weight: 1 },
    { term: 'tech startup', weight: 1 },
    { term: 'co-founder', weight: 1 },
    { term: 'bootstrapper', weight: 1 },
    { term: 'female founder', weight: 1 },
    { term: 'tech founder', weight: 1 },
    { term: 'small business owner', weight: 1 },
    { term: 'tech entrepreneur', weight: 1 },
  ],
  'disaster-resilience': [
    { term: 'firefighter', weight: 2 },
    { term: 'fire department', weight: 2 },
    { term: 'emergency management', weight: 2 },
    { term: 'emergency planner', weight: 2 },
    { term: 'search and rescue', weight: 2 },
    { term: 'disaster relief', weight: 2 },
    { term: 'civil defense', weight: 1 },
    { term: 'red cross', weight: 1 },
    { term: 'business continuity', weight: 1 },
    { term: 'flood response', weight: 1 },
    { term: 'coastguard', weight: 1 },
    { term: 'resilience consultant', weight: 1 },
    { term: 'coast guard', weight: 1 },
    { term: 'emergency services', weight: 1 },
    { term: 'flood defence', weight: 1 },
    { term: 'disaster recovery', weight: 1 },
    { term: 'mountain rescue', weight: 1 },
    { term: 'fire risk assessment', weight: 1 },
    { term: 'emergency response', weight: 1 },
    { term: 'fire safety', weight: 1 },
    { term: 'flood restoration', weight: 1 },
    { term: 'emergency planning', weight: 1 },
  ],
  'funerary-memorial': [
    { term: 'funeral director', weight: 2 },
    { term: 'undertaker', weight: 2 },
    { term: 'mortician', weight: 2 },
    { term: 'cemetery', weight: 2 },
    { term: 'crematorium', weight: 2 },
    { term: 'funeral home', weight: 2 },
    { term: 'memorial service', weight: 1 },
    { term: 'gravestone', weight: 1 },
    { term: 'headstone', weight: 1 },
    { term: 'hospice', weight: 1 },
    { term: 'obituary', weight: 1 },
    { term: 'embalmer', weight: 1 },
    { term: 'bereavement', weight: 1 },
    { term: 'funeral celebrant', weight: 1 },
    { term: 'funeral arranger', weight: 1 },
    { term: 'memorial mason', weight: 1 },
    { term: 'grave digger', weight: 1 },
    { term: 'pet crematorium', weight: 1 },
    { term: 'direct cremation', weight: 1 },
    { term: 'natural burial', weight: 1 },
    { term: 'funeral plans', weight: 1 },
    { term: 'woodland burial', weight: 1 },
  ],
  horology: [
    { term: 'watchmaker', weight: 2 },
    { term: 'clockmaker', weight: 2 },
    { term: 'watch', weight: 2 },
    { term: 'watch repair', weight: 2 },
    { term: 'horologist', weight: 2 },
    { term: 'timepiece', weight: 2 },
    { term: 'luxury watch', weight: 2 },
    { term: 'calendar app', weight: 2 },
    { term: 'chronometer', weight: 1 },
    { term: 'smartwatch', weight: 1 },
    { term: 'scheduling software', weight: 1 },
    { term: 'atomic clock', weight: 1 },
    { term: 'watch dealer', weight: 1 },
    { term: 'watch collector', weight: 1 },
    { term: 'clock repair', weight: 1 },
    { term: 'watch servicing', weight: 1 },
    { term: 'horology', weight: 1 },
    { term: 'timekeeping', weight: 1 },
    { term: 'watch restoration', weight: 1 },
    { term: 'antique clock', weight: 1 },
    { term: 'watch valuation', weight: 1 },
    { term: 'watch shop', weight: 1 },
    { term: 'watch battery replacement', weight: 1 },
  ],
  'photography-optics': [
    { term: 'photographer', weight: 2 },
    { term: 'photography', weight: 2 },
    { term: 'videographer', weight: 2 },
    { term: 'camera', weight: 2 },
    { term: 'lens', weight: 2 },
    { term: 'cinematographer', weight: 2 },
    { term: 'optician', weight: 2 },
    { term: 'optometrist', weight: 2 },
    { term: 'eyewear', weight: 2 },
    { term: 'photo studio', weight: 1 },
    { term: 'wedding photographer', weight: 1 },
    { term: 'drone photographer', weight: 1 },
    { term: 'binoculars', weight: 1 },
    { term: 'microscope', weight: 1 },
    { term: 'photo editor', weight: 1 },
    { term: 'portrait photographer', weight: 1 },
    { term: 'commercial photographer', weight: 1 },
    { term: 'videography', weight: 1 },
    { term: 'camera operator', weight: 1 },
    { term: 'event photographer', weight: 1 },
    { term: 'family photographer', weight: 1 },
    { term: 'photo restoration', weight: 1 },
    { term: 'headshot photographer', weight: 1 },
    { term: 'newborn photographer', weight: 1 },
    { term: 'aerial photographer', weight: 1 },
    { term: 'wedding videographer', weight: 1 },
  ],
  femtech: [
    { term: 'femtech', weight: 2 },
    { term: 'femtech startup', weight: 2 },
    { term: 'period tracker', weight: 2 },
    { term: 'fertility app', weight: 2 },
    { term: 'pregnancy app', weight: 2 },
    { term: 'menstrual health', weight: 2 },
    { term: 'menopause', weight: 1 },
    { term: 'ovulation tracker', weight: 1 },
    { term: 'breastfeeding', weight: 1 },
    { term: 'pelvic health', weight: 1 },
    { term: "women's health", weight: 1 },
    { term: 'menstrual cup', weight: 1 },
    { term: 'hormone health', weight: 1 },
    { term: 'postpartum', weight: 1 },
    { term: 'period products', weight: 1 },
    { term: 'fertility tracker', weight: 1 },
    { term: "women's health app", weight: 1 },
    { term: 'menopause clinic', weight: 1 },
    { term: 'endometriosis', weight: 1 },
  ],
  'wedding-family': [
    { term: 'wedding planner', weight: 2 },
    { term: 'bridal shop', weight: 2 },
    { term: 'wedding venue', weight: 2 },
    { term: 'midwife', weight: 2 },
    { term: 'doula', weight: 2 },
    { term: 'maternity', weight: 2 },
    { term: 'nanny', weight: 2 },
    { term: 'daycare', weight: 2 },
    { term: 'marriage celebrant', weight: 1 },
    { term: 'baby shower', weight: 1 },
    { term: 'christening', weight: 1 },
    { term: 'surrogacy', weight: 1 },
    { term: 'nursery', weight: 1 },
    { term: 'childminder', weight: 1 },
    { term: 'nursery school', weight: 1 },
    { term: 'au pair', weight: 1 },
    { term: 'babysitter', weight: 1 },
    { term: 'maternity nurse', weight: 1 },
    { term: 'wedding cake', weight: 1 },
    { term: 'wedding dress', weight: 1 },
    { term: 'wedding car', weight: 1 },
    { term: 'wedding florist', weight: 1 },
  ],
  'dating-relationships': [
    { term: 'dating app', weight: 2 },
    { term: 'dating site', weight: 2 },
    { term: 'online dating', weight: 2 },
    { term: 'matchmaker', weight: 2 },
    { term: 'matchmaking', weight: 2 },
    { term: 'dating coach', weight: 2 },
    { term: 'relationship counselor', weight: 2 },
    { term: 'speed dating', weight: 1 },
    { term: 'singles events', weight: 1 },
    { term: 'marriage counselor', weight: 1 },
    { term: 'love coach', weight: 1 },
    { term: 'couples therapy', weight: 1 },
    { term: 'dating agency', weight: 1 },
    { term: 'relationship coach', weight: 1 },
    { term: 'matchmaking agency', weight: 1 },
    { term: 'dating consultant', weight: 1 },
  ],
  'automotive-mobility': [
    { term: 'mechanic', weight: 2 },
    { term: 'garage', weight: 2 },
    { term: 'car dealership', weight: 2 },
    { term: 'auto repair', weight: 2 },
    { term: 'driving school', weight: 2 },
    { term: 'taxi', weight: 1 },
    { term: 'haulage', weight: 1 },
    { term: 'tyre shop', weight: 1 },
    { term: 'panel beater', weight: 1 },
    { term: 'valet parking', weight: 1 },
    { term: 'car rental', weight: 1 },
    { term: 'chauffeur', weight: 1 },
    { term: 'fleet manager', weight: 1 },
    { term: 'van driver', weight: 1 },
    { term: 'auto electrician', weight: 1 },
    { term: 'trucking', weight: 2 },
    { term: 'mot centre', weight: 1 },
    { term: 'tyre fitter', weight: 1 },
    { term: 'detailer', weight: 1 },
    { term: 'windscreen repair', weight: 1 },
    { term: 'breakdown recovery', weight: 1 },
    { term: 'van hire', weight: 1 },
    { term: 'cab', weight: 1 },
    { term: 'minicab', weight: 1 },
    { term: 'rideshare driver', weight: 1 },
    { term: 'ev mechanic', weight: 1 },
    { term: 'driving instructor', weight: 1 },
    { term: 'car wash', weight: 1 },
    { term: 'tire shop', weight: 1 },
    { term: 'body shop', weight: 1 },
    { term: 'airport transfer', weight: 1 },
    { term: 'mobile mechanic', weight: 1 },
  ],
  'construction-engineering': [
    { term: 'builder', weight: 2 },
    { term: 'contractor', weight: 2 },
    { term: 'civil engineer', weight: 2 },
    { term: 'construction company', weight: 2 },
    { term: 'bricklayer', weight: 2 },
    { term: 'scaffolder', weight: 2 },
    { term: 'roofer', weight: 2 },
    { term: 'site manager', weight: 1 },
    { term: 'structural engineer', weight: 1 },
    { term: 'plasterer', weight: 1 },
    { term: 'joiner', weight: 1 },
    { term: 'carpenter', weight: 1 },
    { term: 'groundworker', weight: 1 },
    { term: 'building inspector', weight: 1 },
    { term: 'construction', weight: 2 },
    { term: 'general contractor', weight: 2 },
    { term: 'home builder', weight: 2 },
    { term: 'quantity surveyor', weight: 1 },
    { term: 'electrician', weight: 2 },
    { term: 'tiler', weight: 1 },
    { term: 'glazier', weight: 1 },
    { term: 'demolition', weight: 1 },
    { term: 'plant operator', weight: 1 },
    { term: 'crane driver', weight: 1 },
    { term: 'highways engineer', weight: 1 },
    { term: 'rigger', weight: 1 },
    { term: 'chippy', weight: 1 },
    { term: 'brickie', weight: 1 },
    { term: 'sparky', weight: 2 },
    { term: 'sparkie', weight: 2 },
    { term: 'roof repair', weight: 1 },
  ],
  'food-hospitality': [
    { term: 'cook', weight: 2 },
    { term: 'baker', weight: 2 },
    { term: 'bakery', weight: 2 },
    { term: 'food truck', weight: 2 },
    { term: 'takeaway', weight: 2 },
    { term: 'catering company', weight: 2 },
    { term: 'barista', weight: 1 },
    { term: 'waiter', weight: 1 },
    { term: 'waitress', weight: 1 },
    { term: 'sous chef', weight: 1 },
    { term: 'street food', weight: 1 },
    { term: 'diner', weight: 1 },
    { term: 'eatery', weight: 1 },
    { term: 'brasserie', weight: 1 },
    { term: 'line cook', weight: 1 },
    { term: 'patisserie', weight: 1 },
    { term: 'pizzeria', weight: 1 },
    { term: 'chef', weight: 2 },
    { term: 'restaurant', weight: 2 },
    { term: 'cafe', weight: 2 },
    { term: 'pub', weight: 2 },
    { term: 'bar', weight: 2 },
    { term: 'caterer', weight: 2 },
    { term: 'hospitality', weight: 2 },
    { term: 'sommelier', weight: 1 },
    { term: 'bistro', weight: 1 },
    { term: 'tavern', weight: 1 },
    { term: 'kebab shop', weight: 1 },
    { term: 'chippie', weight: 1 },
    { term: 'maitre d', weight: 1 },
    { term: 'michelin star', weight: 1 },
    { term: 'ghost kitchen', weight: 1 },
    { term: 'meal prep', weight: 1 },
    { term: 'restaurateur', weight: 1 },
    { term: 'barback', weight: 1 },
    { term: 'coffee shop', weight: 1 },
  ],
  'retail-marketplaces': [
    { term: 'shop', weight: 2 },
    { term: 'store', weight: 2 },
    { term: 'boutique', weight: 2 },
    { term: 'supermarket', weight: 2 },
    { term: 'grocer', weight: 2 },
    { term: 'e-commerce', weight: 2 },
    { term: 'online store', weight: 2 },
    { term: 'marketplace seller', weight: 1 },
    { term: 'checkout', weight: 1 },
    { term: 'point of sale', weight: 2 },
    { term: 'retail manager', weight: 1 },
    { term: 'merchandiser', weight: 1 },
    { term: 'pop-up shop', weight: 1 },
    { term: 'farmers market', weight: 1 },
    { term: 'wholesaler', weight: 1 },
    { term: 'corner shop', weight: 1 },
    { term: 'retail', weight: 2 },
    { term: 'ecommerce', weight: 1 },
    { term: 'dropshipper', weight: 1 },
    { term: 'online seller', weight: 1 },
    { term: 'pos', weight: 2 },
    { term: 'window display', weight: 1 },
    { term: 'flea market', weight: 1 },
    { term: 'cash and carry', weight: 1 },
    { term: 'franchise', weight: 1 },
    { term: 'off-licence', weight: 1 },
    { term: 'liquor store', weight: 1 },
    { term: 'newsagent', weight: 1 },
    { term: 'convenience store', weight: 1 },
    { term: 'butcher', weight: 1 },
    { term: 'greengrocer', weight: 1 },
    { term: 'second hand shop', weight: 1 },
  ],
};

module.exports = { INDUSTRY_ALIASES };
