/**
 * PuniCodex — Canonical industry-alias vocabulary
 *
 * Companion to type/js/industry-patterns.js. Maps the fragment professions,
 * trades, and search terms a real sponsor would type ("plumber", "poet",
 * "church") onto the 53 curated industries of the pattern map. Powers the
 * Find Your Pattern autocomplete on /patterns/ and the
 * /api/v1/industry-patterns/match endpoint.
 *
 * Curation discipline:
 *   - weight 2 (direct): a direct synonym for the industry or a core
 *     profession inside it (plumber → water-utilities).
 *   - weight 1 (adjacent): a neighboring fragment, sub-trade, or audience
 *     term that reliably implies the industry (irrigation → water-utilities).
 *   - One alias has exactly one home. A term that could serve two industries
 *     is assigned to the best fit only — precision over recall.
 *   - Terms are lowercase, singular preferred (plurals added only when
 *     natural), multi-word terms allowed. UK/US variants both included
 *     where a real person would type either (solicitor/attorney).
 *   - If no industry genuinely fits a profession, the term is omitted.
 *
 * Generated consumers (DO NOT edit by hand):
 *   - platform/api/industry-patterns.json (aliases index, meta.aliasCount)
 *   - platform/browser/renderer/industry-patterns.json
 *   - patterns/index.html (embedded in window.PATTERN_GRAPH)
 *
 * Run `npm run generate` after editing this file.
 */

'use strict';

const INDUSTRY_ALIASES = {
  'solar-energy': [
    { term: 'solar', weight: 2 },
    { term: 'solar power', weight: 2 },
    { term: 'solar panel', weight: 2 },
    { term: 'solar installer', weight: 2 },
    { term: 'solar company', weight: 2 },
    { term: 'solar farm', weight: 2 },
    { term: 'solar thermal', weight: 2 },
    { term: 'photovoltaic', weight: 2 },
    { term: 'renewable energy', weight: 2 },
    { term: 'pv installer', weight: 1 },
    { term: 'renewables', weight: 1 },
    { term: 'clean energy', weight: 1 },
    { term: 'green energy', weight: 1 },
    { term: 'sun power', weight: 1 },
  ],
  'wind-energy': [
    { term: 'wind energy', weight: 2 },
    { term: 'wind power', weight: 2 },
    { term: 'wind farm', weight: 2 },
    { term: 'wind turbine', weight: 2 },
    { term: 'offshore wind', weight: 2 },
    { term: 'wind technician', weight: 2 },
    { term: 'wind engineer', weight: 2 },
    { term: 'windmill', weight: 1 },
    { term: 'turbine technician', weight: 1 },
    { term: 'aerogenerator', weight: 1 },
  ],
  'thermal-energy': [
    { term: 'geothermal', weight: 2 },
    { term: 'geothermal energy', weight: 2 },
    { term: 'heating', weight: 2 },
    { term: 'hvac', weight: 2 },
    { term: 'boiler', weight: 2 },
    { term: 'heating engineer', weight: 2 },
    { term: 'thermal power', weight: 2 },
    { term: 'heat pump', weight: 2 },
    { term: 'furnace', weight: 1 },
    { term: 'fireplace', weight: 1 },
    { term: 'stove', weight: 1 },
    { term: 'district heating', weight: 1 },
    { term: 'gas engineer', weight: 1 },
  ],
  'storm-forecasting': [
    { term: 'meteorologist', weight: 2 },
    { term: 'meteorology', weight: 2 },
    { term: 'weather', weight: 2 },
    { term: 'weather forecast', weight: 2 },
    { term: 'weather app', weight: 2 },
    { term: 'forecaster', weight: 2 },
    { term: 'weatherman', weight: 1 },
    { term: 'storm chaser', weight: 1 },
    { term: 'hurricane tracker', weight: 1 },
    { term: 'weather radar', weight: 1 },
    { term: 'weather station', weight: 1 },
  ],
  maritime: [
    { term: 'shipping', weight: 2 },
    { term: 'sailor', weight: 2 },
    { term: 'shipyard', weight: 2 },
    { term: 'shipbuilding', weight: 2 },
    { term: 'fishing', weight: 2 },
    { term: 'fisherman', weight: 2 },
    { term: 'cruise', weight: 2 },
    { term: 'ferry', weight: 2 },
    { term: 'port', weight: 2 },
    { term: 'boat', weight: 2 },
    { term: 'ship captain', weight: 2 },
    { term: 'seafarer', weight: 1 },
    { term: 'yacht', weight: 1 },
    { term: 'marine', weight: 1 },
    { term: 'dockworker', weight: 1 },
    { term: 'lighthouse', weight: 1 },
  ],
  'water-utilities': [
    { term: 'plumber', weight: 2 },
    { term: 'plumbing', weight: 2 },
    { term: 'water engineer', weight: 2 },
    { term: 'water company', weight: 2 },
    { term: 'water supply', weight: 2 },
    { term: 'water treatment', weight: 2 },
    { term: 'drainage', weight: 1 },
    { term: 'sewage', weight: 1 },
    { term: 'irrigation', weight: 1 },
    { term: 'hydrologist', weight: 1 },
    { term: 'wastewater', weight: 1 },
    { term: 'utility', weight: 1 },
    { term: 'pipe fitter', weight: 1 },
    { term: 'well driller', weight: 1 },
  ],
  'aviation-aerospace': [
    { term: 'pilot', weight: 2 },
    { term: 'airline', weight: 2 },
    { term: 'airport', weight: 2 },
    { term: 'aviation', weight: 2 },
    { term: 'aerospace', weight: 2 },
    { term: 'flight attendant', weight: 2 },
    { term: 'drone', weight: 2 },
    { term: 'aircraft', weight: 2 },
    { term: 'air traffic controller', weight: 2 },
    { term: 'helicopter', weight: 1 },
    { term: 'flight school', weight: 1 },
    { term: 'balloonist', weight: 1 },
  ],
  'space-astronomy': [
    { term: 'astronomer', weight: 2 },
    { term: 'space', weight: 2 },
    { term: 'observatory', weight: 2 },
    { term: 'telescope', weight: 2 },
    { term: 'astronaut', weight: 2 },
    { term: 'planetarium', weight: 2 },
    { term: 'space agency', weight: 2 },
    { term: 'astrophysics', weight: 2 },
    { term: 'rocket', weight: 1 },
    { term: 'satellite', weight: 1 },
    { term: 'stargazing', weight: 1 },
    { term: 'cosmology', weight: 1 },
    { term: 'nasa', weight: 1 },
  ],
  defense: [
    { term: 'military', weight: 2 },
    { term: 'army', weight: 2 },
    { term: 'soldier', weight: 2 },
    { term: 'navy', weight: 2 },
    { term: 'air force', weight: 2 },
    { term: 'veteran', weight: 2 },
    { term: 'defense contractor', weight: 2 },
    { term: 'defence', weight: 2 },
    { term: 'security contractor', weight: 1 },
    { term: 'mercenary', weight: 1 },
    { term: 'marine corps', weight: 1 },
    { term: 'special forces', weight: 1 },
    { term: 'bodyguard', weight: 1 },
  ],
  cybersecurity: [
    { term: 'cybersecurity', weight: 2 },
    { term: 'cyber security', weight: 2 },
    { term: 'hacker', weight: 2 },
    { term: 'infosec', weight: 2 },
    { term: 'penetration tester', weight: 2 },
    { term: 'ethical hacker', weight: 2 },
    { term: 'security researcher', weight: 2 },
    { term: 'antivirus', weight: 2 },
    { term: 'soc analyst', weight: 1 },
    { term: 'malware', weight: 1 },
    { term: 'security operations', weight: 1 },
    { term: 'cryptographer', weight: 1 },
  ],
  'software-tech': [
    { term: 'software developer', weight: 2 },
    { term: 'software engineer', weight: 2 },
    { term: 'programmer', weight: 2 },
    { term: 'web developer', weight: 2 },
    { term: 'app developer', weight: 2 },
    { term: 'devops', weight: 2 },
    { term: 'cloud engineer', weight: 2 },
    { term: 'saas', weight: 2 },
    { term: 'software company', weight: 2 },
    { term: 'coding bootcamp', weight: 1 },
    { term: 'full stack developer', weight: 1 },
    { term: 'it support', weight: 1 },
    { term: 'tech company', weight: 1 },
  ],
  'ai-forecasting': [
    { term: 'data scientist', weight: 2 },
    { term: 'machine learning', weight: 2 },
    { term: 'artificial intelligence', weight: 2 },
    { term: 'ai startup', weight: 2 },
    { term: 'data analyst', weight: 2 },
    { term: 'predictive analytics', weight: 2 },
    { term: 'ml engineer', weight: 2 },
    { term: 'ai researcher', weight: 2 },
    { term: 'forecasting', weight: 2 },
    { term: 'quant', weight: 1 },
    { term: 'big data', weight: 1 },
    { term: 'algorithmic trading', weight: 1 },
  ],
  'telecom-logistics': [
    { term: 'logistics', weight: 2 },
    { term: 'courier', weight: 2 },
    { term: 'delivery', weight: 2 },
    { term: 'trucking', weight: 2 },
    { term: 'supply chain', weight: 2 },
    { term: 'freight', weight: 2 },
    { term: 'messenger', weight: 2 },
    { term: 'postal service', weight: 2 },
    { term: 'telecom', weight: 2 },
    { term: 'freight forwarder', weight: 1 },
    { term: 'dispatcher', weight: 1 },
    { term: 'last mile delivery', weight: 1 },
    { term: 'broadband', weight: 1 },
  ],
  'cartography-geospatial': [
    { term: 'cartographer', weight: 2 },
    { term: 'gis', weight: 2 },
    { term: 'gis analyst', weight: 2 },
    { term: 'surveyor', weight: 2 },
    { term: 'land surveyor', weight: 2 },
    { term: 'mapping', weight: 2 },
    { term: 'mapmaker', weight: 2 },
    { term: 'gps', weight: 2 },
    { term: 'geospatial', weight: 2 },
    { term: 'remote sensing', weight: 1 },
    { term: 'navigation', weight: 1 },
    { term: 'topography', weight: 1 },
  ],
  'mining-resources': [
    { term: 'mining', weight: 2 },
    { term: 'miner', weight: 2 },
    { term: 'quarry', weight: 2 },
    { term: 'gold mining', weight: 2 },
    { term: 'coal', weight: 2 },
    { term: 'oil rig', weight: 2 },
    { term: 'oil and gas', weight: 2 },
    { term: 'drilling', weight: 1 },
    { term: 'prospector', weight: 1 },
    { term: 'geologist', weight: 1 },
    { term: 'roughneck', weight: 1 },
  ],
  'agriculture-food': [
    { term: 'farmer', weight: 2 },
    { term: 'farming', weight: 2 },
    { term: 'agriculture', weight: 2 },
    { term: 'rancher', weight: 2 },
    { term: 'agronomist', weight: 2 },
    { term: 'harvest', weight: 2 },
    { term: 'organic farm', weight: 2 },
    { term: 'food producer', weight: 2 },
    { term: 'dairy farm', weight: 1 },
    { term: 'market gardener', weight: 1 },
    { term: 'cattle', weight: 1 },
    { term: 'grain', weight: 1 },
    { term: 'farm equipment', weight: 1 },
  ],
  'forestry-conservation': [
    { term: 'forester', weight: 2 },
    { term: 'logging', weight: 2 },
    { term: 'lumber', weight: 2 },
    { term: 'timber', weight: 2 },
    { term: 'ranger', weight: 2 },
    { term: 'park ranger', weight: 2 },
    { term: 'arborist', weight: 2 },
    { term: 'conservationist', weight: 2 },
    { term: 'tree surgeon', weight: 1 },
    { term: 'wildlife biologist', weight: 1 },
    { term: 'forest service', weight: 1 },
    { term: 'lumberjack', weight: 1 },
    { term: 'national park', weight: 1 },
  ],
  'environment-climate': [
    { term: 'climate', weight: 2 },
    { term: 'sustainability', weight: 2 },
    { term: 'environmental consultant', weight: 2 },
    { term: 'environmental scientist', weight: 2 },
    { term: 'recycling', weight: 2 },
    { term: 'carbon offset', weight: 2 },
    { term: 'climate tech', weight: 2 },
    { term: 'ecologist', weight: 2 },
    { term: 'carbon accounting', weight: 1 },
    { term: 'green building', weight: 1 },
    { term: 'emissions', weight: 1 },
    { term: 'climate activist', weight: 1 },
  ],
  'manufacturing-craft': [
    { term: 'manufacturer', weight: 2 },
    { term: 'factory', weight: 2 },
    { term: 'machinist', weight: 2 },
    { term: 'welder', weight: 2 },
    { term: 'blacksmith', weight: 2 },
    { term: 'craftsman', weight: 2 },
    { term: 'artisan', weight: 2 },
    { term: 'woodworker', weight: 1 },
    { term: 'metalworker', weight: 1 },
    { term: 'cnc operator', weight: 1 },
    { term: 'assembly line', weight: 1 },
    { term: 'potter', weight: 1 },
  ],
  'architecture-design': [
    { term: 'architect', weight: 2 },
    { term: 'interior designer', weight: 2 },
    { term: 'construction', weight: 2 },
    { term: 'builder', weight: 2 },
    { term: 'general contractor', weight: 2 },
    { term: 'home builder', weight: 2 },
    { term: 'urban planner', weight: 2 },
    { term: 'landscape architect', weight: 1 },
    { term: 'drafter', weight: 1 },
    { term: 'design studio', weight: 1 },
    { term: 'building designer', weight: 1 },
    { term: 'quantity surveyor', weight: 1 },
  ],
  textiles: [
    { term: 'tailor', weight: 2 },
    { term: 'weaver', weight: 2 },
    { term: 'textile', weight: 2 },
    { term: 'textile manufacturer', weight: 2 },
    { term: 'seamstress', weight: 2 },
    { term: 'fabric', weight: 2 },
    { term: 'dressmaker', weight: 2 },
    { term: 'knitter', weight: 1 },
    { term: 'yarn', weight: 1 },
    { term: 'spinning', weight: 1 },
    { term: 'embroiderer', weight: 1 },
    { term: 'upholsterer', weight: 1 },
  ],
  'gems-jewelry': [
    { term: 'jeweler', weight: 2 },
    { term: 'jeweller', weight: 2 },
    { term: 'goldsmith', weight: 2 },
    { term: 'silversmith', weight: 2 },
    { term: 'diamond', weight: 2 },
    { term: 'gemstone', weight: 2 },
    { term: 'gemologist', weight: 2 },
    { term: 'lapidary', weight: 1 },
    { term: 'diamond dealer', weight: 1 },
    { term: 'engagement ring', weight: 1 },
    { term: 'luxury goods', weight: 1 },
    { term: 'pearl', weight: 1 },
  ],
  'beauty-fashion': [
    { term: 'fashion', weight: 2 },
    { term: 'fashion designer', weight: 2 },
    { term: 'model', weight: 2 },
    { term: 'modeling agency', weight: 2 },
    { term: 'makeup artist', weight: 2 },
    { term: 'cosmetics', weight: 2 },
    { term: 'stylist', weight: 2 },
    { term: 'hairdresser', weight: 2 },
    { term: 'barber', weight: 2 },
    { term: 'salon', weight: 2 },
    { term: 'beauty salon', weight: 2 },
    { term: 'nail technician', weight: 1 },
    { term: 'perfume', weight: 1 },
    { term: 'runway', weight: 1 },
  ],
  'healthcare-pharma': [
    { term: 'doctor', weight: 2 },
    { term: 'nurse', weight: 2 },
    { term: 'dentist', weight: 2 },
    { term: 'hospital', weight: 2 },
    { term: 'pharmacist', weight: 2 },
    { term: 'pharmacy', weight: 2 },
    { term: 'surgeon', weight: 2 },
    { term: 'physician', weight: 2 },
    { term: 'clinic', weight: 2 },
    { term: 'pharma', weight: 2 },
    { term: 'paramedic', weight: 2 },
    { term: 'gp', weight: 1 },
    { term: 'pediatrician', weight: 1 },
    { term: 'dermatologist', weight: 1 },
    { term: 'caregiver', weight: 1 },
    { term: 'nursing home', weight: 1 },
  ],
  'mental-health': [
    { term: 'therapist', weight: 2 },
    { term: 'therapy', weight: 2 },
    { term: 'psychologist', weight: 2 },
    { term: 'psychiatrist', weight: 2 },
    { term: 'counselor', weight: 2 },
    { term: 'psychotherapist', weight: 2 },
    { term: 'mental health', weight: 2 },
    { term: 'counselling', weight: 1 },
    { term: 'counseling', weight: 1 },
    { term: 'anxiety coach', weight: 1 },
    { term: 'trauma therapist', weight: 1 },
    { term: 'grief counselor', weight: 1 },
    { term: 'addiction counselor', weight: 1 },
  ],
  'sleep-recovery': [
    { term: 'sleep', weight: 2 },
    { term: 'mattress', weight: 2 },
    { term: 'sleep tracker', weight: 2 },
    { term: 'sleep clinic', weight: 2 },
    { term: 'insomnia', weight: 2 },
    { term: 'bedding', weight: 1 },
    { term: 'pillow', weight: 1 },
    { term: 'sleep coach', weight: 1 },
    { term: 'melatonin', weight: 1 },
    { term: 'white noise', weight: 1 },
    { term: 'sleep apnea', weight: 1 },
    { term: 'recovery tech', weight: 1 },
  ],
  'wellness-mind': [
    { term: 'yoga', weight: 2 },
    { term: 'yoga teacher', weight: 2 },
    { term: 'meditation', weight: 2 },
    { term: 'mindfulness', weight: 2 },
    { term: 'wellness', weight: 2 },
    { term: 'spa', weight: 2 },
    { term: 'massage therapist', weight: 2 },
    { term: 'retreat', weight: 2 },
    { term: 'life coach', weight: 1 },
    { term: 'breathwork', weight: 1 },
    { term: 'pilates', weight: 1 },
    { term: 'holistic healer', weight: 1 },
    { term: 'reiki', weight: 1 },
    { term: 'ayurveda', weight: 1 },
  ],
  'biotech-longevity': [
    { term: 'biotech', weight: 2 },
    { term: 'biotech startup', weight: 2 },
    { term: 'longevity', weight: 2 },
    { term: 'longevity clinic', weight: 2 },
    { term: 'geneticist', weight: 2 },
    { term: 'gene therapy', weight: 2 },
    { term: 'genomics', weight: 2 },
    { term: 'anti aging', weight: 2 },
    { term: 'biohacker', weight: 1 },
    { term: 'biohacking', weight: 1 },
    { term: 'life extension', weight: 1 },
    { term: 'stem cell', weight: 1 },
    { term: 'crispr', weight: 1 },
  ],
  'occult-esoteric': [
    { term: 'astrologer', weight: 2 },
    { term: 'astrology', weight: 2 },
    { term: 'tarot', weight: 2 },
    { term: 'tarot reader', weight: 2 },
    { term: 'psychic', weight: 2 },
    { term: 'horoscope', weight: 2 },
    { term: 'occult', weight: 2 },
    { term: 'medium', weight: 1 },
    { term: 'palm reader', weight: 1 },
    { term: 'witch', weight: 1 },
    { term: 'numerologist', weight: 1 },
    { term: 'crystal healer', weight: 1 },
    { term: 'fortune teller', weight: 1 },
    { term: 'esoteric shop', weight: 1 },
    { term: 'clairvoyant', weight: 1 },
  ],
  faith: [
    { term: 'church', weight: 2 },
    { term: 'mosque', weight: 2 },
    { term: 'temple', weight: 2 },
    { term: 'synagogue', weight: 2 },
    { term: 'chapel', weight: 2 },
    { term: 'religion', weight: 2 },
    { term: 'priest', weight: 2 },
    { term: 'imam', weight: 2 },
    { term: 'pastor', weight: 2 },
    { term: 'rabbi', weight: 2 },
    { term: 'vicar', weight: 2 },
    { term: 'monk', weight: 1 },
    { term: 'nun', weight: 1 },
    { term: 'congregation', weight: 1 },
    { term: 'parish', weight: 1 },
    { term: 'ministry', weight: 1 },
    { term: 'worship', weight: 1 },
    { term: 'cathedral', weight: 1 },
    { term: 'bishop', weight: 1 },
    { term: 'cleric', weight: 1 },
  ],
  'publishing-media': [
    { term: 'poet', weight: 2 },
    { term: 'writer', weight: 2 },
    { term: 'author', weight: 2 },
    { term: 'journalist', weight: 2 },
    { term: 'novelist', weight: 2 },
    { term: 'copywriter', weight: 2 },
    { term: 'editor', weight: 2 },
    { term: 'publisher', weight: 2 },
    { term: 'reporter', weight: 2 },
    { term: 'newspaper', weight: 2 },
    { term: 'magazine', weight: 2 },
    { term: 'bard', weight: 1 },
    { term: 'blogger', weight: 1 },
    { term: 'screenwriter', weight: 1 },
    { term: 'storyteller', weight: 1 },
    { term: 'columnist', weight: 1 },
    { term: 'playwright', weight: 1 },
    { term: 'freelance writer', weight: 1 },
    { term: 'influencer', weight: 1 },
    { term: 'podcaster', weight: 1 },
  ],
  'music-arts': [
    { term: 'musician', weight: 2 },
    { term: 'singer', weight: 2 },
    { term: 'composer', weight: 2 },
    { term: 'band', weight: 2 },
    { term: 'dj', weight: 2 },
    { term: 'orchestra', weight: 2 },
    { term: 'painter', weight: 2 },
    { term: 'artist', weight: 2 },
    { term: 'dancer', weight: 2 },
    { term: 'actor', weight: 2 },
    { term: 'theater', weight: 2 },
    { term: 'theatre', weight: 2 },
    { term: 'concert', weight: 2 },
    { term: 'sculptor', weight: 1 },
    { term: 'opera', weight: 1 },
    { term: 'guitarist', weight: 1 },
    { term: 'record label', weight: 1 },
    { term: 'filmmaker', weight: 1 },
  ],
  'gaming-entertainment': [
    { term: 'game developer', weight: 2 },
    { term: 'game designer', weight: 2 },
    { term: 'game studio', weight: 2 },
    { term: 'video game', weight: 2 },
    { term: 'esports', weight: 2 },
    { term: 'streamer', weight: 2 },
    { term: 'twitch streamer', weight: 1 },
    { term: 'board game', weight: 1 },
    { term: 'rpg', weight: 1 },
    { term: 'game publisher', weight: 1 },
    { term: 'dungeon master', weight: 1 },
    { term: 'arcade', weight: 1 },
    { term: 'cosplay', weight: 1 },
  ],
  'sports-athletics': [
    { term: 'athlete', weight: 2 },
    { term: 'gym', weight: 2 },
    { term: 'personal trainer', weight: 2 },
    { term: 'football', weight: 2 },
    { term: 'football club', weight: 2 },
    { term: 'basketball', weight: 2 },
    { term: 'coach', weight: 2 },
    { term: 'sports team', weight: 2 },
    { term: 'olympics', weight: 1 },
    { term: 'marathon', weight: 1 },
    { term: 'runner', weight: 1 },
    { term: 'triathlete', weight: 1 },
    { term: 'crossfit', weight: 1 },
    { term: 'boxer', weight: 1 },
    { term: 'wrestler', weight: 1 },
  ],
  'wine-hospitality': [
    { term: 'winemaker', weight: 2 },
    { term: 'winery', weight: 2 },
    { term: 'vineyard', weight: 2 },
    { term: 'brewer', weight: 2 },
    { term: 'brewery', weight: 2 },
    { term: 'restaurant', weight: 2 },
    { term: 'chef', weight: 2 },
    { term: 'hotel', weight: 2 },
    { term: 'sommelier', weight: 2 },
    { term: 'bar', weight: 2 },
    { term: 'bartender', weight: 2 },
    { term: 'caterer', weight: 2 },
    { term: 'hospitality', weight: 2 },
    { term: 'cafe', weight: 1 },
    { term: 'bistro', weight: 1 },
    { term: 'distiller', weight: 1 },
    { term: 'innkeeper', weight: 1 },
    { term: 'bed and breakfast', weight: 1 },
  ],
  'travel-tourism': [
    { term: 'travel agent', weight: 2 },
    { term: 'travel agency', weight: 2 },
    { term: 'tour guide', weight: 2 },
    { term: 'tour operator', weight: 2 },
    { term: 'tourism', weight: 2 },
    { term: 'travel blogger', weight: 1 },
    { term: 'vacation rental', weight: 1 },
    { term: 'safari', weight: 1 },
    { term: 'ecotourism', weight: 1 },
    { term: 'destination marketing', weight: 1 },
    { term: 'cruise line', weight: 1 },
  ],
  'real-estate-home': [
    { term: 'realtor', weight: 2 },
    { term: 'real estate agent', weight: 2 },
    { term: 'estate agent', weight: 2 },
    { term: 'letting agent', weight: 2 },
    { term: 'property developer', weight: 2 },
    { term: 'landlord', weight: 2 },
    { term: 'property management', weight: 2 },
    { term: 'mortgage broker', weight: 1 },
    { term: 'home staging', weight: 1 },
    { term: 'realty', weight: 1 },
    { term: 'property investor', weight: 1 },
    { term: 'conveyancer', weight: 1 },
    { term: 'home inspector', weight: 1 },
  ],
  petcare: [
    { term: 'vet', weight: 2 },
    { term: 'veterinarian', weight: 2 },
    { term: 'dog groomer', weight: 2 },
    { term: 'pet sitter', weight: 2 },
    { term: 'dog walker', weight: 2 },
    { term: 'pet shop', weight: 2 },
    { term: 'animal shelter', weight: 2 },
    { term: 'dog trainer', weight: 2 },
    { term: 'kennel', weight: 1 },
    { term: 'cat breeder', weight: 1 },
    { term: 'pet food', weight: 1 },
    { term: 'horse trainer', weight: 1 },
    { term: 'stable', weight: 1 },
    { term: 'farrier', weight: 1 },
  ],
  'finance-commerce': [
    { term: 'banker', weight: 2 },
    { term: 'accountant', weight: 2 },
    { term: 'investor', weight: 2 },
    { term: 'hedge fund', weight: 2 },
    { term: 'investment bank', weight: 2 },
    { term: 'financial advisor', weight: 2 },
    { term: 'stockbroker', weight: 2 },
    { term: 'fintech', weight: 2 },
    { term: 'trader', weight: 2 },
    { term: 'wealth manager', weight: 2 },
    { term: 'retail', weight: 2 },
    { term: 'merchant', weight: 2 },
    { term: 'private equity', weight: 1 },
    { term: 'bookkeeper', weight: 1 },
    { term: 'cfo', weight: 1 },
    { term: 'tax advisor', weight: 1 },
    { term: 'auditor', weight: 1 },
    { term: 'ecommerce', weight: 1 },
  ],
  insurance: [
    { term: 'insurance agent', weight: 2 },
    { term: 'insurance broker', weight: 2 },
    { term: 'insurance company', weight: 2 },
    { term: 'insurer', weight: 2 },
    { term: 'underwriter', weight: 2 },
    { term: 'actuary', weight: 2 },
    { term: 'life insurance', weight: 2 },
    { term: 'claims adjuster', weight: 1 },
    { term: 'health insurance', weight: 1 },
    { term: 'car insurance', weight: 1 },
    { term: 'reinsurance', weight: 1 },
    { term: 'risk manager', weight: 1 },
  ],
  'legal-justice': [
    { term: 'lawyer', weight: 2 },
    { term: 'solicitor', weight: 2 },
    { term: 'attorney', weight: 2 },
    { term: 'barrister', weight: 2 },
    { term: 'judge', weight: 2 },
    { term: 'law firm', weight: 2 },
    { term: 'paralegal', weight: 1 },
    { term: 'notary', weight: 1 },
    { term: 'prosecutor', weight: 1 },
    { term: 'public defender', weight: 1 },
    { term: 'compliance officer', weight: 1 },
    { term: 'legal counsel', weight: 1 },
    { term: 'litigator', weight: 1 },
    { term: 'magistrate', weight: 1 },
    { term: 'police officer', weight: 1 },
    { term: 'detective', weight: 1 },
  ],
  leadership: [
    { term: 'mayor', weight: 2 },
    { term: 'president', weight: 2 },
    { term: 'politician', weight: 2 },
    { term: 'senator', weight: 2 },
    { term: 'governor', weight: 2 },
    { term: 'government', weight: 2 },
    { term: 'civil servant', weight: 2 },
    { term: 'diplomat', weight: 2 },
    { term: 'prime minister', weight: 2 },
    { term: 'public administration', weight: 2 },
    { term: 'city council', weight: 1 },
    { term: 'ambassador', weight: 1 },
    { term: 'campaign manager', weight: 1 },
    { term: 'policy advisor', weight: 1 },
    { term: 'minister', weight: 1 },
  ],
  education: [
    { term: 'teacher', weight: 2 },
    { term: 'professor', weight: 2 },
    { term: 'university', weight: 2 },
    { term: 'school', weight: 2 },
    { term: 'tutor', weight: 2 },
    { term: 'researcher', weight: 2 },
    { term: 'lecturer', weight: 2 },
    { term: 'academic', weight: 2 },
    { term: 'student', weight: 1 },
    { term: 'librarian', weight: 1 },
    { term: 'phd', weight: 1 },
    { term: 'online course', weight: 1 },
    { term: 'kindergarten', weight: 1 },
    { term: 'principal', weight: 1 },
    { term: 'edtech', weight: 1 },
  ],
  'philosophy-ethics': [
    { term: 'philosopher', weight: 2 },
    { term: 'ethicist', weight: 2 },
    { term: 'think tank', weight: 2 },
    { term: 'ethics committee', weight: 1 },
    { term: 'standards body', weight: 1 },
    { term: 'bioethicist', weight: 1 },
    { term: 'logician', weight: 1 },
    { term: 'moral philosopher', weight: 1 },
    { term: 'policy institute', weight: 1 },
    { term: 'board of ethics', weight: 1 },
    { term: 'futurist', weight: 1 },
  ],
  'genealogy-ancestry': [
    { term: 'genealogist', weight: 2 },
    { term: 'dna test', weight: 2 },
    { term: 'ancestry research', weight: 2 },
    { term: 'family tree', weight: 2 },
    { term: 'archivist', weight: 2 },
    { term: 'heritage', weight: 2 },
    { term: 'family historian', weight: 1 },
    { term: 'historian', weight: 1 },
    { term: 'lineage society', weight: 1 },
    { term: 'heraldry', weight: 1 },
    { term: 'archive', weight: 1 },
    { term: 'museum', weight: 1 },
  ],
  'startups-venture': [
    { term: 'entrepreneur', weight: 2 },
    { term: 'business owner', weight: 2 },
    { term: 'founder', weight: 2 },
    { term: 'startup founder', weight: 2 },
    { term: 'startup', weight: 2 },
    { term: 'small business', weight: 2 },
    { term: 'venture capitalist', weight: 1 },
    { term: 'solopreneur', weight: 1 },
    { term: 'incubator', weight: 1 },
    { term: 'angel investor', weight: 1 },
    { term: 'side hustle', weight: 1 },
    { term: 'accelerator', weight: 1 },
    { term: 'serial entrepreneur', weight: 1 },
  ],
  'disaster-resilience': [
    { term: 'firefighter', weight: 2 },
    { term: 'fire department', weight: 2 },
    { term: 'emergency management', weight: 2 },
    { term: 'emergency planner', weight: 2 },
    { term: 'search and rescue', weight: 2 },
    { term: 'disaster relief', weight: 2 },
    { term: 'civil defense', weight: 1 },
    { term: 'red cross', weight: 1 },
    { term: 'business continuity', weight: 1 },
    { term: 'flood response', weight: 1 },
    { term: 'coastguard', weight: 1 },
    { term: 'resilience consultant', weight: 1 },
  ],
  'funerary-memorial': [
    { term: 'funeral director', weight: 2 },
    { term: 'undertaker', weight: 2 },
    { term: 'mortician', weight: 2 },
    { term: 'cemetery', weight: 2 },
    { term: 'crematorium', weight: 2 },
    { term: 'funeral home', weight: 2 },
    { term: 'memorial service', weight: 1 },
    { term: 'gravestone', weight: 1 },
    { term: 'headstone', weight: 1 },
    { term: 'hospice', weight: 1 },
    { term: 'obituary', weight: 1 },
    { term: 'embalmer', weight: 1 },
    { term: 'bereavement', weight: 1 },
  ],
  horology: [
    { term: 'watchmaker', weight: 2 },
    { term: 'clockmaker', weight: 2 },
    { term: 'watch', weight: 2 },
    { term: 'watch repair', weight: 2 },
    { term: 'horologist', weight: 2 },
    { term: 'timepiece', weight: 2 },
    { term: 'luxury watch', weight: 2 },
    { term: 'calendar app', weight: 2 },
    { term: 'chronometer', weight: 1 },
    { term: 'smartwatch', weight: 1 },
    { term: 'scheduling software', weight: 1 },
    { term: 'atomic clock', weight: 1 },
  ],
  'photography-optics': [
    { term: 'photographer', weight: 2 },
    { term: 'photography', weight: 2 },
    { term: 'videographer', weight: 2 },
    { term: 'camera', weight: 2 },
    { term: 'lens', weight: 2 },
    { term: 'cinematographer', weight: 2 },
    { term: 'optician', weight: 2 },
    { term: 'optometrist', weight: 2 },
    { term: 'eyewear', weight: 2 },
    { term: 'photo studio', weight: 1 },
    { term: 'wedding photographer', weight: 1 },
    { term: 'drone photographer', weight: 1 },
    { term: 'binoculars', weight: 1 },
    { term: 'microscope', weight: 1 },
  ],
  femtech: [
    { term: 'femtech', weight: 2 },
    { term: 'femtech startup', weight: 2 },
    { term: 'period tracker', weight: 2 },
    { term: 'fertility app', weight: 2 },
    { term: 'pregnancy app', weight: 2 },
    { term: 'menstrual health', weight: 2 },
    { term: 'menopause', weight: 1 },
    { term: 'ovulation tracker', weight: 1 },
    { term: 'breastfeeding', weight: 1 },
    { term: 'pelvic health', weight: 1 },
  ],
  'wedding-family': [
    { term: 'wedding planner', weight: 2 },
    { term: 'bridal shop', weight: 2 },
    { term: 'wedding venue', weight: 2 },
    { term: 'midwife', weight: 2 },
    { term: 'doula', weight: 2 },
    { term: 'maternity', weight: 2 },
    { term: 'nanny', weight: 2 },
    { term: 'daycare', weight: 2 },
    { term: 'marriage celebrant', weight: 1 },
    { term: 'baby shower', weight: 1 },
    { term: 'christening', weight: 1 },
    { term: 'surrogacy', weight: 1 },
  ],
  'dating-relationships': [
    { term: 'dating app', weight: 2 },
    { term: 'dating site', weight: 2 },
    { term: 'online dating', weight: 2 },
    { term: 'matchmaker', weight: 2 },
    { term: 'matchmaking', weight: 2 },
    { term: 'dating coach', weight: 2 },
    { term: 'relationship counselor', weight: 2 },
    { term: 'speed dating', weight: 1 },
    { term: 'singles events', weight: 1 },
    { term: 'marriage counselor', weight: 1 },
    { term: 'love coach', weight: 1 },
    { term: 'couples therapy', weight: 1 },
  ],
};

module.exports = { INDUSTRY_ALIASES };
